Add admin endpoint to terminate subscriptions
RedHatInsights/rhsm-subscriptions pull request #1055
Opened 2022-05-31 15:59 UTC by awood

https://issues.redhat.com/browse/ENT-4932

PAYG subscriptions terminated more than an hour from the current time
will log a warning.

2022-05-31 19:49 UTC, InsightsDroid commented
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
1aa2e30b-483d-453c-b609-ee930b84e0a2
db0c9041-ef22-4360-91ca-ce18cc0c04af

2022-05-31 19:56 UTC, closed without merging

2022-06-01 15:33 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
> +    if (tagProfile.isProductPAYGEligible(subscription.getSku()) && delta > 0) {
This `if` statement doesn't work as intended. Reason being that subscription SKU is like `MW01882` where `isProductPAYGEligible` deals with swatch product tags like `rhosak`. So we need to do a couple of things here:
1. Lookup the offering based on the SKU (using `offeringRepository`).
2. Lookup the swatch product tag via offering - the data is in tag profile, but it doesn't look like we made a method for this yet.

2022-06-02 18:21 UTC, kahowell requested changes

2022-06-02 18:21 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
> +    if (tagProfile.isProductPAYGEligible(productTag) && delta > 0) {
I found that delta is negative if termination date is in the past. `Math.abs(delta)` helps

2022-06-07 18:02 UTC, kahowell commented
Confirmed via:

```
DEVTEST_EVENT_EDITING_ENABLED=true ./gradlew :bootRun&
http POST :8000/api/rhsm-subscriptions/v1/internal/subscriptions/terminate/12351253 x-rh-swatch-psk:dummy timestamp==2022-06-22T00:00:00Z
```