ENT-5014: Update aws producer to ignore metrics without awsDimension
RedHatInsights/rhsm-subscriptions pull request #1058
Opened 2022-05-31 21:56 UTC by ksynvrit

Add logic to isSnapshotApplicable method to skip unconfigured dimensions
Update Unit test for BillableUsageProcessor for skipping unknown dimension.
Add new method to TagProfile.

2022-05-31 22:18 UTC, InsightsDroid commented
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
45176059-71ec-4745-adf9-47d1fe462dd4
a3560f42-6ac5-4d41-ad8d-a5c809862c5c

2022-06-01 14:18 UTC, kahowell requested changes

2022-06-01 14:42 UTC, ksynvrit commented on swatch-producer-aws/src/main/java/com/redhat/swatch/files/TagProfile.java
> +                product, TallySnapshotTallyMeasurements.UomEnum.TRANSFER_GIBIBYTES.name()));
Depending on whose branch get merged in first. the `tallySnapshot.getTallyMeasurements().get(0).getUom().name()` would be replaced with `billable.getUom().name()`.

2022-06-01 14:55 UTC, kahowell approved these changes

2022-06-01 16:34 UTC, merged