Add Internal Billing API to get remittances data.
RedHatInsights/rhsm-subscriptions pull request #1191
Opened 2022-06-30 14:04 UTC by ksynvrit

https://issues.redhat.com/browse/ENT-5096

Testing Steps:
1. Insert data into local database
```
insert into public.billable_usage_remittance (account_number, org_id, product_id, metric_id, accumulation_period, sla, usage, billing_provider, billing_account_id, remitted_value, remittance_date, version) values ('account123', null, 'rhosak', 'Instance-Hours', '2022-07', '_ANY', '_ANY', 'redhat', 'dummy', 10, '2022-07-27 13:04:51.977000 +00:00', 1);
insert into public.billable_usage_remittance (account_number, org_id, product_id, metric_id, accumulation_period, sla, usage, billing_provider, billing_account_id, remitted_value, remittance_date, version) values ('account123', null, 'rhosak', 'Instance-Monthly', '2022-06', '_ANY', '_ANY', 'redhat', 'dummy', 10, '2022-06-27 13:01:26.048000 +00:00', 1);
```
2. Run Application and hit Internal Billing API using curl. :
```
curl --request GET \
  --url 'http://localhost:8000/api/rhsm-subscriptions/v1/internal/remittance/accountRemittances?accountNumber=account123&productId=rhosak' \
  --header 'accept: application/vnd.api+json' \
  --header 'content-type: application/json' \
  --header 'x-rh-swatch-psk: dummy' \
  --data '{}'
```
3. Should return a list of Monthly Remittance. If you want you can get more specific, but make sure you add an `org Id `in the database. The current implementation of the internal billing API `org Id` will take precedent over `accountNumber` in the query of the remittance table.

2022-06-30 14:53 UTC, InsightsDroid commented
Test results are available in Ibutsu:
https://url.corp.redhat.com/ibutsu-runs-6f110601-573b-43b0-bb1a-f44b07967adc

2022-06-30 15:14 UTC, barnabycourt commented
retest this please

2022-06-30 20:38 UTC, kahowell requested changes

2022-06-30 20:38 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingController.java
> +public class InternalBillingController {
Let's log at debug instead in this class, please. The response contains the same information (w/ use of `jq)`, so feels more appropriate to use debug level here.

2022-06-30 20:38 UTC, kahowell commented on src/main/spec/internal-billing-api-spec.yaml
> +        required: true
Let's go ahead and make it false, and instead validate that one of `orgId`, `accountNumber` is present in the API controller instead.

2022-06-30 20:38 UTC, kahowell commented on src/main/spec/internal-billing-api-spec.yaml
> +      properties:
Can you go please ahead and add accumulationPeriod?

2022-07-01 17:53 UTC, kahowell approved these changes

2022-07-01 20:19 UTC, merged