SWATCH-288: Update Jenkins pipeline to use containers as nodes
RedHatInsights/rhsm-subscriptions pull request #1257
Opened 2022-07-26 20:32 UTC by lindseyburnett

Instead of using "fedora" or "fedora35" node on the SMQE jenkins instance for our **continuous-integration/jenkins/pr-merge** check for each PR, have jenkins spin up a new container to use as a build node.

"Testing"/Verification

If you click "Details" in the checks section of this PR, and then navigate to the Jenkins instance[0]  (top right corner....icon that kind of looks like logout), and then open the console output and View Full Log....you'll be able to see near the top that an agent was provisioned based on a pod spec yaml. 

If the job has been ran recently, you can actually click into the linked agent name that got spun up and see some details within Jenkins.  You can also take that name and search for it in the openshift console [1], where you can view the node and access the terminal.

[0] https://stage-jenkins-csb-smqe.apps.ocp4.prod.psi.redhat.com/job/Subscriptions%20PR%20Check/
[1] https://console-openshift-console.apps.ocp4.prod.psi.redhat.com/topology/ns/jenkins-csb-smqe?view=graph

2022-07-27 16:01 UTC, lindseyburnett commented
/retest

2022-07-27 17:55 UTC, lindseyburnett commented
close to stop the auto build spam

2022-07-28 14:16 UTC, kahowell requested changes

2022-07-28 14:16 UTC, kahowell commented on Jenkinsfile
> +            label 'swatch' // this value + unique identifier becomes the label
becomes the pod name?

2022-07-28 14:16 UTC, kahowell commented on Jenkinsfile
> +                   sh "./gradlew  --no-daemon  sonarqube -Duser.home=/tmp -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.login=${SONAR_AUTH_TOKEN} -Dsonar.pullrequest.key=${CHANGE_ID} -Dsonar.pullrequest
Nitpick: extraneous space character throughout between `gradlew` and `--no-daemon`

2022-07-28 14:16 UTC, kahowell commented on Jenkinsfile
> +       stage('Build') {
Probably worth commenting that what this effectively invokes with a comment, consider changing stage name too; suggestion: `Build/Test/Lint`

2022-07-28 14:48 UTC, kahowell approved these changes

2022-07-28 16:29 UTC, merged