SWATCH-253: Add support for Kafka over TLS and using SASL
RedHatInsights/rhsm-subscriptions pull request #1283
Opened 2022-07-29 18:18 UTC by awood

# Testing
* You'll need to destroy your existing `kafka` pod and recreate it with the new TLS configuration.  Myself, I have just been bringing everything down with `podman-compose down`, then `podman-compose up -d`.  This series of commands will wipe your dev database though.  Either do a `pg_dump` before `podman-compose down` and do an import after `podman-compose up`.  *OR* `podman stop` and `podman rm` the `rhsm-subscriptions_kafka_1` and run `podman-compose up` again.  I believe that will be sufficient to just recreate the Kafka container.  I would appreciate verification of this though.  It seems to work for me after some quick testing.
* Start the application with some extra logging:
  ```
  ./gradlew :bootRun --args="--logging.level.org.apache.kafka.common.security.ssl=DEBUG \
  --logging.level.org.apache.kafka.common.network.SslTransportLayer=DEBUG \
  --logging.level.org.apache.kafka.common.security.authenticator.SaslClientAuthenticator=DEBUG"
  ```
* You should see the TLS connection get established and the SASL authentication succeed.
* Ensure TLS settings are the default by trying to connect to the non-TLS port:
  `./gradlew :bootRun --args="--spring.kafka.bootstrap-servers=localhost:9092" `
  Connection errors will result because SWatch is trying to talk TLS on a non-TLS port:
  "Connection to node -1 (localhost/127.0.0.1:9092) terminated during authentication."

# TODO
- [ ] Send a note to all devs when this merges indicating that they will need to recreate their `kafka` pod.

2022-08-02 18:48 UTC, kahowell commented
/retest

2022-08-05 20:52 UTC, kahowell commented
FYI, failing in EE w/

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.kafka.jaas.options.username' to java.lang.String:

    Property: spring.kafka.jaas.options.username
    Value: "${KAFKA_USERNAME}"
    Origin: class path resource [swatch-core/application.yaml] from rhsm-subscriptions-1.1.0-snapshot.202208052011.uncommitted+a57d8ea.jar!/BOOT-INF/lib/swatch-core-1.1.0-snapshot.202208052011.uncommitted+a57d8ea.jar - 208:19
    Reason: java.lang.IllegalArgumentException: Could not resolve placeholder 'clowder.kafka.brokers[0].sasl.username' in value "${clowder.kafka.brokers[0].sasl.username}"

Action:

Update your application's configuration
```

2022-08-08 15:25 UTC, lindseyburnett commented
/retest

2022-08-08 19:24 UTC, awood commented
Which pod was failing with that error, @kahowell?

2022-08-10 07:57 UTC, ntkathole commented
> Which pod was failing with that error, @kahowell?

@awood I see Job build artifacts has rhsm-subscriptions-worker-648ff977f4-kdzwl_rhsm-subscriptions-worker-init.log file showing above error.

2022-08-11 19:40 UTC, awood commented
I made a push that at least fixes the issue with the init pods, but the ultimate issue looks like there's no `cdappconfig.json` file being read during the Jenkins run.  @kahowell Let's talk Monday and see if we can figure this out.

2022-08-25 15:15 UTC, barnabycourt commented
/retest

2022-08-26 17:47 UTC, lindseyburnett commented
/retest

2022-08-26 21:56 UTC, lindseyburnett commented
/retest

2022-08-29 14:55 UTC, lindseyburnett commented
/retest

2022-08-31 20:34 UTC, kahowell requested changes
Overall looks good, left a couple inline comments; also can you please s/dummy/placeholder in
* `config/kafka/client.properties`
* `config/kafka/clowder-config-test.json`
* `config/kafka/kafka_server_jaas.conf`
* `swatch-core/src/main/resources/swatch-core/application.yaml`
?

2022-08-31 20:34 UTC, kahowell commented on deploy/clowder.md
> +Clouddout documentation, but here are some essentials:
Typo: Clouddout; at first I read this as "cloud-doubt" :joy: .

2022-08-31 20:34 UTC, kahowell commented on deploy/clowder.md
> +```
Mind to correct the path in swatch-api, while you are making changes?

2022-09-01 18:39 UTC, kahowell commented
/retest

2022-09-01 19:53 UTC, kahowell approved these changes

2022-09-01 19:53 UTC, kahowell commented
failing test: `tests.e2e.test_ephemeral_conduit.test_e2e_conduit_ephermal` unrelated

2022-09-02 17:21 UTC, merged