SWATCH-124: Move metrics-worker to its own ClowdApp
RedHatInsights/rhsm-subscriptions pull request #1288
Opened 2022-08-01 16:07 UTC by lindseyburnett

https://issues.redhat.com/browse/SWATCH-124

2022-08-01 23:10 UTC, lindseyburnett commented
/rebase

2022-08-02 02:27 UTC, lindseyburnett commented
/retest

2022-08-04 14:05 UTC, kahowell requested changes

2022-08-04 14:05 UTC, kahowell commented on deploy/rhsm-clowdapp.yaml
> -      - name: subscription-sync
Should also remove `capacity-ingress`

2022-08-10 16:25 UTC, lindseyburnett commented
/retest

2022-08-10 18:12 UTC, mstead approved these changes
Approve pending pr_checks passing.

2022-08-10 18:42 UTC, merged