Add OrgId to Account services table and implement placeholders
RedHatInsights/rhsm-subscriptions pull request #1363
Opened 2022-08-24 18:35 UTC by ksynvrit

Created new changelog for Account service table
Add new field for AccountServiceInventory
Add new logic for UsageCollector for both Inventory & Metrics
Add Draft changelog for future cards are completed.

2022-09-06 08:02 UTC, ntkathole commented
Tests are failing for UPDATE_HOURLY_SNAPSHOTS operation throwing NullPointerException while collecting snapshots

`2022-09-06 06:15:18,634 [thread=rhsm-subscriptions-task-processor-0-C-1] [INFO ] [org.candlepin.subscriptions.task.queue.kafka.KafkaTaskProcessor] - Message received from kafka: {"groupId": "platform.rhsm-subscriptions.tasks", "type": "UPDATE_HOURLY_SNAPSHOTS", "args": {"accountNumber": ["7147355"], "endDateTime": ["2022-09-06T07:00:00Z"], "startDateTime": ["2022-09-06T03:00:00Z"]}}`

```
2022-09-06 06:15:24,911 [thread=rhsm-subscriptions-task-processor-0-C-1] [ERROR] [org.candlepin.subscriptions.tally.TallySnapshotController] - Could not collect metrics and/or produce snapshots for account 7147355
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at java.base/java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:194)
	at java.base/java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:191)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.candlepin.subscriptions.tally.MetricUsageCollector.collect(MetricUsageCollector.java:154)
	at org.candlepin.subscriptions.tally.MetricUsageCollector$$FastClassBySpringCGLIB$$474faa26.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.candlepin.subscriptions.tally.MetricUsageCollector$$EnhancerBySpringCGLIB$$4887e476.collect(<generated>)
	at org.candlepin.subscriptions.tally.TallySnapshotController.lambda$produceHourlySnapshotsForAccount$1(TallySnapshotController.java:133)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209)
	at org.candlepin.subscriptions.tally.TallySnapshotController.lambda$produceHourlySnapshotsForAccount$2(TallySnapshotController.java:131)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.candlepin.subscriptions.tally.TallySnapshotController.produceHourlySnapshotsForAccount(TallySnapshotController.java:120)
	at org.candlepin.subscriptions.tally.TallySnapshotController$$FastClassBySpringCGLIB$$e4d59262.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at io.micrometer.core.aop.TimedAspect.processWithTimer(TimedAspect.java:221)
	at io.micrometer.core.aop.TimedAspect.perform(TimedAspect.java:196)
	at io.micrometer.core.aop.TimedAspect.timedMethod(TimedAspect.java:188)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.candlepin.subscriptions.tally.TallySnapshotController$$EnhancerBySpringCGLIB$$1e64ef59.produceHourlySnapshotsForAccount(<generated>)
	at org.candlepin.subscriptions.tally.tasks.CaptureMetricsSnapshotTask.execute(CaptureMetricsSnapshotTask.java:50)
	at org.candlepin.subscriptions.task.TaskWorker.executeTask(TaskWorker.java:44)
	at org.candlepin.subscriptions.task.queue.kafka.KafkaTaskProcessor.receive(KafkaTaskProcessor.java:57)
	at org.candlepin.subscriptions.task.queue.kafka.KafkaTaskProcessor$$FastClassBySpringCGLIB$$e481aead.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at io.micrometer.core.aop.TimedAspect.processWithTimer(TimedAspect.java:221)
	at io.micrometer.core.aop.TimedAspect.perform(TimedAspect.java:196)
	at io.micrometer.core.aop.TimedAspect.timedMethod(TimedAspect.java:188)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.spr [...]

2022-09-07 15:45 UTC, kahowell requested changes

2022-09-07 15:45 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
> +        .findFirst()
Apparently, `findFirst()` does not allow nulls [per the javadocs](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#findFirst--). Found via https://stackoverflow.com/a/32476601

I played around a bit in `jshell` which made it easy to reproduce:

```
Stream.of(1).map(a -> null).findFirst().ifPresent((a) -> {})
```

fails with a similar stacktrace. You can easily work around by filtering null values out:

```
Stream.of(1).map(a -> null).filter(Objects::nonNull).findFirst().ifPresent((a) -> {})
```

So I would suggest:
```suggestion
        .filter(Objects::nonNull)
        .findFirst()
```
(will need to adjust import statements afterwards).

2022-09-07 17:41 UTC, kahowell approved these changes
approved, assuming tests will pass

2022-09-07 18:01 UTC, merged