SWATCH-643 Map tally usage by orgId instead of account number
RedHatInsights/rhsm-subscriptions pull request #1644
Opened 2022-11-17 14:41 UTC by mstead

AccountUsageCalculations are now based on orgId and all usage
collection mappings are now done by orgId instead of
account number.

This refactor allowed for completely removing account dependancy
from all cloudigrade usage collection.

## Testing
Clean out the DBs:
```
psql -h localhost -U insights insights <<EOF
delete from hosts;
EOF

psql -h localhost -U rhsm-subscriptions rhsm-subscriptions <<EOF
delete from events;
delete from tally_snapshots;
delete from tally_measurements;
delete from instance_monthly_totals;
delete from instance_measurements;
delete from billable_usage_remittance;
EOF
```

Insert some hosts.

```shell
bin/insert-mock-hosts \
  --num-hypervisors 1 \
  --num-guests 4 \
  --hbi \
  --clear \
  --org org123
```

Run the service:
```shell
DEV_MODE=true ./gradlew :bootRun
```

Ensure opt-in:

```shell
http :9000/hawtio/jolokia \
  type=exec \
  mbean=org.candlepin.subscriptions.jmx:name=optInJmxBean,type=OptInJmxBean \
  operation='createOrUpdateOptInConfig(java.lang.String,java.lang.String,boolean,boolean,boolean)' \
  arguments:='["account123","org123",true,true,true]'
```

Trigger a nightly tally:

```shell
http :9000/hawtio/jolokia \
  type=exec \
  mbean=org.candlepin.subscriptions.jmx:name=tallyJmxBean,type=TallyJmxBean \
  operation='tallyOrg(java.lang.String)' \
  arguments:='["org123"]'
```

Verify the tally ran completely, and check the data.
```
select org_id, granularity, snapshot_date, uom, value from tally_snapshots s inner join tally_measurements m on s.id = m.snapshot_id where measurement_type='TOTAL'  and product_id='RHEL' and sla='_ANY' and usage='_ANY' and billing_provider='_ANY' and billing_account_id='_ANY' order by snapshot_date desc, granularity, uom;
```

**Run the tally again, and ensure that it results in the same number of snapshots and spotcheck to make sure they did not change.**

Next test the hourly metering tally. Start by cleaning out the DB.
```
psql -h localhost -U rhsm-subscriptions rhsm-subscriptions <<EOF
delete from events;
delete from tally_snapshots;
delete from tally_measurements;
delete from instance_monthly_totals;
delete from instance_measurements;
delete from billable_usage_remittance;
EOF
```

Load some events into the DB.
```
bin/import-events.py --file bin/events.csv
```

Opt In the account:
```
http :9000/hawtio/jolokia \
  type=exec \
  mbean=org.candlepin.subscriptions.jmx:name=optInJmxBean,type=OptInJmxBean \
  operation='createOrUpdateOptInConfig(java.lang.String,java.lang.String,boolean,boolean,boolean)' \
  arguments:='["account123","org123",true,true,true]'
```

Run the hourly tally:
```
http :9000/hawtio/jolokia \
  type=exec \
  mbean=org.candlepin.subscriptions.jmx:name=tallyJmxBean,type=TallyJmxBean \
  operation='tallyAllAccountsByHourly(java.lang.String,java.lang.String)' \
  arguments:='["2021-10-18T00:00Z","2021-10-19T00:00Z"]'
```

Verify the tally ran, and check the data. Make sure that the summations from the 2 and 3rd queries line up with those in the first.
```
-- Get the instance totals
select h.instance_id, t.uom, t.value from instance_monthly_totals t, hosts h where t.instance_id = h.id and month='2021-10' and h.instance_id::text in (select distinct e.instance_id from events e where e.org_id='org123' and extract(month from e.timestamp) = 10) order by h.instance_id;

-- Verify Cores
select e.instance_id, sum((measurements->>'value')::numeric) from events e, jsonb_array_elements(data->'measurements') measurements where org_id='org123' and extract(month from timestamp) = 10 and measurements->>'uom' = 'Cores' group by e.instance_id order by instance_id;

-- Verify Instance Hours
select e.instance_id, sum((measurements->>'value')::numeric) from events e, jsonb_array_elements(data->'measurements') measurements where org_id='org123' and extract(month from timestamp) = 10 and measurements->>'uom' = 'Instance-hours' group by e.instance_id order by instance_id;
```

**Re-run the tally and ensure that the values do not change. This is the key part that the mapping changes affect.**

2022-11-17 15:40 UTC, ntkathole commented
/retest

2022-11-18 21:45 UTC, kahowell requested changes

2022-11-22 19:48 UTC, mstead commented on src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
DONE

2022-11-22 19:48 UTC, mstead commented on src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
> +                        orgId,
DONE

2022-11-22 19:49 UTC, mstead commented on src/main/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategy.java
>        return snapStream.collect(Collectors.groupingBy(TallySnapshot::getAccountNumber));
ugh... brutal. Good eye there. Thanks.

2022-11-22 19:49 UTC, mstead commented on src/main/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategy.java
>        return snapStream.collect(Collectors.groupingBy(TallySnapshot::getAccountNumber));
DONE

2022-11-28 07:22 UTC, ntkathole commented
Tally pod has traceback 

```
2022-11-23 13:52:57,828 [thread=rhsm-subscriptions-task-processor-0-C-1] [ERROR] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] - ERROR: null value in column "account_number" violates not-null constraint
  Detail: Failing row contains (null, HBI_HOST, 14540822).
2022-11-23 13:52:57,829 [thread=rhsm-subscriptions-task-processor-0-C-1] [ERROR] [org.candlepin.subscriptions.tally.TallySnapshotController] - Could not collect existing usage snapshots for orgId=14540822
org.springframework.dao.DataIntegrityViolationException: could not execute batch; SQL [insert into account_services (account_number, org_id, service_type) values (?, ?, ?)]; constraint [account_number]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch
```

2022-11-28 14:20 UTC, mstead commented
> Tally pod has traceback
> 
> ```
> 2022-11-23 13:52:57,828 [thread=rhsm-subscriptions-task-processor-0-C-1] [ERROR] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] - ERROR: null value in column "account_number" violates not-null constraint
>   Detail: Failing row contains (null, HBI_HOST, 14540822).
> 2022-11-23 13:52:57,829 [thread=rhsm-subscriptions-task-processor-0-C-1] [ERROR] [org.candlepin.subscriptions.tally.TallySnapshotController] - Could not collect existing usage snapshots for orgId=14540822
> org.springframework.dao.DataIntegrityViolationException: could not execute batch; SQL [insert into account_services (account_number, org_id, service_type) values (?, ?, ?)]; constraint [account_number]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch
> ```

Thanks Nikhil, this helps a lot. There's a couple things that need to happen on the tally side:
1. account_services should have the not-null constraint removed for account_number (only org_id should be non-null).
2. I accidentally removed the code that sets the account number on the account_service __when it exists__. This should still set it when available.

A new card will be made for (1) if it doesn't exist already, and I'll make the required changes to this PR to fix the test failures.

2022-11-29 07:35 UTC, ntkathole commented
/retest

2022-11-29 20:10 UTC, kahowell approved these changes

2022-11-29 20:11 UTC, merged