(DRAFT) SWATCH-803 CRUD apis for swatch-contracts
RedHatInsights/rhsm-subscriptions pull request #1821
Opened 2023-02-02 21:08 UTC by lindseyburnett

2023-02-03 19:19 UTC, lindseyburnett commented
/retest

2023-02-03 19:20 UTC, lindseyburnett commented
/retest

2023-02-20 07:49 UTC, ntkathole commented
/retest

2023-02-28 19:32 UTC, mstead requested changes
I tried to check existing cards to see if anything I've commented on will be covered elsewhere, so I apologize in advance if I missed them. :)

Some general comments:
* Would it make sense to describe 'local deploy with bonfire' in a README?
* Personally I'd like to see some additional package structure. i.e Can we move the DB related classes to its own package? Could create an additional card to do this, or serve as a discussion point.
* There are some test specific annotations being used which could benefit from some documentation somewhere (mostly around intent so that others can follow suit when needed)
   * `@DisabledIfEnvironmentVariable(named = "CI", matches = "true")`
   * `@Tag("integration")`

2023-02-28 19:32 UTC, mstead commented on swatch-contracts/src/main/java/com/redhat/swatch/ContractService.java
> +            });
Found a card that appears to cover this. Please ignore.

2023-02-28 19:32 UTC, mstead commented on swatch-contracts/src/main/java/com/redhat/swatch/ContractService.java
> +            });
Found a card that appears to cover this. Please ignore.

2023-02-28 20:08 UTC, lindseyburnett commented
> * Would it make sense to describe 'local deploy with bonfire' in a README?
I think our main README.md has a section about this.  Might need updating.

> * Personally I'd like to see some additional package structure. i.e Can we move the DB related classes to its own package? Could create an additional card to do this, or serve as a discussion point.
I added this as a dev sync agenda item.  Seeing things lately in quarkus apps where people are moving away from a bunch of separate packages.

2023-02-28 20:44 UTC, kartikshahc commented on swatch-contracts/src/test/java/com/redhat/swatch/ContractServiceTest.java
> +    // new.startDate == old.endDate
Will take care in next card

2023-02-28 20:44 UTC, kartikshahc commented on swatch-contracts/src/test/java/com/redhat/swatch/ContractServiceTest.java
> +  void testUpdateContract() {
:) Will take care in following card

2023-02-28 20:44 UTC, kartikshahc commented on swatch-contracts/src/test/java/com/redhat/swatch/BaseUnitTest.java
> +  }
Done

2023-02-28 20:45 UTC, merged