Remove SearchCriteria and SearchOperation classes in favor of Spring Specification search
RedHatInsights/rhsm-subscriptions pull request #1862
Opened 2023-02-20 18:47 UTC by awood

# Testing
## TallyInstanceViewRepository
Apply the following patch by saving the contents of the block below to `tallyInstanceViewRepositoryTest.patch` and running `patch -p1 < tallyInstanceViewRepositoryTest.patch`
```patch
diff --git a/src/test/java/org/candlepin/subscriptions/db/TallyInstanceViewRepositoryTest.java b/src/test/java/org/candlepin/subscriptions/db/TallyInstanceViewRepositoryTest.java
index 93dcc53d..d1ece648 100644
--- a/src/test/java/org/candlepin/subscriptions/db/TallyInstanceViewRepositoryTest.java
+++ b/src/test/java/org/candlepin/subscriptions/db/TallyInstanceViewRepositoryTest.java
@@ -52,6 +52,8 @@ import org.junit.jupiter.api.TestInstance;
 import org.junit.jupiter.api.TestInstance.Lifecycle;
 import org.junit.jupiter.params.ParameterizedTest;
 import org.junit.jupiter.params.provider.MethodSource;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.boot.test.context.SpringBootTest;
 import org.springframework.data.domain.Page;
@@ -512,6 +514,42 @@ class TallyInstanceViewRepositoryTest {
         HardwareMeasurementType.EMPTY, results.getContent().get(0).getKey().getMeasurementType());
   }
 
+  private static final Logger log = LoggerFactory.getLogger(TallyInstanceViewRepositoryTest.class);
+  @Transactional
+  @Test
+  void testFindAllBy() {
+    Host host1 = createHost(UUID.randomUUID().toString(), "a1");
+    host1.setBillingProvider(BillingProvider.RED_HAT);
+    addBucketToHost(
+        host1,
+        COOL_PROD,
+        ServiceLevel.PREMIUM,
+        Usage.PRODUCTION,
+        HardwareMeasurementType.AWS,
+        BillingProvider.RED_HAT);
+
+    persistHosts(host1);
+    Pageable page = PageRequest.of(0, 10);
+
+    log.info("Find all by begins now");
+    Page<TallyInstanceView> results =
+        repo.findAllBy(
+            "ORG_a1",
+            COOL_PROD,
+            ServiceLevel.PREMIUM,
+            Usage.PRODUCTION,
+            "foo",
+            0,
+            0,
+            "2021-01",
+            Uom.CORES,
+            BillingProvider.RED_HAT,
+            "_ANY",
+            HardwareMeasurementType.getCloudProviderTypes(),
+            page);
+    log.info("Query complete");
+  }
+
   @Transactional
   @Test
   void testFilterByCloudHardwareMeasurementTypes() {
```
This patch creates a test case that just runs a `TallyInstanceViewRepository.findAllBy` call that exercises all the potential additions to the `where` clause.

On the `main` branch, run
```shell
SPRING_APPLICATION_JSON='{"spring":{"jpa":{"show-sql":"true","properties":{"hibernate":{"format_sql":"true"}}}}}' ./gradlew -i clean :test --tests="TallyInstanceViewRepositoryTest.testFindAllBy"
```
and copy the generated SQL that appears between the two log lines in the test (represented by the ellipses in the block below).  Paste the generated SQL into a file named `tallyInstanceView-old.txt`
```
[thread=Test worker] [INFO ] [org.candlepin.subscriptions.db.TallyInstanceViewRepositoryTest] - Find all by begins now
...
[thread=Test worker] [INFO ] [org.candlepin.subscriptions.db.TallyInstanceViewRepositoryTest] - Query complete
```

Now check out this branch, rerun the same command, and paste the generated SQL into a file named `tallyInstanceView-new.txt`.  Do a `diff` between these two files.
```diff
--- tallyInstanceView-old.txt   2023-02-20 11:24:46.818633722 -0500
+++ tallyInstanceView-new.txt   2023-02-20 11:59:26.789224108 -0500
@@ -24,7 +24,9 @@
         instance_monthly_totals monthlytot1_
             on tallyinsta0_.id=monthlytot1_.instance_id
     where
-        tallyinsta0_.org_id=?
+        tallyinsta0_.cores>=0
+        and tallyinsta0_.sockets>=0
+        and tallyinsta0_.org_id=?
         and tallyinsta0_.product_id=?
         and tallyinsta0_.sla=?
         and tallyinsta0_.usage=?
@@ -34,8 +36,6 @@
             lower(tallyinsta0_.display_name) like ?
         )
         and tallyinsta0_.uom=?
-        and tallyinsta0_.cores>=0
-        and tallyinsta0_.sockets>=0
         and monthlytot1_.month=?
         and monthlytot1_.uom=?
         and (
```

The diff demonstrates that the queries are logically identical.  There is a small change in the placement of a few clauses based on how I wrote the new code but I attempted to keep everything as similar as reasonably possible.

2023-02-23 14:57 UTC, kahowell requested changes
Overall looks good to me, I'm not excited about the redundant joins in HostRepository, but since we're deprecating the Hosts API, we can live with it. Needs a rebase, and there is a stale TODO

2023-02-23 14:57 UTC, kahowell commented on src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
> +  // TODO More tests
Stale TODO?

2023-02-23 14:58 UTC, awood commented on src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
> +  // TODO More tests
Oops!

2023-02-27 21:33 UTC, kahowell approved these changes

2023-02-28 02:03 UTC, merged