Apply origin/referer check to all jolokia requests
RedHatInsights/rhsm-subscriptions pull request #189
Opened 2020-09-22 19:31 UTC by kahowell

Even GET requests, as those can actually cause bean invocation in Jolokia.

To be consistent with the AntiCsrfFilter, I made it so that `DEV_MODE=true` causes the origin/referer check to be turned off.

To test, try running in the following configurations:

1. `DEV_MODE=true ./gradlew bootRun`: http://localhost:8080/actuator/jolokia will be fully open
2. `./gradlew bootRun`: http://localhost:8080/actuator/hawtio will be non-functional because /actuator/jolokia requests are rejected based on the default origin suffix of .redhat.com w/ port 443.
3. `RHSM_SUBSCRIPTIONS_ANTI_CSRF_DOMAIN_SUFFIX=localhost RHSM_SUBSCRIPTIONS_ANTI_CSRF_PORT=8080 ./gradlew`: http://localhost:8080/actuator/hawtio be functional

Note that there is some nuance, as hitting `/actuator/jolokia` with `GET` (when visiting with a browser), doesn't send an `Origin` header. So with the restrictor turned on, visiting /actuator/jolokia is fruitless even with the correct domain suffix/port set.

2020-09-22 19:37 UTC, kahowell commented
044088f to 2e8301e: added application.yaml changes.

2020-09-23 19:01 UTC, kahowell commented
2e8301e to 6a6fec2: rebase

2020-10-02 18:49 UTC, awood requested changes
I had to rebase onto master to get this running because of the Java 11 changes, but even with the rebase, I'm not getting the behavior you describe.  Hawtio comes up and I can invoke JMX beans just fine.  The Jolokia endpoint is accessible also.

I'm not sure where (or if) I'm going wrong exactly.  Would you mind doing a double-check on your end and make sure it works as expected?  If so, we can sit down and maybe try to puzzle out what's going wrong on my end.

2020-10-02 20:29 UTC, kahowell commented
@awood I rebased locally, and it still works as described. Is it possible you have a `config/application.properties` locally or an env var where you've set `DEV_MODE`? Otherwise, let's sync up on Monday about it.

2020-10-05 17:20 UTC, awood commented
>  Is it possible you have a `config/application.properties` locally or an env var where you've set `DEV_MODE`?

D'oh

2020-10-08 14:01 UTC, kahowell commented
6a6fec2 to 948698d: rebase

2020-10-12 18:10 UTC, kahowell commented
Closed in favor of #202

2020-10-12 18:10 UTC, closed without merging