Add opt in stats to OptInJmxBean
RedHatInsights/rhsm-subscriptions pull request #192
Opened 2020-09-29 20:27 UTC by kahowell

To test, run with `./gradlew bootRun`.

Then open http://localhost:8080/actuator/hawtio/jmx/attributes?nid=root-org.candlepin.subscriptions.jmx-OptInJmxBean-optInJmxBean&pref=Connect

Observe the values of two fields:

- Current week opt in count
- Last week opt in count

In a terminal, simulate an opt-in:

```
echo "insert into account_config(account_number, sync_enabled, reporting_enabled, opt_in_type, created, updated) values ('optin0', true, true, 'API', now(), now());" | psql -h localhost -U rhsm-subscriptions
```

and observe that `Current week opt in count` is incremented by one (5 second polling interval in hawtio by default).

Insert a record to mock a previous week's opt-in:

```
echo "insert into account_config(account_number, sync_enabled, reporting_enabled, opt_in_type, created, updated) values ('optin1', true, true, 'API', now() + interval '-7 days', now() + interval '-7 days');" | psql -h localhost -U rhsm-subscriptions
```

and observe that `Last week opt in count` is incremented.

I'm open to making these methods rather than attributes if there is concern about the auto-refresh from hawtio.

Also, try the new JMX operation: `getOptInCountForWeekOf(String)`, passing in the current date in YYYY-MM-DD format.

2020-10-02 18:58 UTC, awood requested changes

2020-10-02 18:58 UTC, awood commented on src/main/java/org/candlepin/subscriptions/jmx/OptInJmxBean.java
> +
Let's DRY.  I'm writing this off the top of my head, so I'm not going to put it up as a GitHub suggestion, but I think you can just copy-paste it and clean up any erroneous syntax.

```java
@ManagedAttribute(description = "Count of how many orgs opted-in in the previous week.")
public int getLastWeekOptInCount() {
    OffsetDateTime weekDate = OffsetDateTime.now().minusWeeks(1);
    return weekCount(weekDate);
}
   
@ManagedAttribute(description = "Count of how many orgs opted-in in the current week.")
public int getCurrentWeekOptInCount() {
    OffsetDateTime weekDate = OffsetDateTime.now();
    return weekCount(weekDate);
}

@ManagedOperation(description = "Fetch the number of orgs opted-in in a given week.")
@ManagedOperationParameter(name = "weekOf", description = "Date in the week to query; YYYY-MM-DD format")
public int getOptInCountForWeekOf(String weekOf) throws ParseException {
    OffsetDateTime weekDate = OffsetDateTime
        .ofInstant(new SimpleDateFormat("yyyy-MM-dd").parse(weekOf).toInstant(), ZoneOffset.UTC);
    return weekCount(weekDate);
}

protected int weekCount(OffsetDateTime weekDate) {
    OffsetDateTime begin = clock.startOfWeek(weekDate);
    OffsetDateTime end = clock.endOfWeek(weekDate);
    return repo.getCountOfOptInsForDateRange(begin, end);
}
```

2020-10-05 18:38 UTC, kahowell commented
- dc04b98 to 2e828e3: rebase against master
- 2e828e3 to 5f65d71: DRY

@awood please take another look

2020-10-06 15:16 UTC, awood approved these changes

2020-10-06 15:16 UTC, merged