SWATCH-1014 Configure ActiveMQ
RedHatInsights/rhsm-subscriptions pull request #1941
Opened 2023-03-10 16:12 UTC by kartikshahc

2023-03-22 18:24 UTC, kartikshahc commented
/retest

2023-03-27 18:04 UTC, kahowell requested changes

2023-03-27 20:06 UTC, kartikshahc commented on swatch-contracts/src/main/resources/application.properties
> +quarkus.artemis.url=tcp://localhost:61616
done

2023-03-27 20:06 UTC, kartikshahc commented on swatch-contracts/src/main/java/com/redhat/swatch/ContractUMBDummyProducer.java
> +public class ContractUMBDummyProducer {
done

2023-03-27 20:06 UTC, kartikshahc commented on swatch-contracts/src/main/java/com/redhat/swatch/ActiveMQReactiveConfiguration.java
> +  URI brokerUrl;
done

2023-03-27 20:07 UTC, kartikshahc commented on swatch-contracts/deploy/clowdapp.yaml
> +    value: 'false'
done

2023-03-27 20:45 UTC, kartikshahc commented on swatch-contracts/build.gradle
> +    implementation 'org.apache.activemq:artemis-jms-client:2.28.0'
done

2023-03-27 21:19 UTC, kahowell commented
Note, test failure is unrelated, so we're going to go ahead and merge :-)

2023-03-27 21:19 UTC, merged