SWATCH-968: Add timestamp query param to GET contracts
RedHatInsights/rhsm-subscriptions pull request #1947
Opened 2023-03-13 14:58 UTC by kahowell

https://issues.redhat.com/browse/SWATCH-968

This is only the spec change, interface change, and I had to copy in OffsetDateTimeParamConverterProvider so that swatch-contracts can accept OffsetDateTime query params.

Implementation forthcoming w/ SWATCH-962

2023-03-13 15:34 UTC, kahowell commented
96d7f1b3 to 7108ae21: spotless apply

2023-03-13 19:36 UTC, lindseyburnett requested changes
Address code duplication that Sonar is mad about

https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&pullRequest=1947&id=rhsm-subscriptions&open=AYbbpGMWzqy-hRezJaSu

2023-03-17 18:35 UTC, kahowell commented
/retest

2023-03-17 20:53 UTC, lindseyburnett approved these changes

2023-03-17 20:53 UTC, merged