Make changes to system table API to support GUI
RedHatInsights/rhsm-subscriptions pull request #196
Opened 2020-10-01 17:34 UTC by mstead

Added DB/API fields:
* is_unmapped_guest
* is_hypervisor
* cloud_provider

HardwareType is one of 3 values:
* CLOUD
* PHYSICAL
* VIRTUALIZED

Fix broken script and set new fields

2020-10-08 15:25 UTC, kahowell requested changes
Overall, makes sense and works with some tweaks (see inline suggestion)

2020-10-13 08:13 UTC, san7ket commented
@kahowell I have a question, I see that there is this new field we are adding, `is_unmapped_guest`. Earlier, these orphan guests were treated as a separate virtual host, that consumed a sub. Now, with addition of the new field will that workflow stlll remain true, or will we simply skip these unmapped guests in tally, like we do for the mapped guests for a hypervisor.

2020-10-13 12:16 UTC, kahowell commented
@san7ket the workflow will stay the same. Our intent in providing the fields is that if the GUI wants to do something with them later, they can (e.g. if the GUI needs to distinguish between hypervisors and unmapped guests visually, it will have a flag available for that).

2020-10-14 21:02 UTC, kahowell approved these changes

2020-10-14 21:02 UTC, merged