Add new Admin Api for Contract Sync
RedHatInsights/rhsm-subscriptions pull request #1994
Opened 2023-03-24 21:53 UTC by ksynvrit

This is to create the Admin API to sync existing contracts and add new contracts if there are not already in the swatch-contract database.

Testing Steps: TBD

2023-04-03 10:21 UTC, san7ket commented
/retest

2023-04-04 20:42 UTC, kartikshahc commented on swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsTestingResource.java
> +    for (ContractEntity org : contracts) {
If the contracts list is empty then show the message "No active contract found for the orgIds"

2023-04-05 14:19 UTC, kartikshahc requested changes

2023-04-05 18:04 UTC, ksynvrit commented on swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
> +              persistExistingContract(entitlementEntity, OffsetDateTime.now());
I was using this to update existing records

2023-04-05 18:12 UTC, ksynvrit commented on swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
> +          OfferingProductTags productTags = syncResource.getSkuProductTags(sku);
I decide to use the `throw` declaration instead here. Let me know if your find with that

2023-04-05 20:24 UTC, kartikshahc commented on swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
> +              persistExistingContract(entitlementEntity, OffsetDateTime.now());
If its same record then I don't think we need to update. Unless you can think of a reason?

2023-04-07 12:37 UTC, kartikshahc requested changes

2023-04-07 14:52 UTC, kartikshahc approved these changes
LGTM

2023-04-07 15:27 UTC, merged