Incorporate opt-in checks into the Spring Security authorization layer
RedHatInsights/rhsm-subscriptions pull request #204
Opened 2020-10-19 20:59 UTC by awood

Rather than use a specific filter for the opt-in check, we can use
Spring Security's authorization facilities.  This leads to a cleaner
design and a less confusing architecture.

2020-11-05 20:50 UTC, kahowell commented
Overall I dig it. I noticed if you try to access one of the APIs without auth you get:

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class org.candlepin.subscriptions.security.InsightsUserPrincipal (java.lang.String is in module java.base of loader 'bootstrap'; org.candlepin.subscriptions.security.InsightsUserPrincipal is in unnamed module of loader 'app')
```.

Maybe just returning false if the principal is not `instanceof InsightsUserPrincipal` would work? Not picky about how to solve.

2020-11-05 20:51 UTC, kahowell requested changes
See above comment

2020-11-11 15:26 UTC, awood commented
> See above comment

Should be resolved now.

2020-11-11 16:36 UTC, kahowell approved these changes

2020-11-11 16:36 UTC, merged