Awood/better logging
RedHatInsights/rhsm-subscriptions pull request #205
Opened 2020-10-23 17:54 UTC by awood

* I want to add a few more items to the list of stacktrace-less errors.  I also want to get some opinions on how we want to configure the logging.  For example, it might make sense to have the stacktraces show during development runs in the ConsoleAppender, but not to appear in the SplunkAppender.  I think we definitely will want the stacktraces on during testing, which is easy enough to accomplish with the logback-testing.xml file.

## Testing

`curl -H "x-rh-identity: $(echo -n '{"identity":{"account_number":"account12345","type":"User","user":{"is_org_admin":true},"internal":{"org_id":"org123"}}}' 
| base64 -w 0)" "http://localhost:8080/api/rhsm-subscriptions/v1/hosts/products/RHEL?usage=Production&limit=1"`

That account is not opted-in, so an AccessDeniedException gets thrown.  With this commit, the error message appears, but there should be no accompanying stacktrace in the console log.

2020-11-06 21:54 UTC, kahowell requested changes
@awood tiny fix suggested. Otherwise looks good.

2020-11-06 21:54 UTC, kahowell commented on src/main/resources/logback-spring.xml
> +            <pattern>%d{yyyy-MM-dd'T'HH:mm:ss.SSS'+0000'} [thread=%t] [level=%p] [category=%c] %X{user} - %m%n%ex{full, SECURITY_STACKTRACE_EVAL}  </pattern>
```suggestion
            <pattern>%d{yyyy-MM-dd'T'HH:mm:ss.SSS'+0000'} [thread=%t] [level=%p] [category=%c] %X{user} - %m%n%ex{full, SECURITY_STACKTRACE_EVAL}</pattern>
```

2020-11-09 18:19 UTC, awood commented
> @awood tiny fix suggested. Otherwise looks good.

TYVM!

2020-11-09 19:57 UTC, kahowell approved these changes

2020-11-09 19:58 UTC, merged