SWATCH-788 Refactor all references ProductAllowlist to ProductDenylist
RedHatInsights/rhsm-subscriptions pull request #2123
Opened 2023-05-09 20:55 UTC by kartikshahc

…nylist

Jira issue: [SWATCH-XXXX](https://issues.redhat.com/browse/SWATCH-XXXX)

## Description

## Testing

### Setup

1.
1.

### Steps

1.
1.

### Verification

1.
1.

2023-05-10 18:07 UTC, mstead commented
/retest

2023-05-10 19:30 UTC, mstead requested changes
Looks good and tests well.

One small request. Please update your commit message to include a description of what changed. The description on the PR itself would work.

2023-05-10 19:50 UTC, kartikshahc commented
Changed the commit message as requested

2023-05-11 14:54 UTC, mstead approved these changes

2023-05-11 14:55 UTC, merged