Fix path lookups to work for `quarkus test`
RedHatInsights/rhsm-subscriptions pull request #2204
Opened 2023-06-06 17:41 UTC by kahowell

## Description

`quarkus test` runs in a different working directory than when running from Intellij or gradle builds. In order to allow tests to run in either, I implemented a lookup of the project directory by walking up the directory tree looking for `src`.

Before this change, running `quarkus test` doesn't work from the `swatch-contracts` directory, and afterwards it works.

## Testing

### Setup

1. Install the quarkus cli
2. `cd swatch-contracts`

### Steps

1. `git checkout main`
2. `quarkus test` (see failures)
3. ctrl+c after tests run
4. `git checkout khowell/quarkus_test_fixes`
5. `quarkus test` (see no failures)
6. ctrl+c after tests run

### Verification

1. Observe test failures during the first `quarkus test`
1. Observe no test failures during second `quarkus test`.

2023-06-06 19:52 UTC, lindseyburnett commented on swatch-contracts/src/test/java/com/redhat/swatch/contract/PathUtils.java
> +    ;
extra `;`

2023-06-06 19:53 UTC, lindseyburnett requested changes

2023-06-12 14:22 UTC, kahowell commented on swatch-contracts/src/test/java/com/redhat/swatch/contract/PathUtils.java
> +    ;
Fixed, thanks!

2023-06-13 14:49 UTC, lindseyburnett approved these changes

2023-06-13 15:09 UTC, merged