Jdhrh/offering table
RedHatInsights/rhsm-subscriptions pull request #232
Opened 2020-12-18 21:18 UTC by jdhrh

2021-01-06 20:16 UTC, kahowell requested changes
Overall looks good! A couple of tiny stylistic requests.

2021-01-06 20:16 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/db/OfferingRepository.java
> +public interface OfferingRepository extends JpaRepository<Offering, String> {
```suggestion
public interface OfferingRepository extends JpaRepository<Offering, String> {
    /* Intentionally left blank */
```

2021-01-06 20:16 UTC, kahowell commented on src/main/resources/liquibase/202012181510-add-offering-table.xml
> +</databaseChangeLog>
Nitpick: can has newline?

2021-01-07 14:10 UTC, jdhrh commented on src/main/java/org/candlepin/subscriptions/db/OfferingRepository.java
> +public interface OfferingRepository extends JpaRepository<Offering, String> {
Done!

2021-01-07 14:10 UTC, jdhrh commented on src/main/resources/liquibase/202012181510-add-offering-table.xml
> +</databaseChangeLog>
Done!

2021-01-07 18:59 UTC, lindseyburnett requested changes
We should add foreign keys for `sku_child_sku.sku`, `sku_child_sku.child_sku` and `sku_oid` tables back to `offering.sku`.

2021-01-07 21:30 UTC, lindseyburnett approved these changes

2021-01-07 21:38 UTC, kahowell approved these changes

2021-01-07 23:15 UTC, merged