SWATCH-1538: Add Origin header to conduit cron command
RedHatInsights/rhsm-subscriptions pull request #2341
Opened 2023-07-20 16:11 UTC by kahowell

Jira issue: [SWATCH-1538](https://issues.redhat.com/browse/SWATCH-1538)

Description
===========

We're hitting 403s due to anti-csrf code. Similar to #2059. Probably happening now because of JMX removal.

Testing
=======

1. Deploy:

```shell
./gradlew swatch-system-conduit:bootRun
```

2. Simulate the command used by the job:

```shell
export SWATCH_SELF_PSK=placeholder
/usr/bin/curl --fail -H "x-rh-swatch-psk: ${SWATCH_SELF_PSK}" -X POST "http://localhost:8000/api/rhsm-subscriptions/v1/internal/rpc/syncAllOrgs"
```

(see failure w/ 403)

3. Try the updated command:

```shell
export SWATCH_SELF_PSK=placeholder
/usr/bin/curl --fail -H "Origin: https://console.redhat.com" -H "x-rh-swatch-psk: ${SWATCH_SELF_PSK}" -X POST "http://localhost:8000/api/rhsm-subscriptions/v1/internal/rpc/syncAllOrgs"
```

(see success)

2023-07-20 16:54 UTC, mstead commented
/retest

2023-07-20 19:14 UTC, kahowell commented
/retest

2023-07-21 11:29 UTC, ntkathole commented
/retest

2023-07-21 12:24 UTC, mstead requested changes
I remember asking you about the origin header path when I hit this issue and I believe we talked about setting it to the {target_service}.[redhat.com](http://redhat.com/) as per PR #2059 

What ever you decide is best, we should follow suit with others as well to be consistent.

2023-07-21 13:20 UTC, kahowell commented
@mstead done, please take another look

2023-07-21 13:44 UTC, mstead approved these changes

2023-07-21 13:44 UTC, merged