SWATCH-1237: Use swatch-product-configuration in subscription syncing
RedHatInsights/rhsm-subscriptions pull request #2413
Opened 2023-08-17 20:04 UTC by kahowell

Jira issue: [SWATCH-1237](https://issues.redhat.com/browse/SWATCH-1237)

Description
===========

Subscription syncing used tag profile for the following things:

* Log a warning if a PAYG sub is missing details
* Log a warning if attempting to terminate a PAYG sub more than an hour out
* Lookup the product names used for a PAYG sub lookup
* Provide a lookup for productIds/tags for a SKU.
* Provide a lookup for metrics for a productId/tag.

Testing
=======

1. Deploy the service:

```shell
DEV_MODE=true \
  DEVTEST_EVENT_EDITING_ENABLED=true \
  SUBSCRIPTION_USE_STUB=true \
  PRODUCT_USE_STUB=true \
  ./gradlew :bootRun
```

2. Sync subscriptions:

```shell
http PUT :8000/api/rhsm-subscriptions/v1/internal/subscriptions/sync/org/123 \
  x-rh-swatch-psk:placeholder \
  Origin:console.redhat.com
```

3. Terminate a subscription:

```shell
http POST :8000/api/rhsm-subscriptions/v1/internal/subscriptions/terminate/235251 \
  timestamp==2030-01-01T00:00Z \
  x-rh-swatch-psk:placeholder \
  Origin:console.redhat.com
```

4. Lookup aws usage context:

```shell
http :8000/api/rhsm-subscriptions/v1/internal/subscriptions/awsUsageContext \
  orgId==123 \
  productId==rosa \
  date==2023-01-01T00:00Z \
  awsAccountId==foo \
  x-rh-swatch-psk:placeholder \
  Origin:console.redhat.com
```

See in the logs a line like:
> No subscription found for account null with criteria DbReportCriteria(accountNumber=null, orgId=123, productTag=null, productNames=[OpenShift Dedicated], productId=null, serviceLevel=EMPTY, usage=_ANY, billingProvider=AWS, billingAccountId=foo, payg=true, beginning=2022-12-31T23:00Z, ending=2023-01-01T00:00Z, metricId=null, hypervisorReportCategory=null)

(Verify that `OpenShift Dedicated` is in `productNames`)

5. Lookup tags for a SKU:

```shell
http :8000/api/rhsm-subscriptions/v1/internal/offerings/MW01485/product_tags \
  x-rh-swatch-psk:placeholder \
  Origin:console.redhat.com
```

(See `OpenShift-metrics` in the response).

6. Lookup metrics for a tag:

```shell
http :8000/api/rhsm-subscriptions/v1/internal/tags/rosa/metrics \
  x-rh-swatch-psk:placeholder \
  Origin:console.redhat.com
```

(Verify `Instance-hours` and `Cores` in the response).

Verification
------------

* Verify warning log when PAYG sub is missing details, message like:
> PAYG eligible subscription with subscriptionId:235251 has no billing provider.

* Verify warning log when attempting to terminate a PAYG sub more than an hour out, message like:
> Subscription 235251 terminated at 2023-08-17T19:50:06.974839779Z with out of range termination date 2030-01-01T00:00Z

Verify api calls succeed w/ non-empty results for lookups.

2023-08-21 11:13 UTC, ntkathole commented
/retest

2023-08-21 11:37 UTC, ntkathole commented
/retest

2023-08-21 12:51 UTC, ntkathole approved these changes
Looks good!

Subscription related internal rest calls are working fine, will need https://github.com/RedHatInsights/rhsm-subscriptions/pull/2406 to verify actual numbers, will do further testing in stage or once that pr merged.

2023-08-23 10:08 UTC, lindseyburnett commented on src/main/java/org/candlepin/subscriptions/capacity/admin/TagMetricMapper.java
> +  TagMetric fromConfigurationMetric(Metric metric);
Did this get used anywhere?

2023-08-23 12:01 UTC, kartikshahc requested changes

2023-08-23 12:01 UTC, kartikshahc commented on src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
> +  public List<Metric> getMetricsForTag(String tag) {
Feels like helper methods that would fit in Variant class?

2023-08-24 15:34 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
> +        Variant.findByTag(productId).stream()
Will add to Variant as `getProductNamesForTag`

2023-08-24 15:35 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/capacity/admin/TagMetricMapper.java
> +  List<TagMetric> mapTagMetrics(List<Metric> metricsForTag);
:thinking: yeah, will add another commit with changes for this.

2023-08-24 15:41 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
> +      if (subscriptionDefinition.isPresent() && subscriptionDefinition.get().isPaygEnabled()) {
Nah, it's fine as-is, there will be many cases where there is a product name on the offering but there's no matching configuration.

2023-08-24 16:02 UTC, kahowell commented
@kartikshahc please take another look when you get a chance.

2023-08-24 16:47 UTC, lindseyburnett approved these changes

2023-08-24 19:00 UTC, kartikshahc approved these changes
LGTM

2023-08-24 19:06 UTC, merged