Remove all non-BOM entries from dependency management
RedHatInsights/rhsm-subscriptions pull request #2426
Opened 2023-08-22 20:39 UTC by awood

Having non-BOM entries in dependency management results in transitive dependency exclusions not working properly.  We achieve the intended effect of dependency management (uniform versions of a library across all sub-projects) with the dependencies.gradle file anyway.

Attn @kahowell

2023-08-22 23:18 UTC, lindseyburnett commented
related: https://github.com/RedHatInsights/rhsm-subscriptions/pull/2423/files#diff-81ca6ede6d5ce5bc9718e90eed7b8887c0b4ae7980ca0a8789d96075db246461R10

2023-08-23 15:33 UTC, kahowell requested changes

2023-08-23 15:33 UTC, kahowell commented on buildSrc/src/main/groovy/swatch.spring-boot-dependencies-conventions.gradle
>          mavenBom libraries["spring-boot-dependencies"]
I'd be interested to go ahead and try moving this dep to the `dependencies` section, using `enforcedPlatform` and dropping the spring dependency management plugin; if it all works out, let's just go ahead and do that here.

2023-08-25 18:48 UTC, kahowell requested changes
- [ ] `platform` was intentional for the libraries (just revert d4f0801) - because we don't want to force the spring boot services to use quarkus provided versions.
- [ ] We can remove `io.spring.gradle:dependency-management-plugin` from dependencies.gradle now.

2023-08-30 13:42 UTC, awood commented
@kahowell Thanks for the review.  The issues you caught should be fixed now.  Good to know about the "platform was intentional for the libraries" bit.  I added a commit with comments explaining that.

2023-08-30 14:05 UTC, kahowell approved these changes

2023-08-30 14:05 UTC, kahowell commented
/retest

2023-08-30 17:36 UTC, awood commented
/retest

2023-08-30 19:23 UTC, merged