SWATCH-1630: Make the instance identifier configurable
RedHatInsights/rhsm-subscriptions pull request #2484
Opened 2023-09-04 09:54 UTC by Sgitario

Jira issue: [SWATCH-1630](https://issues.redhat.com/browse/SWATCH-1630)

## Description
 I want the subscription watch to allow the instance ID to be configurable so that I can change it depending on the product tag and the metric.

## Testing
1.- podman-compose up
2.- createdb -h localhost -U postgres -O rhsm-subscriptions swatch-1630
3.- DATABASE_DATABASE=swatch-1630 ./gradlew :bootRun
4.- Once the migration is finished, stop all the application that started in step 3.
5.- Mock the prometheus server at localhost:

Create the stub directory:
`mkdir stub`

Add a stub file to return some data: `stub/__files/swatch-1630.json`

```
cat > stub/__files/swatch-1630.json <<EOF
{
    "status" : "success",
    "data" : {
      "resultType" : "matrix",
      "result" : [
        {
          "metric" : {
            "_id" : "cluster id",
            "support" : "sla",
            "usage" : "usage",
            "product" : "product",
            "billing_marketplace" : "billing_marketplace",
            "billing_marketplace_account" : "billing_marketplace_account",
            "ebs_account" : "account"
          },
          "values": [[ $(date +%s), "1" ]]
        }
      ]
    }
}
EOF
```

Add a stub file to return no data: `stub/__files/empty.json`

```
cat > stub/__files/empty.json <<EOF
{
    "status" : "success",
    "data" : {
      "resultType" : "matrix",
      "result" : []
    }
}
EOF
```

Run wiremock:
`podman run -it --rm -p 8101:8080 --name wiremock -v $PWD/stub:/home/wiremock wiremock/wiremock:2.32.0 --verbose`

Configure stubbing for prometheus:

- this is to return some data when asking for instance-hours:
`curl -X POST --data '{ "priority": 1, "request": { "urlPath": "/api/v1/query_range", "method": "GET", "queryParameters": {"query": {"contains":"instance_hours"}}}, "response": { "status": 200, "bodyFileName": "swatch-1630.json", "headers":{"Content-Type":"application/json"} }}' http://localhost:8101/__admin/mappings/new`

- this is to return no data otherwise:
`curl -X POST --data '{ "priority": 5, "request": { "urlPath": "/api/v1/query_range", "method": "GET" }, "response": { "status": 200, "bodyFileName": "empty.json", "headers":{"Content-Type":"application/json"} }}' http://localhost:8101/__admin/mappings/new`

6.- Start the swatch metrics app: `DATABASE_DATABASE=swatch-1630 PROM_URL="http://localhost:8101/api/v1/" SUBSCRIPTION_USE_STUB=true USER_USE_STUB=true RHSM_RBAC_USE_STUB=true SUBSCRIPTION_SYNC_ENABLED=true ENABLE_SYNCHRONOUS_OPERATIONS=true SPRING_PROFILES_ACTIVE=openshift-metering-worker,kafka-queue ./gradlew :bootRun`

7.- Trigger the metrics from prometheus:
```
http POST :8000/api/rhsm-subscriptions/v1/internal/metering/rosa?orgId=16790890 \
Origin:console.redhat.com \
x-rh-swatch-synchronous-request:true \
x-rh-swatch-psk:placeholder \
x-rh-identity:$(echo -n '{"identity":{"account_number":"","type":"User","user":{"is_org_admin":true},"internal":{"org_id":"16790890"}}}' | base64 -w 0)
```

8.- Wait some time, so the service consumes all the events from the topic, and then query the `events` table:

Connect to the database:
`psql -h localhost -U rhsm-subscriptions swatch-1630`

Create an existing event for orgId=16790890

`SELECT * FROM EVENTS;`

And you should see only one event. And the "instance_id" column should be "cluster id". This column is populated from the field "_id" (see stub swatch-1630.json) and can be changed in 'subscription_configs/OpenShift/rosa.yaml', see the "queryParams.instanceKey" value (as part of this test, we used 'rosa' and the 'instance-hours' metrics)

2023-09-04 10:39 UTC, ntkathole commented
/retest

2023-09-04 11:04 UTC, ntkathole commented
/retest

2023-09-04 12:28 UTC, ntkathole commented
@Sgitario Test is failing due to error in metrics pod while performing metering operation `POST - api/rhsm-subscriptions/v1/internal/metering/OpenShift-metrics?orgId=3340851&endDate=2023-09-04T14:00:00Z&rangeInMinutes=240`

```
2023-09-04 12:27:25,710 [thread=metering-task-processor-0-C-1] [INFO ] [org.candlepin.subscriptions.task.queue.kafka.KafkaTaskProcessor] - Message received from kafka (key=3340851): JsonTaskMessage(groupId=platform.rhsm-subscriptions.metering-tasks, type=METRICS_COLLECTION, args={metric=[Cores], productTag=[OpenShift-metrics], start=[2023-09-04T10:00Z], end=[2023-09-04T14:00Z], orgId=[3340851]})
2023-09-04 12:27:25,710 [thread=metering-task-processor-0-C-1] [ERROR] [org.candlepin.subscriptions.task.queue.kafka.KafkaTaskProcessor] - Failed to execute task: JsonTaskMessage(groupId=platform.rhsm-subscriptions.metering-tasks, type=METRICS_COLLECTION, args={metric=[Cores], productTag=[OpenShift-metrics], start=[2023-09-04T10:00Z], end=[2023-09-04T14:00Z], orgId=[3340851]})
org.candlepin.subscriptions.task.TaskExecutionException: Error executing task: TaskDescriptor[groupId: platform.rhsm-subscriptions.metering-tasks, taskType: METRICS_COLLECTION, args: [start: [2023-09-04T10:00Z], end: [2023-09-04T14:00Z], metric: [Cores], orgId: [3340851], productTag: [OpenShift-metrics]]]
	at org.candlepin.subscriptions.task.TaskWorker.executeTask(TaskWorker.java:47)
	at org.candlepin.subscriptions.task.queue.kafka.KafkaTaskProcessor.receive(KafkaTaskProcessor.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119)
	at org.springframework.kafka.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:56)
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:375)
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:92)
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:53)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2873)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:2854)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.lambda$doInvokeRecordListener$57(KafkaMessageListenerContainer.java:2772)
	at io.micrometer.observation.Observation.lambda$observe$4(Observation.java:544)
	at io.micrometer.observation.Observation.observeWithContext(Observation.java:603)
	at io.micrometer.observation.Observation.observe(Observation.java:544)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:2770)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:2622)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:2508)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:2150)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeIfHaveRecords(KafkaMessageListenerContainer.java:1505)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1469)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1344)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Could not build task. Missing task argument: instanceKey
	at org.candlepin.subscriptions.metering.service.prometheus.task.PrometheusMeteringTaskFactory.validateString(PrometheusMeteringTaskFactory.java:65)
	at org.candlepin.subscriptions.metering.service.prometheus.task.PrometheusMeteringTaskFactory.build(PrometheusMeteringTaskFactory.java:53)
	at org.candlepin.subscriptions.task.TaskWorker.executeTask(TaskWorker.java:43)
	... 26 common frames omitted
```

2023-09-04 13:28 UTC, Sgitario commented
> @Sgitario Test is failing due to error in metrics pod while performing metering operation `POST - api/rhsm-subscriptions/v1/internal/metering/OpenShift-metrics?orgId=3340851&endDate=2023-09-04T14:00:00Z&rangeInMinutes=240`
> 
> ```
> 2023-09-04 12:27:25,710 [thread=metering-task-processor-0-C-1] [INFO ] [org.candlepin.subscriptions.task.queue.kafka.KafkaTaskProcessor] - Message received from kafka (key=3340851): JsonTaskMessage(groupId=platform.rhsm-subscriptions.metering-tasks, type=METRICS_COLLECTION, args={metric=[Cores], productTag=[OpenShift-metrics], start=[2023-09-04T10:00Z], end=[2023-09-04T14:00Z], orgId=[3340851]})


I don't see any relation between the error you shared and the test failing: https://ci.ext.devshift.net/job/RedHatInsights-rhsm-subscriptions-pr-check/3987/testReport/junit/tests.opt_in/test_opt_in_prometheus/test_verify_opt_in_prometheus_rhods_/

which is for `rhods` instead of `OpenShift-metrics`.

And as you said, this actual test failure is caused because you're still using the tag_profile.yaml file (which will be fully dropped) instead of the new product configuration. 

Note that I did try to reproduce the issue and it worked for me.

2023-09-05 04:56 UTC, ntkathole commented
/retest

2023-09-05 05:05 UTC, ntkathole commented
/retest

2023-09-05 15:37 UTC, kahowell requested changes
Overall, makes sense and works well, but I'd rather minimize the scope of changes. Instead of changing the signature for `PrometheusMeteringController.collectMetrics`, we should perform the lookup in that method, something like:

```java
var instanceKey = getPrometheusInstanceKeyFromMetric(tag, tagMetric.get());
```

This better encapsulates the configurable instance key so that it doesn't need to flow through our task management, etc.

(we should move the related constant and lookup method to `PrometheusMeteringController`).

2023-09-06 05:12 UTC, Sgitario commented
> Overall, makes sense and works well, but I'd rather minimize the scope of changes. Instead of changing the signature for `PrometheusMeteringController.collectMetrics`, we should perform the lookup in that method, something like:
> 
> ```java
> var instanceKey = getPrometheusInstanceKeyFromMetric(tag, tagMetric.get());
> ```
> 
> This better encapsulates the configurable instance key so that it doesn't need to flow through our task management, etc.
> 
> (we should move the related constant and lookup method to `PrometheusMeteringController`).

+100 this makes more sense

2023-09-06 08:07 UTC, Sgitario commented
@kahowell PR updated!

2023-09-06 15:41 UTC, kahowell approved these changes

2023-09-06 17:31 UTC, merged