SWATCH-1629: Include addonSamples as a template for accountQueryTemplate
RedHatInsights/rhsm-subscriptions pull request #2485
Opened 2023-09-04 11:01 UTC by Sgitario

Jira issue: [SWATCH-1629](https://issues.redhat.com/browse/SWATCH-1629)

## Description
Currently, Rhods contains "addonSamples", but application.yaml does not have a template for it. Therefore, it reads everything by "default" using default query and filters it later in the code. 

Now, we have properly configured the "addonSamples" query profile that includes the resource_type and resource_name filters directly in the prometheus query. 

## Testing
I've verified these changes via:

### a. Using the new prometheus promql script:

1.- Run the script:
```
bin/metering-promql.py --product rhods --url https://grafana.app-sre.devshift.net
```

2.- It will generate the following output:

```
Accounts: https://grafana.app-sre.devshift.net/explore?orgId=1&left=%7B%22queries%22%3A+%5B%7B%22refId%22%3A+%22A%22%2C+%22editorMode%22%3A+%22code%22%2C+%22expr%22%3A+%22group%28min_over_time%28ocm_subscription_resource%7Bresource_type%3D%5C%22addon%5C%22%2C+resource_name%3D%27addon-open-data-hub%27%2C+external_organization+%21%3D+%27%27%2C+billing_model%3D%27marketplace%27%7D%5B1h%5D%29%29+by+%28external_organization%29%22%2C+%22legendFormat%22%3A+%22__auto%22%2C+%22range%22%3A+true%2C+%22instant%22%3A+true%2C+%22interval%22%3A+%223600%22%7D%5D%2C+%22range%22%3A+%7B%22from%22%3A+%22now-12h%22%2C+%22to%22%3A+%22now%22%7D%7D
  Cores: https://grafana.app-sre.devshift.net/explore?orgId=1&left=%7B%22queries%22%3A+%5B%7B%22refId%22%3A+%22A%22%2C+%22editorMode%22%3A+%22code%22%2C+%22expr%22%3A+%22cluster%3Ausage%3Aworkload%3Acapacity_virtual_cpu_hours+%2A+on%28_id%29+group_right+min_over_time%28ocm_subscription_resource%7Bresource_type%3D%5C%22addon%5C%22%2Cresource_name%3D%5C%22addon-open-data-hub%5C%22%2C+external_organization%3D~%5C%22.%2A%5C%22%2C+billing_model%3D%5C%22marketplace%5C%22%2C+support%3D~%5C%22Premium%7CStandard%7CSelf-Support%7CNone%5C%22%7D%5B1h%5D%29%22%2C+%22legendFormat%22%3A+%22__auto%22%2C+%22range%22%3A+true%2C+%22instant%22%3A+true%2C+%22interval%22%3A+%223600%22%7D%5D%2C+%22range%22%3A+%7B%22from%22%3A+%22now-12h%22%2C+%22to%22%3A+%22now%22%7D%7D
```

Checking the `Accounts` link, you can confirm that the query is now: `group(min_over_time(ocm_subscription_resource{resource_type="addon", resource_name='addon-open-data-hub', external_organization != '', billing_model='marketplace'}[1h])) by (external_organization)`

Before these changes, the filters were `group(min_over_time(ocm_subscription_resource{product='rhods', external_organization != '', billing_model='marketplace'}[1h])) by (external_organization)`.

### b. Using the service

1.- podman-compose up
2.- Mock the prometheus server at localhost:

Create the stub directory:
`mkdir stub`

Add a stub file to return no data: `stub/__files/empty.json`

```
cat > stub/__files/empty.json <<EOF
{
    "status" : "success",
    "data" : {
      "resultType" : "matrix",
      "result" : []
    }
}
EOF
```

Run wiremock:
`podman run -it --rm -p 8101:8080 --name wiremock -v $PWD/stub:/home/wiremock wiremock/wiremock:2.32.0 --verbose`

Configure stubbing for prometheus:

- this is to return no data otherwise:
`curl -X POST --data '{ "priority": 5, "request": { "urlPath": "/api/v1/query_range", "method": "GET" }, "response": { "status": 200, "bodyFileName": "empty.json", "headers":{"Content-Type":"application/json"} }}' http://localhost:8101/__admin/mappings/new`

3.- Start the swatch metrics app: `PROM_URL="http://localhost:8101/api/v1/" SUBSCRIPTION_USE_STUB=true USER_USE_STUB=true RHSM_RBAC_USE_STUB=true SUBSCRIPTION_SYNC_ENABLED=true ENABLE_SYNCHRONOUS_OPERATIONS=true SPRING_PROFILES_ACTIVE=openshift-metering-worker,kafka-queue ./gradlew :bootRun`

4.- Trigger the metrics from prometheus:
```
http POST :8000/api/rhsm-subscriptions/v1/internal/metering/rhods?orgId=16790890 \
Origin:console.redhat.com \
x-rh-swatch-synchronous-request:true \
x-rh-swatch-psk:placeholder \
x-rh-identity:$(echo -n '{"identity":{"account_number":"","type":"User","user":{"is_org_admin":true},"internal":{"org_id":"16790890"}}}' | base64 -w 0)
```

5.- Check the prometheus logs (you started the wiremock server using --verbose) and confirm you received:

```
10.0.2.100 - GET /api/v1/query_range?query=cluster%3Ausage%3Aworkload%3Acapacity_virtual_cpu_hours%20*%20on%28_id%29%20group_right%20min_over_time%28ocm_subscription_resource%7Bresource_type%3D%22addon%22%2Cresource_name%3D%22addon-open-data-hub%22%2C%20external_organization%3D%2216790890%22%2C%20billing_model%3D%22marketplace%22%2C%20support%3D~%22Premium%7CStandard%7CSelf-Support%7CNone%22%7D%5B1h%5D%29&start=1693821600&end=1693821600&step=3600&timeout=10000
```

Which now it contains the `resource_name=addon-open-data-hub` and `resource_type=addon`.

2023-09-06 18:29 UTC, kahowell commented
>  `podman run -it --rm -p 8101:8080 --name wiremock -v $PWD/stub:/home/wiremock wiremock/wiremock:2.32.0 --verbose`

Looks like you run without selinux enforcing?

PSA: https://stopdisablingselinux.com/

2023-09-06 19:07 UTC, lindseyburnett commented
# Test Step corrections/notes
* mkdir -p stub/__files
* wiremock volume mount needs **:z** at the end
* "api" profile also needed on application startup to make rest request

2023-09-06 19:14 UTC, lindseyburnett requested changes
The steps listed don't actually have the application exercising the new template you added.  The results you got are misleading.  The `openshift-metering-worker` profile actually uses the set of templates found in [application-openshift-metering-worker.yaml](https://github.com/RedHatInsights/rhsm-subscriptions/blob/f53e559df23efbc7ba6b5028b1db2f26e3f29570/src/main/resources/application-openshift-metering-worker.yaml#L11). Coincidentally, the templates are identical so you got false positive results.

You can verify that the template isn't being used by setting the `OPENSHIFT_ENABLED_ACCOUNT_PROMQL` environment variable during startup.  When you make the http request, you can see that URL wiremock is receiving didn't change to "bananas".

```
OPENSHIFT_ENABLED_ACCOUNT_PROMQL="bananas" PROM_URL="http://localhost:8101/api/v1/" SUBSCRIPTION_USE_STUB=true USER_USE_STUB=true RHSM_RBAC_USE_STUB=true SUBSCRIPTION_SYNC_ENABLED=true ENABLE_SYNCHRONOUS_OPERATIONS=true SPRING_PROFILES_ACTIVE=openshift-metering-worker,api,kafka-queue ./gradlew :bootRun
```

The hourly metering job is what exercises the query template defined in **application.yaml**.  You can do this by starting the application with the following profiles.
`SPRING_PROFILES_ACTIVE=metering-job,kafka-queue` 

You can also set `OPENSHIFT_ENABLED_ACCOUNT_PROMQL` as noted above to see the difference.


 # TODO
- [ ] Update [QueryBuilder](https://github.com/RedHatInsights/rhsm-subscriptions/blob/70124090d78e2595b1420f0ee70797f9f5deb542/src/main/java/org/candlepin/subscriptions/metering/service/prometheus/promql/QueryBuilder.java#L66) to select which query template to use based on swatch-product-configuration.

`var templateKey = queryDescriptor.getMetric().getPrometheus().getQueryKey()` should do the trick.

- [ ] Ensure all the product configurations that have a `prometheus` block also have "queryKey" set.  Alternatively, you could set the string to "default" in the `com.redhat.swatch.configuration.registry.PrometheusMetric` class

2023-09-07 07:33 UTC, Sgitario commented
> # Test Step corrections/notes
> * wiremock volume mount needs **:z** at the end
> * "api" profile also needed on application startup to make rest request

This is odd since I didn't need these two steps.

2023-09-07 07:46 UTC, Sgitario commented
> > `podman run -it --rm -p 8101:8080 --name wiremock -v $PWD/stub:/home/wiremock wiremock/wiremock:2.32.0 --verbose`
> 
> Looks like you run without selinux enforcing?
> 
> PSA: https://stopdisablingselinux.com/
> 
> Edit: If no, I'm curious how this works otherwise without `-v $PWD/stub:/home/wiremock:z` 😄

I had to disable for some reason I don't remember now :)

2023-09-07 08:31 UTC, Sgitario commented
PR updated with the requested changes and description updated as well.
Thanks @lindseyburnett !

2023-09-07 21:29 UTC, lindseyburnett approved these changes

2023-09-12 13:50 UTC, TrayvonMcKnight approved these changes
https://drive.google.com/file/d/1AnNnpxiZPJauOj96v1EPuDjbwd9swQ2z/view?usp=drive_link

2023-09-12 14:15 UTC, merged