SWATCH-1651: Populate uri label in Spring Boot 3 request metrics
RedHatInsights/rhsm-subscriptions pull request #2489
Opened 2023-09-05 20:44 UTC by kahowell

Jira issue: [SWATCH-1651](https://issues.redhat.com/browse/SWATCH-1651)

Description
===========

Spring Boot 3 introduced drastic changes to how the metrics are constructed.

Two classes are now necessary to carry resteasy URIs into metrics:

1. ResteasyUriExtractionFilter - to extract the URI from resteasy
2. ResteasyRequestObservationConvention - to set the URI as the `uri` attribute.

ResteasyUriExtractionFilter was renamed from MicrometerUriHackFilter to better reflect its purpose.

Testing
=======

Setup
-----

1. Deploy the service:

```shell
DEV_MODE=true ./gradlew :bootRun
```

2. Ensure opted in:

```shell
http PUT :8000/api/rhsm-subscriptions/v1/opt-in \
  x-rh-identity:$(echo '{"identity":{"type":"User","internal":{"org_id":"org123"}}}' | base64 -w0)
```

Verification
------------

Hit an http API:

```shell
http ':8000/api/rhsm-subscriptions/v1/capacity/products/RHEL for x86' \
  granularity==Daily \
  beginning==2023-07-21T17:32:28Z \
  ending==2023-07-22T17:32:28Z \
  x-rh-identity:$(echo '{"identity":{"type":"User","internal":{"org_id":"org123"}}}' | base64 -w0)
```

Check metrics endpoint and see that the URI is populated:

```shell
http :9000/metrics | grep http_server_requests_seconds_count
```

2023-09-06 11:15 UTC, Sgitario requested changes
I wrote a test to verify this change. Are you ok if I submit a commit with the test?
Also, I've found that when the call fails, the URI is still "UNKNOWN": 

```
http_server_requests_seconds_count{error="none",exception="none",method="PUT",outcome="SUCCESS",status="200",uri="/api/rhsm-subscriptions/v1/opt-in",} 1.0
http_server_requests_seconds_count{error="none",exception="none",method="PUT",outcome="CLIENT_ERROR",status="401",uri="UNKNOWN",} 1.0
```

Note that when the call works fine, the URI is populated, but now when there is a failure. 

I'm seeing how to address it.

2023-09-06 15:39 UTC, kahowell commented
> Let me know what you think about and I'm ok to update your branch to include these commits into this pull request.

@Sgitario I'm happy with those changes, feel free to commit them directly to this branch.

2023-09-06 17:30 UTC, Sgitario commented
> > Let me know what you think about and I'm ok to update your branch to include these commits into this pull request.
> 
> @Sgitario I'm happy with those changes, feel free to commit them directly to this branch.

Updated!

2023-09-07 07:52 UTC, Sgitario commented
PR updated to fix the sonar issue.

2023-09-07 07:52 UTC, Sgitario approved these changes

2023-09-08 13:54 UTC, merged