SWATCH-382: Aggregate code coverage from sub projects
RedHatInsights/rhsm-subscriptions pull request #2533
Opened 2023-09-19 10:19 UTC by Sgitario

Jira issue: [SWATCH-382](https://issues.redhat.com/browse/SWATCH-382)

# Description

The pull request includes the following changes:
- Change scope of quarkus-jacoco to test
- Replace the deprecated `sonar.login` to `sonar.token`

Sonar was alerting that `sonar.login` is deprecated and is going to be removed.

- fix code coverage for subprojects

The main issue was that by having: `project.tasks["sonarqube"].dependsOn "jacocoTestReport"` only in the parent build.gradle file, the sub projects were generating the jacoco report. 

I fixed that by appending the tasks directly to the gradle command. 
The problem with the Quarkus projects was caused by a wrong location of the jacoco report and missing the Jacoco plugin.

2023-09-19 14:39 UTC, Sgitario commented
After these changes, the test coverage for subprojects are now correctly generated:

![Captura de pantalla de 2023-09-19 16-38-47](https://github.com/RedHatInsights/rhsm-subscriptions/assets/6310047/6ce18044-71fe-47f4-b82a-5f4871769048)

2023-09-19 17:37 UTC, Sgitario commented
/retest

2023-09-20 13:53 UTC, Sgitario commented
/retest

2023-09-21 15:56 UTC, kahowell requested changes

2023-09-21 17:33 UTC, Sgitario commented on swatch-producer-aws/build.gradle
> +}
Good idea! Will update the pull request shortly.

2023-09-21 17:39 UTC, Sgitario commented on swatch-contracts/build.gradle
> +}
I think I know the reason. `swatch-producer-aws` does not have any `QuarkusTest`, but only regular JUnit tests.

2023-09-21 19:49 UTC, Sgitario commented
@kahowell I've just updated the pull request by moving the common config of jacoco into the swatch.java-conventions file.

Moreover, I also created a `swatch.quarkus-conventions` gradle file, so we can use it for common configuration for Quarkus. At the moment, I only included a few things plus the necessary configuration for jacoco to work with `@QuarkusTest` and regular JUnit tests, and also the sonar configuration. 

Note that when using Quarkus Jacoco must be at least one test annotated with `@QuarkusTest` to work and combine all the regular JUnit tests. That's why I adapted the BillableUsageProcessorTest test to use `@QuarkusTest`. 

Now, all the Quarkus apps behave the same and because we're now incorporating the Quarkus tests and regular JUnit tests, the code coverage looks much better:

![Captura de pantalla de 2023-09-21 21-45-21](https://github.com/RedHatInsights/rhsm-subscriptions/assets/6310047/3f56cf36-1ef6-4d0f-8f45-6fca0720e172)

2023-09-21 19:51 UTC, Sgitario commented on swatch-contracts/build.gradle
> +}
PR updated. Now, these two Quarkus applications produce the jacoco report on the same path. 
We still need: 

```
sonarqube {
    properties {
        property 'sonar.coverage.jacoco.xmlReportPaths', "${projectDir}/build/jacoco-report/jacoco.xml"
    }
}
```

But it's configured in the common `swatch.quarkus-conventions` file.

2023-09-21 19:51 UTC, Sgitario commented on swatch-producer-aws/build.gradle
> +}
PR updated!

2023-09-22 08:26 UTC, Aurobinda55 commented
/retest

2023-09-22 13:44 UTC, kahowell approved these changes

2023-09-22 13:58 UTC, merged