configure docker and docker in Jenkins
RedHatInsights/rhsm-subscriptions pull request #2544
Opened 2023-09-21 06:03 UTC by Sgitario

tbd

2023-09-21 13:24 UTC, lindseyburnett commented
TODO:

- [ ] see if we can find a RedHat source for kubedock

2023-09-21 22:18 UTC, kahowell requested changes

2023-09-22 08:17 UTC, Sgitario commented on swatch-core-test/src/main/java/org/candlepin/containers/SwatchPostgreSQLContainer.java
> +package org.candlepin.containers;
done

2023-09-22 09:29 UTC, Sgitario commented on Jenkinsfile
> +      image: docker.io/joyrex2001/kubedock:0.13.0
I've just created the MR to include this image: https://gitlab.cee.redhat.com/jcarvaja/app-interface/-/merge_requests/2

I also had to create the GH repository: https://github.com/RedHatInsights/kubedock

I verified this image with this pull request and everything looks good. 
Once the MR is merged and the image pushed, I will update this pull request.
For now, I'm changing this pull request to draft.

2023-09-22 13:45 UTC, kahowell commented on swatch-core-test/src/main/java/org/candlepin/containers/SwatchPostgreSQLContainer.java
> +  private static final String POSTGRESQL_IMAGE_DEFAULT = "docker.io/library/postgres:13";
Thanks!

2023-09-22 13:47 UTC, kahowell approved these changes
Thanks for addressing my feedback!

I'm okay to merge with your image as a stop-gap if you want to update it in a follow-up PR to one built by the new repo.

2023-09-22 20:12 UTC, kahowell commented on Jenkinsfile
> +      image: docker.io/joyrex2001/kubedock:0.13.0
quay image was built: quay.io/cloudservices/kubedock:123efe0. (Automation doesn't provide a `latest` tag).

2023-09-26 07:21 UTC, Sgitario commented
> @Sgitario Jenkins console logs shows 501 on docker api. Is it an issue ?
> 
> ```
> 
> 2023-09-24 00:14:38,475 [thread=Thread-24] [ERROR] [org.apache.zookeeper.server.NIOServerCnxnFactory] - Thread Thread[Thread-24,5,testcontainers] died
> com.github.dockerjava.api.exception.DockerException: Status 501: 
> 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:249)
> 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:124)
> 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.PruneCmdExec.execute(PruneCmdExec.java:33)
> 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.PruneCmdExec.execute(PruneCmdExec.java:13)
> 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
> 	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
> 	at org.testcontainers.shaded.com.github.dockerjava.core.command.PruneCmdImpl.exec(PruneCmdImpl.java:100)
> 	at org.testcontainers.utility.JVMHookResourceReaper.prune(JVMHookResourceReaper.java:58)
> 	at org.testcontainers.utility.JVMHookResourceReaper.lambda$performCleanup$2(JVMHookResourceReaper.java:27)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
> 	at org.testcontainers.utility.JVMHookResourceReaper.performCleanup(JVMHookResourceReaper.java:27)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> ```

I see this is happening when in the shutdown hook by Spring:

``` 
2023-09-25 18:35:44,307 [thread=SpringApplicationShutdownHook] [INFO ] [org.candlepin.subscriptions.task.queue.kafka.KafkaApplicationListener] - Shutting down kafka consumers...
2023-09-25 18:35:44,405 [thread=Thread-136] [INFO ] [org.candlepin.subscriptions.task.queue.inmemory.ExecutorTaskProcessor] - Stopping in-memory task processor
2023-09-25 18:35:44,556 [thread=Thread-24] [ERROR] [org.apache.zookeeper.server.NIOServerCnxnFactory] - Thread Thread[Thread-24,5,testcontainers] died
com.github.dockerjava.api.exception.DockerException: Status 501: 
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:249)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:124)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.PruneCmdExec.execute(PruneCmdExec.java:33)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.PruneCmdExec.execute(PruneCmdExec.java:13)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.PruneCmdImpl.exec(PruneCmdImpl.java:100)
	at org.testcontainers.utility.JVMHookResourceReaper.prune(JVMHookResourceReaper.java:58)
	at org.testcontainers.utility.JVMHookResourceReaper.lambda$performCleanup$2(JVMHookResourceReaper.java:27)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testcontainers.utility.JVMHookResourceReaper.performCleanup(JVMHookResourceReaper.java:27)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-09-25 18:35:44,629 [thread=Thread-155] [INFO ] [org.candlepin.subscriptions.task.queue.inmemory.ExecutorTaskProcessor] - Stopping in-memory task processor
``` 

Since it's a 501, I assume it's caused because zookeeper is already terminated, so I don't think it's relevant.

2023-09-26 08:16 UTC, Sgitario commented
/retest

2023-09-26 09:04 UTC, Sgitario commented
/retest

2023-09-26 09:38 UTC, merged