Create scaffolding for swatch-producer-azure
RedHatInsights/rhsm-subscriptions pull request #2568
Opened 2023-09-26 21:27 UTC by kahowell

Jira issue: [SWATCH-1715](https://issues.redhat.com/browse/SWATCH-1715)

Description
===========

Create swatch-producer-azure with stubbed out behaviors.

Note I also refactored kafka seeking logic and the PSK into shared libraries.

Testing
=======

Setup
-----

Deploy the service:

```shell
./gradlew swatch-producer-azure:quarkusDev
```

Verification
------------

Try the following curl command to simulate some seemingly applicable usage

```shell
curl -X 'POST' \
  'http://localhost:8000/api/swatch-producer-azure/internal/azure/billable_usage' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "account_number": "account123",
  "org_id": "org123",
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "billing_provider": "azure",
  "billing_account_id": "string",
  "snapshot_date": "2022-03-10T12:15:50-04:00",
  "product_id": "rosa",
  "uom": "Cores",
  "value": 0,
  "billing_factor": 0,
  "vendor_product_code": "string"
}'
```

View the logs and see that a message is produced and then consumed for the billable usage.

2023-09-27 19:09 UTC, lindseyburnett requested changes

2023-09-27 19:09 UTC, lindseyburnett commented on bin/build-images.sh
> +    "swatch-producer-azure")
Corresponding "push and clean" entry needed around line 100

```
    "swatch-producer-azure")
      push_and_clean "quay.io/$quay_user/swatch-producer-azure:$tag"
      ;;
```

2023-09-27 19:25 UTC, lindseyburnett approved these changes

2023-09-28 05:25 UTC, Sgitario requested changes
Just a minor thing.

2023-09-28 05:25 UTC, Sgitario commented on bin/build-images.sh
> +  projects[3]="swatch-producer-azure"
```suggestion
  projects[4]="swatch-producer-azure"
```

2023-09-28 15:02 UTC, kahowell commented on bin/build-images.sh
> +  projects[3]="swatch-producer-azure"
Thanks for catching that. Fixed.

2023-09-28 15:05 UTC, kahowell commented
> Just a minor thing.
I would also add some @QuarkusTest test with some Azure wiremock instance to settle the basis. But we can add this in a separate pull request as well (I can help with that if you want).

@Sgitario, sure. Let's handle in [SWATCH-1726](https://issues.redhat.com/browse/SWATCH-1726). I'll make a note that you can help with the wiremock instance.

2023-09-29 13:57 UTC, merged