SWATCH-1917: Set cores/sockets to null when value is not present
RedHatInsights/rhsm-subscriptions pull request #2821
Opened 2023-11-27 12:12 UTC by kflahert

Jira issue: SWATCH-1917

## Description

In order to have consistency between instance_measurements and host_tally_buckets we need to set the cores/sockets to null when no value it present. Previously these were defaulted to 0.

## Testing

### Setup

1.Insert test data: 
```
INSERT INTO public.events VALUES ('942e5a9b-35b3-4caf-9d31-5544b1591377', '2023-10-31 03:00:00+00', '{"sla": "Premium", "role": "moa-hostedcontrolplane", "org_id": "org123", "event_id": "942e5a9b-35b3-4caf-9d31-5544b1591377", "timestamp": "2023-10-31T03:00:00Z", "event_type": "snapshot_rosa_cores", "expiration": "2023-10-31T04:00:00Z", "instance_id": "10c6e649-8985-4809-ace3-97a55a615fc3", "display_name": "10c6e649-8985-4809-ace3-97a55a615fc3", "event_source": "prometheus", "measurements": [{"uom": "Cores", "value": 4.0}], "service_type": "rosa Instance", "billing_provider": "aws", "metering_batch_id": "45136d97-6963-4adb-8c25-c2352e0ffe63", "billing_account_id": "463992265265"}', 'snapshot_rosa_cores', 'prometheus', '10c6e649-8985-4809-ace3-97a55a615fc3', 'org123', DEFAULT, '45136d97-6963-4adb-8c25-c2352e0ffe63', '2023-10-31 04:30:25.486382+00');
INSERT INTO public.events VALUES ('db5448c2-19cc-41d3-86e4-956dfc25d8fb', '2023-10-04 03:00:00+00', '{"sla": "Premium", "role": "moa-hostedcontrolplane", "org_id": "org123", "event_id": "db5448c2-19cc-41d3-86e4-956dfc25d8fb", "timestamp": "2023-10-04T03:00:00Z", "event_type": "snapshot_rosa_cores", "expiration": "2023-10-04T04:00:00Z", "instance_id": "39146518-51c2-41a1-881e-1fa007facbd0", "display_name": "39146518-51c2-41a1-881e-1fa007facbd0", "event_source": "prometheus", "measurements": [{"uom": "Sockets", "value": 10}], "service_type": "rosa Instance", "account_number": "6344158", "billing_provider": "aws", "metering_batch_id": "da2c3b9c-2ab8-4b6b-934b-536fc8614625", "billing_account_id": "463992265265"}', 'snapshot_rosa_cores', 'prometheus', '39146518-51c2-41a1-881e-1fa007facbd0', 'org123', DEFAULT, 'da2c3b9c-2ab8-4b6b-934b-536fc8614625', '2023-10-04 04:32:09.229067+00');
```

### Steps

1. Start app with: `DEV_MODE=true CONTRACT_USE_STUB=true SPRING_PROFILES_ACTIVE=worker,api,kafka-queue ./gradlew :bootRun`
1. Run tally:` http POST ":8000/api/rhsm-subscriptions/v1/internal/tally/hourly?org=org123&start=2023-10-01T08:00:00Z&end=2023-11-02T08:00:00Z" x-rh-swatch-psk:placeholder`

### Verification

1. Check host_tally_buckets table for a set of records with null sockets and another with null cores:
`select * from host_tally_buckets;`

2023-11-27 19:47 UTC, kflahert commented
/retest

2023-11-28 04:16 UTC, ntkathole commented
/retest

2023-11-30 17:55 UTC, lindseyburnett commented
/retest

2023-11-30 21:11 UTC, kahowell approved these changes

2023-11-30 21:21 UTC, kahowell requested changes
See inline comment.

2023-11-30 21:21 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/tally/collector/RHELProductUsageCollector.java
> +    Integer appliedSockets = normalizedFacts.getSockets();
I think we need to make a similar change to the DefaultProductUsageCollector.

2023-12-01 07:21 UTC, ssidhaye commented
/retest

2023-12-01 08:48 UTC, ssidhaye commented
/retest

2023-12-01 16:26 UTC, kahowell approved these changes

2023-12-04 05:46 UTC, ssidhaye commented
/retest

2023-12-06 11:33 UTC, ssidhaye commented
/retest

2023-12-08 19:18 UTC, lindseyburnett commented
/retest

2023-12-11 20:29 UTC, lindseyburnett commented
/retest

2023-12-14 21:45 UTC, lindseyburnett commented
/retest

2023-12-19 13:21 UTC, ssidhaye commented
/retest

2023-12-26 11:08 UTC, ssidhaye commented
/retest

2024-01-08 07:34 UTC, ntkathole commented
/retest

2024-01-11 11:07 UTC, ssidhaye commented
/retest

2024-01-15 09:30 UTC, ssidhaye commented
/retest

2024-01-16 13:10 UTC, ssidhaye approved these changes
After generating events via test code, and tallying I am able to see null / no value for sockets / core where they are not applicable.

```
host_id                               |   usage    | product_id |   sla   | as_hypervisor | cores | sockets | measurement_type | billing_provider | billing_account_id | version 
 3debcefc-cb0c-417c-9ba1-23119a4ca08a | Production | rosa       | Premium | f             |     4 |         |                  | _ANY             | 463992265265       |       0
 3debcefc-cb0c-417c-9ba1-23119a4ca08a | Production | rosa       | Premium | f             |     4 |         |                  | aws              | _ANY               |       0
 3debcefc-cb0c-417c-9ba1-23119a4ca08a | Production | rosa       | Premium | f             |     4 |         |                  | aws              | 463992265265       |       0
 6b0e37e6-2b08-4b84-848e-0837fe80cfa7 | _ANY       | rosa       | Premium | f             |       |      10 |                  | _ANY             | _ANY               |       0
 6b0e37e6-2b08-4b84-848e-0837fe80cfa7 | _ANY       | rosa       | Premium | f             |       |      10 |                  | _ANY             | 463992265265       |       0
 6b0e37e6-2b08-4b84-848e-0837fe80cfa7 | _ANY       | rosa       | Premium | f             |       |      10 |                  | aws              | _ANY               |       0
```

2024-01-19 12:50 UTC, ssidhaye commented
/retest

2024-01-19 16:39 UTC, kflahert commented
/retest

2024-01-23 14:10 UTC, san7ket commented
/retest

2024-01-25 09:05 UTC, ssidhaye commented
@kflahert I have added a fix for the failing test. But we are hitting an issue due to a [bug](https://issues.redhat.com/browse/SWATCH-2138)

2024-01-29 18:18 UTC, kahowell commented
/retest

2024-02-12 20:48 UTC, kahowell commented
@ssidhaye can you please update tests as necessary?

We're still getting failures in:

-  `tests.tally.test_tally_openshift.test_validate_tally_on_openshift_cores[2]`
-  `tests.tally.test_tally_with_sla_filters.test_validate_sla_filters_for_openshift_tally[Disaster Recovery-Premium-Cores/vCPU]`

2024-02-13 17:49 UTC, ssidhaye commented
/retest

2024-02-16 09:41 UTC, ssidhaye commented
/retest

2024-02-19 14:53 UTC, ssidhaye commented
/retest

2024-02-20 05:37 UTC, ssidhaye commented
/retest

2024-02-27 13:17 UTC, barnabycourt commented
/retest

2024-02-27 15:50 UTC, awood commented
/retest

2024-03-01 05:48 UTC, ssidhaye commented
/retest

2024-03-01 11:30 UTC, kflahert commented
/retest

2024-03-01 12:54 UTC, ssidhaye commented
/retest

2024-03-08 06:42 UTC, ssidhaye commented
/retest

2024-03-08 14:37 UTC, ssidhaye commented
/retest

2024-03-11 09:21 UTC, ssidhaye commented
/retest

2024-03-11 10:52 UTC, ssidhaye commented
/retest

2024-03-11 12:15 UTC, ssidhaye commented
/retest

2024-03-11 13:22 UTC, merged