Add instructions to deploy OTEL exporter and RabbitMQ locally
RedHatInsights/rhsm-subscriptions pull request #2899
Opened 2023-12-18 09:59 UTC by Sgitario

Related to Jira issue: [SWATCH-2038](https://issues.redhat.com/browse/SWATCH-2038)

## Description
These changes allow us to test the remote logging export locally.
For example, for swatch-contracts, we would need to:
1.- Start kafka, db, ... via:

```
podman-compose up -d
```
2.- Start otel exporter:

```
podman-compose -f config/otel/docker-compose.yml up -d
```

3.- Start rabbitmq:

```
podman-compose -f config/rabbitmq/docker-compose.yml up -d
```

4.- Build swatch contracts:

```
./gradlew clean swatch-contracts:assemble -x test
```

5.- Start the swatch contracts service:

```
java -DSWATCH_SELF_PSK=placeholder -DENABLE_SPLUNK_HEC=false -DSWATCH_TEST_APIS_ENABLED=true -DRBAC_ENABLED=false -DUMB_HOSTNAME=localhost -DUMB_PORT=5672 -DOTEL_ENDPOINT=http://localhost:4317 -DRBAC_ENDPOINT=localhost:8080 -jar swatch-contracts/build/quarkus-app/quarkus-run.jar 
```

## Testing
No QE is needed here.

2024-01-03 21:13 UTC, kahowell requested changes
Overall, awesome work, needs a few tweaks to work with selinux enabled.

2024-01-03 21:13 UTC, kahowell commented on config/splunk/docker-compose.yml
> +    image: splunk/splunk
Please be explicit with the registry:

```suggestion
    image: docker.io/splunk/splunk
```

2024-01-03 21:13 UTC, kahowell commented on config/splunk/docker-compose.yml
> +      - SPLUNK_HEC_TOKEN=29fe2838-cab6-4d17-a392-37b7b8f41f75
```suggestion
      - SPLUNK_HEC_TOKEN=29fe2838-cab6-4d17-a392-37b7b8f41f75
      # workaround rootless selinux issues, see https://github.com/splunk/splunk-ansible/issues/607
      security_opt:
        - label=disable
```

2024-01-08 05:43 UTC, Sgitario commented
@kahowell many thanks for your commits suggestions! 
I had to disable selinux security in my laptop for unrelated reasons and that's why I didn't spot these issues. 
Your changes should be now part of the PR.

2024-01-10 18:34 UTC, kahowell approved these changes

2024-01-10 19:47 UTC, merged