ENT-3542: Produce hourly tally for all configured accounts
RedHatInsights/rhsm-subscriptions pull request #299
Opened 2021-02-18 17:18 UTC by lindseyburnett

Produce hourly tally for all configured accounts

Add metric-lookup-range-duration configuration to be used when scheduling hourly snapshot job
Queue up an hourly tally for all configured accounts and expose operation via the TallyJmxBean
Also produce hourly snapshots during the CaptureSnapshotsJob

**Note: Refactoring to minimize some duplicate code in CaptureSnapshotsJob is getting kicked down the road because of timelines, that work is captured in a new card in the backlog ENT-3561**

2021-02-18 19:17 UTC, mstead approved these changes
I had looked at this one before. This version looks good to me as well and addresses the previous concerns I had.

Will let @kahowell have final say an merge this PR since he had feedback last time as well.

2021-02-19 00:10 UTC, kahowell requested changes

2021-02-19 00:10 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/tally/job/CaptureSnapshotsTaskManager.java
> +                OffsetDateTime startTime = endTime.minus(metricRange);
Two thoughts:
1. Let's define start/endtime outside of the for-loop
2. Let's normalize the time (I think truncating `now()` to the hour would probably do it)

2021-02-19 00:10 UTC, kahowell commented on schemas/tally_summary.yaml
> +          $ref: 'event.yaml#properties/usage'
Disregard, noted in #293.

2021-02-19 00:11 UTC, kahowell commented on schemas/tally_summary.yaml
> +          $ref: 'event.yaml#properties/sla'
Disregard, noted in #293.

2021-02-19 19:16 UTC, kahowell approved these changes

2021-02-19 19:29 UTC, merged