Run an init script in the container builds to set git email
RedHatInsights/rhsm-subscriptions pull request #3045
Opened 2024-02-08 20:58 UTC by awood

This is a result of the update of
com.netflix.nebula:nebula-release-plugin from 18.0.8 to 19.0.4.  For
some reason the new plugin demands that the user.name and user.email be
set in the git configuration.

2024-02-09 06:13 UTC, Sgitario requested changes
Why do we need to do this? Theoritically, the only needed changes was done in https://github.com/RedHatInsights/rhsm-subscriptions/pull/3021 and the build of the images was fixed.

2024-02-09 09:31 UTC, san7ket commented
/retest

2024-02-09 09:51 UTC, Sgitario commented
Update: QE just noticed that the deployment to stage was failing. I fixed that using this commit https://github.com/RedHatInsights/rhsm-subscriptions/commit/50a0a9868324a7736882a14dfeafee77933a7009. 
The solution is the same as in the linked pull request: https://github.com/RedHatInsights/rhsm-subscriptions/pull/3021.

Did you encounter this issue in somewhere else?

2024-02-09 15:36 UTC, awood commented
Yes, you can't build the images by hand from the Dockerfiles without this.  So the `bin/build-images.sh` script that can be used for building images to deploy into the ephemeral environments by developers was broken.

2024-02-12 06:03 UTC, Sgitario commented
> Yes, you can't build the images by hand from the Dockerfiles without this. So the `bin/build-images.sh` script that can be used for building images to deploy into the ephemeral environments by developers was broken.

Developers should have configured their user name and email locally. Actually, I didn't hit the issue when I tried to run this script. The problem with these changes is that we will always use the user of the last commit.

2024-02-12 16:38 UTC, awood commented
> Developers should have configured their user name and email locally. Actually, I didn't hit the issue when I tried to run this script. The problem with these changes is that we will always use the user of the last commit.

Yes, I agree.  I do actually have the name and email configured locally.  The problem is that I had that information configured in `~/.gitconfig`.  Consequently, those values were not in `.git/config` in the project.  I made the change to add the value to the local config, but this is a bit of a landmine.  I can see it blowing up in someone else's face in the future (because after all, why bother setting your name and email for each repo when you can just do it globally?).

Any thoughts on the best way to warn people about this?



when the build is performed *in the container*, those settings are not present.  You're right that the name is just going to be whatever is on HEAD.  What do you think about just statically setting the user name to "Subscription Watch" and the email to the team list.  I would like to get this merged as currently the `bin/build_images.sh` script is broken and I use that script when deploying to the EEs.

Would you mind testing and seeing if 

```
podman build . -t scratch
```

works for you?

2024-02-12 16:43 UTC, Sgitario commented
> > Developers should have configured their user name and email locally. Actually, I didn't hit the issue when I tried to run this script. The problem with these changes is that we will always use the user of the last commit.
> 
> Yes, I agree. I do actually have the name and email configured locally. The problem is that I had that information configured in `~/.gitconfig`. Consequently, those values were not in `.git/config` in the project. I made the change to add the value to the local config, but this is a bit of a landmine. I can see it blowing up in someone else's face in the future (because after all, why bother setting your name and email for each repo when you can just do it globally?).
> 
> Any thoughts on the best way to warn people about this?

Indeed, this is a very annoying change by the Nebula release plugin (why are we using this plugin? :S)

To be honest, since we're not really using the GIT user for anything, I would be ok to add the following:

```
# Initialize the GIT config which is required by the Gradle Nebula plugin to build the images
git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
```

as part of the build-images.sh script as done also in https://github.com/RedHatInsights/rhsm-subscriptions/commit/50a0a9868324a7736882a14dfeafee77933a7009.

This is mostly to avoid having to modify all the Dockerfile (and hence increasing the complexity of those) to deal with a suspicious change of the Nebula plugin.

2024-02-12 19:36 UTC, awood commented
> To be honest, since we're not really using the GIT user for anything, I would be ok to add the following:
> 
> ```
> # Initialize the GIT config which is required by the Gradle Nebula plugin to build the images
> git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
> git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
> ```
> 
> as part of the build-images.sh script as done also in [50a0a98](https://github.com/RedHatInsights/rhsm-subscriptions/commit/50a0a9868324a7736882a14dfeafee77933a7009).

I thought about that, but wouldn't that end up affecting the person's local repo?  It'd end up setting the username and email in their local repo to whatever HEAD was.  Honestly, just getting rid of that plugin seems the best.  I don't think we actually use it for anything.

2024-02-13 06:51 UTC, Sgitario approved these changes

2024-02-13 21:23 UTC, merged