Awood/fix profiles
RedHatInsights/rhsm-subscriptions pull request #313
Opened 2021-02-23 18:57 UTC by awood

2021-02-24 16:36 UTC, mstead approved these changes
Agree that productId vs product is a little backwards. If it isn't already, we should create a tech debt card tracking the need to change this. I think this is something that we should do sooner rather than later.

Functionally, this addresses the issue that it was bumped back for.

@kahowell  can do the final merge once he is done his review.

2021-02-24 16:48 UTC, kahowell requested changes
I found the changes a bit hard to follow. Apologies for the late input on naming, but seeing it here certainly helped.

I'd like to ask that we specifically call out in all method/field names which type of product we're talking about:

- engineeringProduct (e.g. 72)
- subscriptionWatchProduct (e.g. "RHEL Workstation")

I tried to identify the top-level field and method changes w/ suggestions (but possibly missed some).

2021-02-24 16:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/capacity/CapacityProductExtractor.java
> +    private final Map<Integer, Set<String>> productToProductIdsMap;
```suggestion
    private final Map<Integer, Set<String>> engineeringProductIdToSubscriptionWatchProductsMap;
```
?

2021-02-24 16:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/files/ProductProfile.java
> +    private Map<String, String> architectureProductIdMap;
```suggestion
    private Map<String, String> architectureToSubscriptionWatchProductMap;
```
?

2021-02-24 16:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/files/SubscriptionWatchProduct.java
> +    private String product;
```suggestion
    private String engineeringProductId;
```
?

2021-02-24 16:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/files/SyspurposeRole.java
> +    private Set<String> productIds;
```suggestion
    private Set<String> subscriptionWatchProductIds;
```
for clarity?

2021-02-24 16:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/files/ProductProfileRegistry.java
> +    private final Map<Integer, ProductProfile> productToProfileMap;
```suggestion
    private final Map<Integer, ProductProfile> engineeringProductIdToProfileMap;
```
?

2021-02-24 16:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/files/ProductProfileRegistry.java
> +    private final Map<String, ProductProfile> productIdToProfileMap;
```suggestion
    private final Map<String, ProductProfile> SubscriptionWatchProductIdToProfileMap;
```
?

2021-02-24 16:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/files/ProductProfileRegistry.java
> +    public ProductProfile findProfileForProductId(String productId) {
```suggestion
    public ProductProfile findProfileForSubscriptionWatchProductId(String productId) {
```
?

2021-02-24 16:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/files/ProductProfileRegistry.java
> +    public ProductProfile findProfileForProduct(Integer product) {
```suggestion
    public ProductProfile findProfileForEngineeringProductId(Integer product) {
```
?

2021-02-24 16:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/files/ProductProfileRegistry.java
> +    public ProductProfile findProfileForProductId(ProductId productId) {
```suggestion
    public ProductProfile findProfileForSubscriptionWatchProductId(ProductId productId) {
```
?

2021-02-24 16:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/files/SubscriptionWatchProduct.java
> +    private Set<String> productIds;
```suggestion
    private Set<String> subscriptionWatchProductIds;
```

2021-02-24 16:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/files/ProductProfileRegistry.java
> +    public ProductProfile findProfileForProduct(String product) {
```suggestion
    public ProductProfile findProfileForEngineeringProductId(String product) {
```

2021-02-26 14:13 UTC, kahowell approved these changes

2021-02-26 14:13 UTC, merged