SWATCH-2317: Move use of UOM to MetricId in tally
RedHatInsights/rhsm-subscriptions pull request #3204
Opened 2024-04-02 19:56 UTC by wottop

Jira issue: SWATCH-2317

## Description
The UOM field is no longer needed as it is redundant to the metric id field

## Testing

The CI test test_verify_remittance_of_metered_product in IQE will cover this change 

### Verification

1. Ensure the above test in specific and the  entire suite in general run successfully

2024-04-03 05:41 UTC, Sgitario requested changes
The changes look good to me, except for some missings places where still remain the `uom` (see comments).
Apart from the comments, by reading the JIRA Ticket SWATCH-2317 I see that removing the `uom` property from BillableUsage and TallyMeasurement is out of scope, so we're good here.
I checked that these two properties are already marked as deprecated in `billable_usage.yaml`  and `tally_snapshot.yaml`, though I miss a comment in `billable_usage.yaml` saying when the uom property from BillableUsage will be dropped, can you add it?

2024-04-03 05:41 UTC, Sgitario commented on src/main/java/org/candlepin/subscriptions/tally/billing/ContractsController.java
>                "Contract metric ID is not configured for billingProvider=%s product=%s uom=%s",
```suggestion
              "Contract metric ID is not configured for billingProvider=%s product=%s metric=%s",
```

2024-04-03 05:41 UTC, Sgitario commented on src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
>          "Processing monthly billable usage for orgId={} productId={} uom={} provider={}, billingAccountId={} snapshotDate={}",
```suggestion
        "Processing monthly billable usage for orgId={} productId={} metric={} provider={}, billingAccountId={} snapshotDate={}",
```

2024-04-03 05:41 UTC, Sgitario commented on src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
>          "Finished producing monthly billable for orgId={} productId={} uom={} provider={}, snapshotDate={}",
```suggestion
        "Finished producing monthly billable for orgId={} productId={} metric={} provider={}, snapshotDate={}",
```

2024-04-03 05:41 UTC, Sgitario commented on src/main/java/org/candlepin/subscriptions/tally/billing/BillingUnit.java
>              .flatMap(
Update the javadocs comment at this class to replace UOM to metric.

2024-04-03 05:41 UTC, Sgitario commented on src/test/java/org/candlepin/subscriptions/tally/billing/QuantityTest.java
> +    createSubscriptionDefinition(billableUsage.getProductId(), billableUsage.getMetricId());
update the `createSubscriptionDefinition` definition to rename the `uom` parameter to `metricId`.

2024-04-03 05:41 UTC, Sgitario commented on src/test/java/org/candlepin/subscriptions/tally/billing/ContractsControllerTest.java
>    void testThrowsIllegalStateExceptionWhenProductIsNotContractEnabled() throws Exception {
The ContractsControllerTest still contains references to `uom` in:
- method `defaultUsage`
- method `createSubscriptionDefinition`

2024-04-03 05:41 UTC, Sgitario commented on src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
>    void monthlyWindowRemittanceMultipleOfBillingFactor() {
The `BillableUsageControllerTest` still contains references to `uom` in:
- method `billable`
- method `createSubscriptionDefinition`

2024-04-03 15:23 UTC, kartikshahc commented
/retest

2024-04-03 18:59 UTC, kartikshahc requested changes

2024-04-03 18:59 UTC, kartikshahc commented on swatch-core/schemas/billable_usage.yaml
>    uom:
You are still using uom here. Causing the IQE tests to fail. Corresponding change needed below:
```
public BillableUsageAggregateKey(BillableUsage billableUsage) {
    this(
        billableUsage.getOrgId(),
        billableUsage.getProductId(),
        billableUsage.getUom(),
        Optional.ofNullable(billableUsage.getSla()).orElse(SlaEnum.EMPTY).value(),
        Optional.ofNullable(billableUsage.getUsage()).orElse(UsageEnum.EMPTY).value(),
        Optional.ofNullable(billableUsage.getBillingProvider())
            .map(BillingProviderEnum::value)
            .orElse(null),
        billableUsage.getBillingAccountId());
  }
```

2024-04-04 04:40 UTC, Sgitario approved these changes

2024-04-04 04:41 UTC, merged