SWATCH-2318: Use metricid instead of UOM from billable usage messages
RedHatInsights/rhsm-subscriptions pull request #3210
Opened 2024-04-03 19:05 UTC by awood

Jira issue: SWATCH-2318

## Description
Consumers from billable-usage now use UOM instead of metricId.

## Testing
Covered by unit test, but insight from QE on *in situ* testing would be appreciated.

2024-04-04 04:46 UTC, Sgitario requested changes
Some of these changes were partially done in https://github.com/RedHatInsights/rhsm-subscriptions/pull/3204 that has been already merged, so it needs rebase to incorporate those changes.

2024-04-04 04:46 UTC, Sgitario approved these changes

2024-04-04 18:41 UTC, awood commented
/retest

2024-04-05 20:16 UTC, TrayvonMcKnight commented
/retest

2024-04-08 15:57 UTC, TrayvonMcKnight approved these changes
No testing around billable_usages. IQE tests will be swithed over to metricId

2024-04-10 17:13 UTC, merged