SWATCH-2361: rhsm-conduit should forward the conversions.activity to HBI
RedHatInsights/rhsm-subscriptions pull request #3341
Opened 2024-05-10 08:23 UTC by Sgitario

Jira issue: [SWATCH-2361](https://issues.redhat.com/browse/SWATCH-2361)

## Description
- forward the conversions.activity fact

## Testing

1.- podman-compose up
2.- start conduit service:

```
RHSM_USE_STUB=true DEV_MODE=true ./gradlew :swatch-system-conduit:bootRun
```

3.- sync the org ID:

```
http :8000/api/rhsm-subscriptions/v1/internal/rpc/syncOrg   x-rh-swatch-psk:placeholder   org_id=org123
```

4.- check the new message that is sent into the Kafka topic "platform.inventory.host-ingress":

```
{
    "topic": "platform.inventory.host-ingress",
    "key": null,
    "value": {
      "operation": "add_host",
      "data": {
        "org_id": "org123",
        "subscription_manager_id": "6089e054-3ff3-4be7-a3fd-027ac70b1048",
        "bios_uuid": "d65b8774-10c5-4c01-be0d-6ec41e6c628d",
        "ip_addresses": [
          "192.167.11.2",
          "192.168.1.1",
          "192.168.122.1",
          "10.0.0.1"
        ],
        "fqdn": "host1.test.com",
        "facts": [
          {
            "namespace": "rhsm",
            "facts": {
              "SYNC_TIMESTAMP": "2024-05-10T07:51:49.705170333Z",
              "IS_VIRTUAL": true,
              "SYSPURPOSE_SLA": "Premium",
              "MEMORY": 32,
              "ARCHITECTURE": "x86_64",
              "VM_HOST": "hypervisor1.test.com",
              "SYSPURPOSE_UNITS": "Sockets",
              "RH_PROD": [
                "72"
              ],
              "orgId": "org123",
              "BILLING_MODEL": "standard"
            }
          }
        ],
        "system_profile": {
          "operating_system": {
            "major": 6,
            "minor": 3,
            "name": "RHEL"
          },
          "os_release": "6.3",
          "releasever": "8.0",
          "arch": "x86_64",
          "cores_per_socket": 2,
          "infrastructure_type": "virtual",
          "system_memory_bytes": 33543999488,
          "number_of_sockets": 2,
          "number_of_cpus": 3,
          "threads_per_core": 5,
          "owner_id": "6089e054-3ff3-4be7-a3fd-027ac70b1048",
          "is_marketplace": true,
          "network_interfaces": [
            {
              "ipv4_addresses": [
                "127.0.0.1"
              ],
              "mac_address": "00:00:00:00:00:00",
              "name": "lo"
            }
          ],
          "conversions_activity": "conversion"
        },
        "stale_timestamp": "2024-05-12T07:51:49.705170333Z",
        "reporter": "rhsm-conduit",
        "provider_id": "123456",
        "provider_type": "aws"
      },
      "platform_metadata": {
        "request_id": "cfa8152d-a29c-4017-9e33-62bcb2ffd9fa"
      }
    }
```

Note the new "conversions_activity" system profile fact.

2024-05-10 12:21 UTC, barnabycourt requested changes
Additional tests should be included to validate if values such as "analysis" or null are specified in the candlepin facts, then the value in the system profile will be false/unset.

2024-05-10 12:21 UTC, barnabycourt commented on swatch-system-conduit/schemas/inventory/hbi-system-profile.yaml
> +    type: string
Per: https://github.com/RedHatInsights/inventory-schemas/pull/129/files#diff-952f7dbba2e7a294392a7ac96f3f9a505fff472c194ecf63763c221e7ef84fb5R759, I believe the value in the HBI system profile is a boolean

2024-05-13 12:16 UTC, barnabycourt commented
/lgtm

2024-05-14 05:06 UTC, Aurobinda55 commented
@Sgitario I am not able to see the fact(conversions_activity) in the system profile fatcs,

```
In [10]: app.host_inventory.rest_client.hosts_api.api_host_get_host_system_profile_by_id(["19bee6cb-4f27-4c2e-a4b3-7ef32d66127d"])
2024-05-14 04:17:40.320 [    INFO] [iqe.base.rest_client] REST: METHOD=GET, request_id=None, params=[]
Out[10]: 
{'count': 1,
 'page': 1,
 'per_page': 50,
 'results': [{'id': '19bee6cb-4f27-4c2e-a4b3-7ef32d66127d',
              'system_profile': {'ansible': None,
                                 'arch': 'x86_64',
                                 'basearch': 'string',
                                 'bios_release_date': 'string',
                                 'bios_vendor': 'string',
                                 'bios_version': 'string',
                                 'bootc_status': None,
                                 'captured_date': None,
                                 'cloud_provider': 'test cloud provider',
                                 'conversions': None,
                                 'cores_per_socket': 1,
                                 'cpu_flags': [],
                                 'cpu_model': None,
                                 'disk_devices': [],
                                 'dnf_modules': None,
                                 'enabled_services': [],
                                 'gpg_pubkeys': None,
                                 'greenboot_fallback_detected': None,
                                 'greenboot_status': None,
                                 'host_type': None,
                                 'infrastructure_type': 'virtual',
                                 'infrastructure_vendor': 'string',
                                 'insights_client_version': 'string',
                                 'insights_egg_version': 'string',
                                 'installed_packages': [],
                                 'installed_packages_delta': None,
                                 'installed_products': [],
                                 'installed_services': [],
                                 'intersystems': None,
                                 'is_marketplace': None,
                                 'katello_agent_running': False,
                                 'kernel_modules': [],
                                 'last_boot_time': datetime.datetime(2024, 5, 13, 10, 14, 23, 979466, tzinfo=tzlocal()),
                                 'mssql': None,
                                 'network_interfaces': [],
                                 'number_of_cpus': 1,
                                 'number_of_sockets': 1,
                                 'operating_system': {'major': 8,
                                                      'minor': 7,
                                                      'name': 'RHEL'},
                                 'os_kernel_version': '3.10.0',
                                 'os_release': 'string',
                                 'owner_id': 'be73358c-74f5-4a59-90ba-6052b00735a1',
                                 'public_dns': None,
                                 'public_ipv4_addresses': None,
                                 'releasever': 'string',
                                 'rhc_client_id': None,
                                 'rhc_config_state': None,
                                 'rhsm': None,
                                 'rpm_ostree_deployments': None,
                                 'running_processes': [],
                                 'sap': None,
                                 'sap_instance_number': None,
                                 'sap_sids': None,
                                 'sap_system': None,
                                 'sap_version': None,
                                 'satellite_managed': True,
                                 'selinux_config_file': None,
                                 'selinux_current_mode': None,
                                 'subscription_auto_attach': 'string',
                                 'subscription_status': 'string',
                                 'system_memory_bytes': 77824,
                                 'system_purpose': None,
                                 'system_update_method': None,
                                 'systemd': None,
                                 'threads_per_core': 1,
                                 'tuned_profile': None,
                                 'virtual_host_uuid': None,
                                 'yum_repos': []}}],
 'total': 1}

```

2024-05-14 05:32 UTC, Sgitario commented
> @Sgitario I am not able to see the fact(conversions_activity) in the system profile fatcs,
> 
> ```
> In [10]: app.host_inventory.rest_client.hosts_api.api_host_get_host_system_profile_by_id(["19bee6cb-4f27-4c2e-a4b3-7ef32d66127d"])
> 2024-05-14 04:17:40.320 [    INFO] [iqe.base.rest_client] REST: METHOD=GET, request_id=None, params=[]
> Out[10]: 
> {'count': 1,
>  'page': 1,
>  'per_page': 50,
>  'results': [{'id': '19bee6cb-4f27-4c2e-a4b3-7ef32d66127d',
>               'system_profile': {'ansible': None,
>                                  'arch': 'x86_64',
>                                  'basearch': 'string',
>                                  'bios_release_date': 'string',
>                                  'bios_vendor': 'string',
>                                  'bios_version': 'string',
>                                  'bootc_status': None,
>                                  'captured_date': None,
>                                  'cloud_provider': 'test cloud provider',
>                                  'conversions': None,
>                                  'cores_per_socket': 1,
>                                  'cpu_flags': [],
>                                  'cpu_model': None,
>                                  'disk_devices': [],
>                                  'dnf_modules': None,
>                                  'enabled_services': [],
>                                  'gpg_pubkeys': None,
>                                  'greenboot_fallback_detected': None,
>                                  'greenboot_status': None,
>                                  'host_type': None,
>                                  'infrastructure_type': 'virtual',
>                                  'infrastructure_vendor': 'string',
>                                  'insights_client_version': 'string',
>                                  'insights_egg_version': 'string',
>                                  'installed_packages': [],
>                                  'installed_packages_delta': None,
>                                  'installed_products': [],
>                                  'installed_services': [],
>                                  'intersystems': None,
>                                  'is_marketplace': None,
>                                  'katello_agent_running': False,
>                                  'kernel_modules': [],
>                                  'last_boot_time': datetime.datetime(2024, 5, 13, 10, 14, 23, 979466, tzinfo=tzlocal()),
>                                  'mssql': None,
>                                  'network_interfaces': [],
>                                  'number_of_cpus': 1,
>                                  'number_of_sockets': 1,
>                                  'operating_system': {'major': 8,
>                                                       'minor': 7,
>                                                       'name': 'RHEL'},
>                                  'os_kernel_version': '3.10.0',
>                                  'os_release': 'string',
>                                  'owner_id': 'be73358c-74f5-4a59-90ba-6052b00735a1',
>                                  'public_dns': None,
>                                  'public_ipv4_addresses': None,
>                                  'releasever': 'string',
>                                  'rhc_client_id': None,
>                                  'rhc_config_state': None,
>                                  'rhsm': None,
>                                  'rpm_ostree_deployments': None,
>                                  'running_processes': [],
>                                  'sap': None,
>                                  'sap_instance_number': None,
>                                  'sap_sids': None,
>                                  'sap_system': None,
>                                  'sap_version': None,
>                                  'satellite_managed': True,
>                                  'selinux_config_file': None,
>                                  'selinux_current_mode': None,
>                                  'subscription_auto_attach': 'string',
>                                  'subscription_status': 'string',
>                                  'system_memory_bytes': 77824,
>                                  'system_purpose': None,
>                                  'system_update_method': None,
>                                  'systemd': None,
>                                  'threads_per_core': 1,
>                                  'tuned_profile': None,
>                                  'virtual_host_uuid': None,
>                                  'yum_repos': []}}],
>  'total': 1}
> ```

You need to create a Host in HBI with the system profile fact `conversions.activity: conversion` like I did in the stub service: https://github.com/RedHatInsights/rhsm-subscriptions/pull/3341/files#diff-d0dfdf9aac89aaddb01f04ff3427fa9348368c0d6f4a4b7a69590c8a3c331fbfR90

2024-05-16 03:47 UTC, Aurobinda55 commented
/retest

2024-05-21 05:03 UTC, Sgitario commented
/retest

2024-05-21 06:55 UTC, Sgitario commented
/retest

2024-05-22 04:50 UTC, Aurobinda55 commented
Verification steps :

- Created a physical host with fact- `{"conversions. activity": "conversion"}`
- Sync conduit 
- Checked system profile and got` 'conversions': {'activity': True},`
- Repeat step-1 and 2 and replace `conversion.activity: ''any"`
- Checked system profile and found `conversions': {'activity': False}`

Added automation https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/710

2024-05-22 05:26 UTC, Sgitario commented
/retest

2024-05-22 08:38 UTC, Sgitario commented
/retest

2024-05-22 12:36 UTC, Sgitario commented
/retest

2024-05-23 04:18 UTC, merged