SWATCH-2594: Ensure ordering of streams when collating hosts
RedHatInsights/rhsm-subscriptions pull request #3385
Opened 2024-05-30 09:12 UTC by Sgitario

Jira issue: SWATCH-2594

## Description
The problem is that when querying the hosts in stage, we're retrieving the following hosts at this order:

First iteration:
- Inventory Host with InventoryId=YYY
- Swatch Host with InventoryId=AAA

Second iteration: 
- Inventory Host with InventoryId=ANY
- Swatch Host with InventoryId=YYY (it should be found in the first iteration!)

I don't see how we could possible resolve the issue by tweaking the order by statement in the HostRepository.streamHbiHostsByOrgId since the InventoryId is ordered alphabetically, so the above is a realistic scenario).

The only solution that I can think of is to sorting the streams using the SortKey.

## Testing
I reproduced the scenario using unit tests.

2024-05-30 20:52 UTC, kahowell requested changes
Both of those sorts should have no effect other than increased memory usage. Are my assumptions incorrect?

2024-05-30 20:52 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/tally/InventorySwatchDataCollator.java
> +            .sorted(Comparator.comparing(SortKey::fromHbiSystem));
This should be a no-op given the order by clause:
https://github.com/RedHatInsights/rhsm-subscriptions/blob/9050d6340388cc41ee15c3f771cd96ab15519555/src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java#L159

should be equivalent to the `SortKey`'s `compareTo` implementation:

https://github.com/RedHatInsights/rhsm-subscriptions/blob/9050d6340388cc41ee15c3f771cd96ab15519555/src/main/java/org/candlepin/subscriptions/tally/InventorySwatchDataCollator.java#L268-L281

2024-05-30 20:52 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/tally/InventorySwatchDataCollator.java
> +            .sorted(Comparator.comparing(SortKey::fromSwatchSystem));
This should be a no-op given the order-by clause:
https://github.com/RedHatInsights/rhsm-subscriptions/blob/3fb6479130cd1118346f1065f396e6b235df3039/swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java#L73

should be equivalent to the `SortKey`'s `compareTo` implementation:

https://github.com/RedHatInsights/rhsm-subscriptions/blob/9050d6340388cc41ee15c3f771cd96ab15519555/src/main/java/org/candlepin/subscriptions/tally/InventorySwatchDataCollator.java#L268-L281

2024-05-30 20:57 UTC, kahowell commented
Put another way, rather than invoking a sort using the `SortKey` as a comparator, the effect will be the same if we fix whatever is causing the `SortKey` `compareTo` to not be equivalent to the `order by` clauses (probably only need changes in the `compareTo` implementation), and then it won't require increased memory usage. I haven't had a chance to dig deeper to see exactly where they differ, but I think it should be feasible using a debugger on the unit test case you added.

2024-05-31 05:18 UTC, closed without merging

2024-05-31 05:18 UTC, Sgitario commented
Closing to look for another solution.