SWATCH-2020: Add CSV support to instances export
RedHatInsights/rhsm-subscriptions pull request #3448
Opened 2024-06-18 19:07 UTC by wottop

Jira issue: SWATCH-2020

## Description
- added capability to create CSV output for instances 

## Testing
1.- start kafka and postgresql: `podman-compose up -d`
2.- start export-service: `podman-compose -f config/export-service/docker-compose.yml up -d`
3.- start the tally service: `RHSM_RBAC_USE_STUB=true DEV_MODE=true SPRING_PROFILES_ACTIVE="worker,api,kafka-queue" ./gradlew :bootRun`
4.- load some data:

```
insert into account_services(org_id, service_type) values ('123', 'test');

insert into hosts(id, org_id, num_of_guests, instance_id, display_name, billing_provider, billing_account_id, instance_type) 
values ('b870dc34-53a3-4634-bfd1-56c227bc36ac','123', 3, '456', 'my host', 'AWS', '789', 'test');

insert into host_tally_buckets (host_id, product_id, "usage", sla, as_hypervisor, billing_provider, billing_account_id, measurement_type, cores, sockets) 
values ('b870dc34-53a3-4634-bfd1-56c227bc36ac', 'RHEL for x86', 'PRODUCTION', 'PREMIUM', true, 'AWS', '789', 'PHYSICAL', 3, 6);

insert into instance_measurements (host_id, metric_id, value)
values ('b870dc34-53a3-4634-bfd1-56c227bc36ac', 'SOCKETS', 4.8);
```

5.- create a new export request from Export Service:

get the identifier first:
```
echo -n '{"identity":{"account_number":"10001","org_id":"123","internal":{"org_id":"13259775"},"type":"User","user":{"username":"user_dev"}}}' | base64 -w 0
> eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjEwMDAxIiwib3JnX2lkIjoiMTIzIiwiaW50ZXJuYWwiOnsib3JnX2lkIjoiMTMyNTk3NzUifSwidHlwZSI6IlVzZXIiLCJ1c2VyIjp7InVzZXJuYW1lIjoidXNlcl9kZXYifX19
```

call the export service:
```
curl -sS -X POST http://localhost:8002/api/export/v1/exports -H "x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjEwMDAxIiwib3JnX2lkIjoiMTIzIiwiaW50ZXJuYWwiOnsib3JnX2lkIjoiMTMyNTk3NzUifSwidHlwZSI6IlVzZXIiLCJ1c2VyIjp7InVzZXJuYW1lIjoidXNlcl9kZXYifX19" -H "Content-Type: application/json" -d '{
    "name": "Test Export Request",
    "format": "csv",
    "expires_at": "2025-01-01T00:00:00Z",
    "sources": [
        {
            "application": "subscriptions",
            "resource": "instances",
            "filters": {
                "product_id": "RHEL for x86"
            }
        }
    ]
}'
```

Expected output is:
```
{"id":"78244e87-2abe-49af-8821-67b14128c5c3","created_at":"2024-04-05T06:30:01.034156787Z","expires_at":"2025-01-01T00:00:00Z","name":"Test Export Request","format":"csv","status":"pending","sources":[{"id":"2008873d-916d-4240-8cd8-55ca00141c55","application":"subscriptions","status":"pending","resource":"instances","filters":{"product_id":"RHEL for x86"}}]}
```

The export-service should have uploaded the generated report by the subscription sync service into S3 (minio instance). 
You can verify that this report has been uploaded by checking the folder 'config/export-service/tmp/minio/exports-bucket' where should be a file at `<BUCKET ID>.json/xl.meta`. The `xl.meta` file is binary, but if you open the txt plain editor, you should see (as an example):

```
id,instance_id,display_name,billing_provider,billing_account_id,measurement_cores,measurement_instances,"measurement_instance_hours",measurement_sockets,"measurement_storage_gibibytes","measurement_storage_gibibyte_months","measurement_transfer_gibibytes",measurement_vcpus,category,last_seen,hypervisor_uuid
"1cbadb23-e86d-4574-b46f-e218eda8aa74","62228bfa-cee9-4ecf-8880-8cc4b526fed4",rosa-hcp,aws,168911171442,336.0,,42.0,,,,,,,2024-06-17T16:00:00Z,
```

2024-06-19 05:56 UTC, Sgitario requested changes
changes look good to me, but I'm missing a test to cover the changes.

2024-06-19 13:03 UTC, Sgitario commented
PR updated with the following changes:
- Refactor solution to directly use MetricId ++ remove unexisting metrics: measurement_instances and measurement_storage_gibibytes
- Map missing hypervisor_uuid
- Added test to cover CSV functionality

2024-06-20 06:11 UTC, Sgitario commented
/retest

2024-06-20 18:16 UTC, san7ket commented
/retest

2024-06-21 05:08 UTC, Sgitario commented
/retest

2024-06-21 09:02 UTC, ntkathole commented
/retest

2024-06-24 07:48 UTC, san7ket commented
New tests passed https://ci.ext.devshift.net/job/RedHatInsights-rhsm-subscriptions-pr-check/7304/testReport/tests.exports%20/test_export_instances/test_export_instances_payg_product_filters_csv_rhel_for_x86_els_payg_/ , but would need a rebase for this

2024-07-02 10:29 UTC, san7ket commented
Hypervisor export are missing data related to guests. 
```
[{'id': 'e2296eac-d5cd-4f8f-a90a-e62c0754361b',
  'instance_id': '507da0bd-feb3-4d92-b012-68aa87be94a2',
  'display_name': 'physical_mockerunjmbr.example.org',
  'billing_provider': '',
  'billing_account_id': '',
  'measurement_cores': '',
  'measurement_instance_hours': '',
  'measurement_sockets': '2.0',
  'measurement_storage_gibibyte_months': '',
  'measurement_transfer_gibibytes': '',
  'measurement_vcpus': '',
  'category': 'hypervisor',
  'last_seen': '2024-07-02T09:44:06.999539Z',
  'hypervisor_uuid': ''}]
```

Metrics for all products are shown, do we want to show them, Can we hide them for irrelevant product_ids
```
 {'id': 'fde12c36-59b1-4986-b792-0663ab0cbfb1',
  'instance_id': 'a21dd842-54bd-4777-9f2e-cddddf89bb2a',
  'display_name': 'automation_moa-hostedcontrolplane_cluster_a21dd842-54bd-4777-9f2e-cddddf89bb2a',
  'billing_provider': 'aws',
  'billing_account_id': 'testtsy',
  'measurement_cores': '12.316637155029259',
  'measurement_instance_hours': '1.0',
  'measurement_sockets': '',
  'measurement_storage_gibibyte_months': '',
  'measurement_transfer_gibibytes': '',
  'measurement_vcpus': '',
  'category': '',
  'last_seen': '2024-07-02T09:00:00Z',
  'hypervisor_uuid': ''}]
```

2024-07-02 10:51 UTC, Sgitario commented
> Hypervisor export are missing data related to guests. Also, 'number_of_guests': 2, missing

This is not a requirement from the JIRA ticket. FYI @lindseyburnett . We can easily map the number_of_guests, but for the guests, we would need to add as many columns as the guest data we would want to export. This should be out of scope for this PR.

2024-07-02 10:53 UTC, Sgitario commented
> Metrics for all products are shown, do we want to show them, Can we hide them for irrelevant product_ids

We can't easily hide/show columns depending on the format (csv or json). This would require an extra effort in development to support this. @san7ket are you ok with raising a new JIRA ticket for supporting this in the future?

2024-07-10 05:11 UTC, ntkathole commented
/retest

2024-07-11 05:00 UTC, Sgitario approved these changes

2024-07-11 06:02 UTC, san7ket commented
Filed https://issues.redhat.com/browse/SWATCH-2730 to track hypervisor mapping separately. ACK on this

2024-07-11 06:15 UTC, Sgitario commented
> Filed https://issues.redhat.com/browse/SWATCH-2730 to track hypervisor mapping separately. ACK on this

Thanks!

2024-07-11 06:16 UTC, merged