SWATCH-2673: Remove character limit from events instance_id column
RedHatInsights/rhsm-subscriptions pull request #3485
Opened 2024-06-28 18:39 UTC by kflahert

Jira issue: SWATCH-2673

## Description

## Testing

IQE Test MR: 

### Setup

1. Start app with: `DEV_MODE=true ./gradlew :bootRun`

### Steps

1. Create event using internal api:
```
curl -X 'POST'   'http://localhost:8000/api/rhsm-subscriptions/v1/internal/rpc/tally/events' -H 'Origin: .redhat.com'  -H 'accept: application/json'   -H 'x-rh-swatch-psk: placeholder'   -H 'Content-Type: application/json'   -d '[
  {
    "event_id": "0998c49b-9552-463f-b363-0a4b046dd6e9",
    "event_source": "prometheus",
    "event_type": "snapshot_redhat.com:BASILISK:storage_gb",
    "account_number": "account123",
    "org_id": "org123",
    "service_type": "BASILISK Instance",
    "instance_id": "c5mu16smf1c22rn8e730morethan60characters1000000000000000000000000000000000000000000000000000000000000000000",
    "timestamp": "2021-10-18T22:00:00Z",
    "expiration": "2021-10-19T22:00:00Z",
    "display_name": "c5mu16smf1c22rn8e730",
    "measurements": [
      {
        "value": 1.5,
        "uom": "Storage-gibibyte-months"
      }
    ],
    "role": "BASILISK",
    "sla": "Premium",
    "billing_provider": "red hat",
    "billing_account_id": "placeholderId"
  }
]'

```
Verification:
1. Check database that record is saved: `SELECT * from events where event_id = '0998c49b-9552-463f-b363-0a4b046dd6e9';`

2024-07-01 10:57 UTC, Sgitario approved these changes
It seems that the both varchar(N) and the text types have the same performance, so everything good here.

2024-07-01 14:58 UTC, lindseyburnett requested changes

2024-07-01 14:58 UTC, lindseyburnett commented on src/main/resources/liquibase/202406261514-alter-event-instance-id-length.xml
Could you add a `<rollback>` instruction to this?

2024-07-01 18:45 UTC, liwalker-rh commented
/retest

2024-07-02 12:40 UTC, liwalker-rh approved these changes
Looks good after testing. Created an IQE MR to test instance ids of different lengths: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/768

2024-07-02 18:03 UTC, merged