SWATCH-2650 Implement level 1 and level 2 attr in offering
RedHatInsights/rhsm-subscriptions pull request #3503
Opened 2024-07-03 12:55 UTC by kartikshahc

Jira issue: SWATCH-XXXX

## Description

## Testing

IQE Test MR: 

### Setup

1.
1.

### Steps

1.
1.

### Verification

1.
1.

2024-07-03 21:28 UTC, kartikshahc commented on src/main/java/org/candlepin/subscriptions/product/UpstreamProductData.java
> +    LEVEL_1,
Not sure if we need '_'  but, to be consistent may be we can add it to offering table columns?

2024-07-11 18:47 UTC, lindseyburnett commented
/retest

2024-07-12 01:21 UTC, lindseyburnett commented
/retest

2024-07-12 15:09 UTC, kahowell requested changes

2024-07-12 15:09 UTC, kahowell commented on swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
> +              && Objects.equals(paramLevel2, variantLevel2);
```suggestion
          return isNullOrEmpty(paramLevel2)
              || (!isNullOrEmpty(variantLevel2)
              && Objects.equals(paramLevel2, variantLevel2));
```

2024-07-12 15:40 UTC, kahowell approved these changes
All is good, I misunderstood the implementation previously, my bad :smile:

2024-07-12 16:14 UTC, kahowell approved these changes

2024-07-13 23:38 UTC, lindseyburnett commented
/retest

2024-07-14 13:17 UTC, lindseyburnett commented
/retest

2024-07-15 19:49 UTC, liwalker-rh approved these changes
Testing looks good. Also working on IQE coverage: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/791

2024-07-16 17:51 UTC, merged