Set the measurement type when creating buckets
RedHatInsights/rhsm-subscriptions pull request #3520
Opened 2024-07-10 15:37 UTC by mstead

Jira issue: SWATCH-2712

## Description
Properly set the measurement type on buckets while updating hosts during the hourly tally. Prior to this patch the bucket measurement type was always getting set to null.

A liquibase changeset was added that updates the measurement_type of any records with a NULL measurement_type to PHYSICAL, since this is our default in code logic.

The changeset also defaults the measurement_type column to PHYSICAL.

## Testing

### Setup
1. Checkout the **main** branch.

2. Reset the HBI DB
```
psql -h localhost -U insights insights -c "truncate hosts cascade;"
```

3. Insert a single host into the HBI DB.
```
INSERT INTO public.hosts (id, account, display_name, created_on, modified_on, facts, tags, canonical_facts, system_profile_facts, ansible_host, stale_timestamp, reporter, per_reporter_staleness, org_id, groups) VALUES ('54e25247-3f80-496b-97ea-75e95b5f4830', '', 'fqdn123456', '2024-07-03 21:54:14.517152 +00:00', '2024-07-03 21:59:04.808071 +00:00', '{}', '{}', '{"fqdn": "l5003u0d13ct314", "bios_uuid": "12345-6850-d844-a576-ec70aabb1f60", "provider_id": "test-instance", "ip_addresses": ["127.0.0.1"], "mac_addresses": [], "provider_type": "azure", "subscription_manager_id": "90db0ceb-ea92-720f-9569-6709bda25e81"}', '{"arch": "x86_64", "owner_id": "1234", "yum_repos": [{"id": "rhel-7-server-rpms", "name": "Red Hat Enterprise Linux 7 Server (RPMs)", "enabled": true}], "os_release": "7.9", "dnf_modules": [], "installed_packages": ["krb5-libs-0:1.15.1-55.el7_9.x86_64", "jansson-0:2.10-1.el7.x86_64", "words-0:3.0-22.el7.noarch", "perl-Carp-0:1.26-244.el7.noarch", "libreport-cli-0:2.1.11-53.el7.x86_64", "libgudev1-0:219-78.el7_9.9.x86_64", "perl-Socket-0:2.010-5.el7.x86_64", "sg3_utils-libs-1:1.37-19.el7.x86_64", "python2-pyasn1-0:0.1.9-7.el7.noarch", "rpm-0:4.11.3-48.el7_9.x86_64", "libteam-0:1.29-3.el7.x86_64", "python-urlgrabber-0:3.10-10.el7.noarch", "libgomp-0:4.8.5-44.el7.x86_64", "libdb-utils-0:5.3.21-25.el7.x86_64", "libselinux-0:2.5-15.el7.x86_64", "hostname-0:3.13-3.el7_7.1.x86_64", "pinentry-0:0.8.1-17.el7.x86_64", "gettext-0:0.19.8.1-3.el7_9.x86_64", "libproxy-0:0.4.11-11.el7.x86_64", "gdisk-0:0.8.10-3.el7.x86_64", "alsa-firmware-0:1.0.28-2.el7.noarch", "libyaml-0:0.1.4-11.el7_0.x86_64", "libsmartcols-0:2.23.2-65.el7_9.1.x86_64", "ipset-libs-0:7.1-1.el7.x86_64", "libsysfs-0:2.1.0-16.el7.x86_64", "device-mapper-event-libs-7:1.02.170-6.el7_9.5.x86_64", "firewalld-0:0.6.3-13.el7_9.noarch", "shared-mime-info-0:1.8-5.el7.x86_64", "cryptsetup-reencrypt-0:2.0.3-6.el7.x86_64", "libss-0:1.42.9-19.el7.x86_64", "python-gobject-base-0:3.22.0-1.el7_4.1.x86_64", "patch-0:2.7.1-12.el7_7.x86_64", "ncurses-0:5.9-14.20130511.el7_4.x86_64", "grub2-tools-1:2.02-0.87.el7_9.14.x86_64", "tcp_wrappers-libs-0:7.6-77.el7.x86_64", "usbutils-0:007-5.el7.x86_64", "python-libs-0:2.7.5-94.el7_9.x86_64", "net-tools-0:2.0-0.25.20131004git.el7.x86_64", "grubby-0:8.28-26.el7.x86_64", "gnutls-0:3.3.29-9.el7_6.x86_64", "cryptsetup-0:2.0.3-6.el7.x86_64", "rhnlib-0:2.5.65-8.el7.noarch", "libreport-plugin-rhtsupport-0:2.1.11-53.el7.x86_64", "gobject-introspection-0:1.56.1-1.el7.x86_64", "redhat-support-lib-python-0:0.14.0-1.el7_9.noarch", "python-firewall-0:0.6.3-13.el7_9.noarch", "grub2-tools-extra-1:2.02-0.87.el7_9.14.x86_64", "grub2-pc-1:2.02-0.87.el7_9.14.x86_64", "abrt-addon-vmcore-0:2.1.11-60.el7.x86_64", "nss-0:3.90.0-2.el7_9.x86_64", "lz4-0:1.8.3-1.el7.x86_64", "openssl-1:1.0.2k-26.el7_9.x86_64", "python-magic-0:5.11-37.el7.noarch", "NessusAgent-0:10.5.1-el7.x86_64", "ed-0:1.9-4.el7.x86_64", "gdb-0:7.6.1-120.el7.x86_64", "hypervfcopyd-0:0-0.34.20180415git.el7.x86_64", "python-chardet-0:2.2.1-3.el7.noarch", "kernel-0:3.10.0-1160.118.1.el7.x86_64", "abrt-tui-0:2.1.11-60.el7.x86_64", "cronie-anacron-0:1.4.11-25.el7_9.x86_64", "openssh-server-0:7.4p1-23.el7_9.x86_64", "teamd-0:1.29-3.el7.x86_64", "mailx-0:12.5-19.el7.x86_64", "rh-dotnetcore11-runtime-0:1.0-1.el7.x86_64", "libpcap-14:1.5.3-13.el7_9.x86_64", "bind-license-32:9.11.4-26.P2.el7_9.16.noarch", "WALinuxAgent-0:2.3.0.2-4.el7_9.noarch", "tar-2:1.26-35.el7.x86_64", "dhcp-libs-12:4.2.5-83.el7_9.2.x86_64", "python-jsonpointer-0:1.9-2.el7.noarch", "quota-1:4.01-19.el7.x86_64", "bind-export-libs-32:9.11.4-26.P2.el7_9.16.x86_64", "pyserial-0:2.6-6.el7.noarch", "vdo-0:6.1.3.23-5.el7.x86_64", "less-0:458-10.el7_9.x86_64", "util-linux-0:2.23.2-65.el7_9.1.x86_64", "authconfig-0:6.2.8-30.el7.x86_64", "iwl2000-firmware-0:18.168.6.1-83.el7_9.noarch", "libstdc++-devel-0:4.8.5-44.el7.x86_64", "lsscsi-0:0.27-6.el7.x86_64", "iwl105-firmware-0:18.168.6.1-83.el7_9.noarch", "chrony-0:3.4-1.el7.x86_64", "iwl6000g2a-firmware-0:18.168.6.1-83.el7_9.noarch", "xz-libs-0:5.2.2-2.el7_9.x86_64", "nspr-0:4.35.0-1.el7_9.x86_64", "iwl3945-firmware-0:15.32.2.9-83.el7_9.noarch", "perl-macros-4:5.16.3-299.el7_9.x86_64", "pam-0:1.1.8-23.el7.x86_64", "pexpect-0:2.3-11.el7.noarch", "btrfs-progs-0:4.9.1-1.el7.x86_64", "ntp-0:4.2.6p5-29.el7_8.2.x86_64", "sg3_utils-1:1.37-19.el7.x86_64", "rpm-libs-0:4.11.3-48.el7_9.x86_64", "grub2-pc-modules-1:2.02-0.87.el7_9.14.noarch", "initscripts-0:9.49.53-1.el7_9.1.x86_64", "rdate-0:1.4-25.el7.x86_64", "python-slip-0:0.4.0-4.el7.noarch", "gettext-libs-0:0.19.8.1-3.el7_9.x86_64", "subscription-manager-rhsm-0:1.24.54-1.el7_9.x86_64", "python-pyudev-0:0.15-9.el7.noarch", "systemd-python-0:219-78.el7_9.9.x86_64", "nmap-ncat-2:6.40-19.el7.x86_64", "grub2-1:2.02-0.87.el7_9.14.x86_64", "abrt-addon-ccpp-0:2.1.11-60.el7.x86_64", "libuser-0:0.60-9.el7.x86_64", "NetworkManager-team-1:1.18.8-2.el7_9.x86_64", "langtable-data-0:0.0.31-4.el7.noarch", "fprintd-pam-0:0.8.1-2.el7.x86_64", "setuptool-0:1.19.11-8.el7.x86_64", "libstdc++-0:4.8.5-44.el7.x86_64", "perl-Pod-Escapes-1:1.04-299.el7_9.noarch", "unzip-0:6.0-24.el7_9.x86_64", "ustr-0:1.0.4-16.el7.x86_64", "crda-0:3.18_2018.05.31-4.el7.x86_64", "sgpio-0:1.2.0.10-13.el7.x86_64", "tcpdump-14:4.9.2-4.el7_7.1.x86_64", "popt-0:1.13-16.el7.x86_64", "wget-0:1.14-18.el7_6.1.x86_64", "apr-0:1.4.8-7.el7.x86_64", "nano-0:2.3.1-10.el7.x86_64", "avahi-libs-0:0.6.31-20.el7.x86_64", "bridge-utils-0:1.5-9.el7.x86_64", "libdb-0:5.3.21-25.el7.x86_64", "hyperv-daemons-license-0:0-0.34.20180415git.el7.noarch", "pakchois-0:0.4-10.el7.x86_64", "libtar-0:1.2.11-29.el7.x86_64", "passwd-0:0.79-6.el7.x86_64", "polkit-pkla-compat-0:0.1-4.el7.x86_64", "tzdata-0:2024a-1.el7.noarch", "lua-0:5.1.4-15.el7.x86_64", "lm_sensors-libs-0:3.4.0-8.20160601gitf9185e5.el7_9.1.x86_64", "iputils-0:20160308-10.el7.x86_64", "file-0:5.11-37.el7.x86_64", "cloud-init-0:19.4-7.el7_9.6.x86_64", "perl-podlators-0:2.5.1-3.el7.noarch", "libattr-0:2.4.46-13.el7.x86_64", "perl-threads-0:1.87-4.el7.x86_64", "kernel-debug-devel-0:3.10.0-1160.118.1.el7.x86_64", "perl-constant-0:1.27-2.el7.noarch", "dwz-0:0.11-3.el7.x86_64", "abrt-python-0:2.1.11-60.el7.x86_64", "sqlite-0:3.7.17-8.el7_7.1.x86_64", "abrt-addon-xorg-0:2.1.11-60.el7.x86_64", "bash-0:4.2.46-35.el7_9.x86_64", "usb_modeswitch-data-0:20170806-1.el7.noarch", "perl-XML-Parser-0:2.41-10.el7.x86_64", "python-slip-dbus-0:0.4.0-4.el7.noarch", "perl-libs-4:5.16.3-299.el7_9.x86_64", "kmod-kvdo-0:6.1.3.23-5.el7.x86_64", "geoipupdate-0:2.5.0-2.el7.x86_64", "rpcbind-0:0.2.0-49.el7.x86_64", "shim-x64-0:15.8-1.el7.x86_64", "efivar-libs-0:36-12.el7.x86_64", "sos-0:3.9-5.el7_9.12.noarch", "libnfnetlink-0:1.0.1-4.el7.x86_64", "basesystem-0:10.0-7.el7.noarch", "yajl-0:2.0.4-4.el7.x86_64", "libunwind-2:1.2-2.el7.x86_64", "ethtool-2:4.8-10.el7.x86_64", "fxload-0:2002_04_11-16.el7.x86_64", "GeoIP-0:1.5.0-14.el7.x86_64", "iproute-0:4.11.0-30.el7.x86_64", "audit-libs-python-0:2.8.5-4.el7.x86_64", "ipset-0:7.1-1.el7.x86_64", "tcp_wrappers-0:7.6-77.el7.x86_64", "hardlink-1:1.0-19.el7.x86_64", "acl-0:2.2.51-15.el7.x86_64", "strace-0:4.24-7.el7_9.x86_64", "libdwarf-0:20130207-4.el7.x86_64", "libutempter-0:1.1.6-4.el7.x86_64", "make-1:3.82-24.el7.x86_64", "python-jinja2-0:2.7.2-4.el7.noarch", "libconfig-0:1.4.9-5.el7.x86_64", "libmpc-0:1.0.1-3.el7.x86_64", "snappy-0:1.1.0-3.el7.x [...]

2024-07-10 18:23 UTC, awood approved these changes
A+ testing steps!

2024-07-10 19:50 UTC, mstead commented
/retest

2024-07-11 04:05 UTC, ntkathole commented
/retest

2024-07-11 14:47 UTC, lindseyburnett requested changes

2024-07-11 14:47 UTC, lindseyburnett commented on src/main/resources/liquibase/changelog.xml
Can you fix the typo in the file name?

2024-07-11 15:57 UTC, mstead commented on src/main/resources/liquibase/changelog.xml
DONE

2024-07-12 14:02 UTC, mstead commented
/retest

2024-07-12 18:57 UTC, lindseyburnett approved these changes

2024-07-12 19:29 UTC, liwalker-rh approved these changes
Testing looks good. Probably going to add some automation support for this as well but this should be good to merge.

2024-07-12 23:36 UTC, merged