SWATCH-2766: Error reading denylist
RedHatInsights/rhsm-subscriptions pull request #3606
Opened 2024-08-07 17:31 UTC by wottop

Jira issue: SWATCH-2766

## Description

When the product id is null we need to return false instead of checking against the denylist

## Testing
Unit tests to cover places where this is found

2024-08-08 10:48 UTC, ntkathole commented
/retest

2024-08-08 11:21 UTC, Sgitario requested changes
The root cause of this issue is that there are some tests trying to save subscriptions with a sku = null:

```json
[{"id": 951221, "subscriptionNumber": 8401831, "subscriptionProducts": [{"sku": null}], "webCustomerId": "17702870", "quantity": 1, "oracleAccountNumber": "", "effectiveStartDate": 1719792188216.0, "effectiveEndDate": 1753920188216.0, "externalReferences": {"azureMarketplace": {"accountID": null, "subscriptionID": "testBillingProvider", "azureResourceId": "a69ff71c-aa8b-43d9-dea8-822fab4bbb86", "partner": "azure_marketplace", "offerId": "azureProductCode", "planId": "rh-rhel-sub-1yr"}}}]
```

Splunk query: `index=rh_rhsm namespace="rhsm-stage" properties.trace_id="f81a1a50ad5b0701c156f08ec5541937"` (from 31 July). 

@ntkathole this is something that you might need to address (or maybe you already did because I don't see more errors after 31 July)

These changes make the `productIdMatches` method more robust which is good, but I bet that when trying to save a subscription with sku = null, it will fail in another part of the logic. 

Therefore, apart of making the method `productIdMatches` more robust as you already did, it's also needed to update the `extractSku` method from [here](https://github.com/RedHatInsights/rhsm-subscriptions/blob/5bf0182af12c32b1ac7a8f992c26132849f3ba20/swatch-contracts/src/main/java/com/redhat/swatch/contract/utils/SubscriptionDtoUtil.java#L48) to filter out sku that are empty or null.

After doing this change, it will fail with the expected exception: https://github.com/RedHatInsights/rhsm-subscriptions/blob/5bf0182af12c32b1ac7a8f992c26132849f3ba20/swatch-contracts/src/main/java/com/redhat/swatch/contract/utils/SubscriptionDtoUtil.java#L61

2024-08-08 12:59 UTC, barnabycourt commented
/retest

2024-08-09 05:14 UTC, Sgitario approved these changes
lgtm

2024-08-09 12:09 UTC, barnabycourt commented
/retest

2024-08-12 17:36 UTC, wottop commented
/retest

2024-08-13 13:17 UTC, ntkathole approved these changes
Looks good!

2024-08-13 14:34 UTC, merged