Use fully qualified names for parameterized tests
RedHatInsights/rhsm-subscriptions pull request #361
Opened 2021-03-23 19:45 UTC by awood

The default test name for a parameterized test is just the index number
and the arguments which does not actually tell you which specific test
method is being run.  The reasoning behind this is that test runners are
expected to print the test method name and then underneath in a
tree-like fashion, print the individual instances of that test.  Our
test runner doesn't follow this behavior making it difficult to tell
what method generated a particular parameterized test.  This patch
corrects the issue by mandating a more verbose name.

2021-03-26 13:12 UTC, mstead requested changes
I love the concept here, but something isn't lining up for me.

Testing your changes out on the CLI I get:
```
org.candlepin.subscriptions.db.HostRepositoryTest

  Test canSortByHostBasedSortMethods(String) REDHAT_PWNS PASSED
  Test canSortByHostBasedSortMethods(String) REDHAT_PWNS PASSED
  Test canSortByHostBasedSortMethods(String) REDHAT_PWNS PASSED
  Test canSortByHostBasedSortMethods(String) REDHAT_PWNS PASSED
  Test canSortByHostBasedSortMethods(String) REDHAT_PWNS PASSED
  Test canSortByHostBasedSortMethods(String) REDHAT_PWNS PASSED
```

Testing on develop I get:
```
org.candlepin.subscriptions.db.HostRepositoryTest

  Test [1] sort=host.displayName PASSED
  Test [2] sort=cores PASSED
  Test [3] sort=host.hardwareType PASSED
  Test [4] sort=sockets PASSED
  Test [5] sort=host.lastSeen PASSED
  Test [6] sort=measurementType PASSED
```

I think this PR needs something else. I feel like I want a mix of both.

```canSortByHostBasedSortMethods(String)  sort=host.displayName PASSED```

Can we achieve this somehow? Is there a way that we can make this easier to apply without having to remember the format or go copy-paste it?

2021-04-06 17:31 UTC, awood commented
> I think this PR needs something else. I feel like I want a mix of both.

The reason I wrote this is because in the IDE, the current format is not helpful:

![Selection_008](https://user-images.githubusercontent.com/17975/113753602-420c3580-96dc-11eb-8b69-c3896ccb8c03.png)

You can't even tell what the top level test is.  I didn't realize it printed the tree format correcting on the CLI.  I'll see about if I can split the difference.

2021-04-07 03:05 UTC, awood commented
I am going to close this.  The problem is actually with Gradle!  It's being tracked at https://github.com/gradle/gradle/issues/5975  Essentially, running the unit tests through Gradle in IntelliJ lops off the portion of the test tree that tells you what method a parameterized test derived from.  Running the unit test through JUnit in IntelliJ and everything is fine.

So the quick work around is just to create a "Run All Tests" run configuration that uses the JUnit run configuration.  As you can see from the screenshot, the test tree is constructed and you can actually tell what unit test a failing parameterized test belongs too.  Easy enough hack for a fairly uncommon problem.  Hopefully Gradle will fix the issue soon anyway.

In the meantime, we could probably remove the names that are already applied to some of the parameterized tests.

![Selection_009](https://user-images.githubusercontent.com/17975/113804259-347e9c00-972c-11eb-96f0-5fad6558a5b5.png)

2021-04-07 03:07 UTC, closed without merging

2021-04-07 03:13 UTC, awood commented
> Testing your changes out on the CLI I get:
> 
> ```
> org.candlepin.subscriptions.db.HostRepositoryTest
> 
>   Test canSortByHostBasedSortMethods(String) REDHAT_PWNS PASSED
>   Test canSortByHostBasedSortMethods(String) REDHAT_PWNS PASSED
>   Test canSortByHostBasedSortMethods(String) REDHAT_PWNS PASSED
>   Test canSortByHostBasedSortMethods(String) REDHAT_PWNS PASSED
>   Test canSortByHostBasedSortMethods(String) REDHAT_PWNS PASSED
>   Test canSortByHostBasedSortMethods(String) REDHAT_PWNS PASSED
> ```

P.S. @mstead How did you invoke Gradle here?  When I run `./gradlew :test --tests "HostRepositoryTest"` my results look like

```
  Test testReturnsGuestsOfHypervisor() PASSED                                                                                                                    
  Test testFindHostsWhenUsageIsDifferent() PASSED                                                                                                                
  Test testShouldFilterSockets() PASSED                                                                                                                          
  Test testFindHostsWhenAccountIsDifferent() PASSED                                                                                                              
  Test [1] displayNameSubstring=, expectedResults=3 PASSED                                                                                                       
  Test [2] displayNameSubstring=banana, expectedResults=1 PASSED
  Test [3] displayNameSubstring=rang, expectedResults=1 PASSED
  Test [4] displayNameSubstring=an, expectedResults=2 PASSED
  Test [5] displayNameSubstring=celery, expectedResults=0 PASSED
...
```

and the actual name of the parameterized test, `testDisplayNameFilter` is nowhere to be found.  

It'd be nice to have it display properly on the CLI too. :rofl: