Lburnett/sub id collector ent 3341
RedHatInsights/rhsm-subscriptions pull request #369
Opened 2021-03-25 18:42 UTC by lindseyburnett

2021-04-08 02:54 UTC, kahowell requested changes
A few small-ish requests:

- [ ] please go ahead and move the subscription properties to application.yaml since they'll be used in more than one place.
- [ ] subscription url will need `https` rather than http
- [ ] we should go ahead and name the stub property `SUBSCRIPTION_USE_STUB` for consistency
- [ ] we need template updates for the SUBSCRIPTION_HOST, SUBSCRIPTION_PORT properties as well as the keystore and truststore properties (I prefer re-using `RHSM_KEYSTORE`/`RHSM_KEYSTORE_PASSWORD` for this). Good references would be the way these are handled in `templates/rhsm-conduit.yaml`... Looking at this, I'm realizing we might need to do a small bit of work to get the proper truststore set up. WIll also be needed in #389, so I will swarm this with you.
- [ ] we should remove the DUMMY ID stuff (or at least make it a dev-only kind of thing)

And a quick note for anyone else reviewing, this requires data in the offering table to test:

```sql
insert into offering(sku, product_name, role, sla, usage) values ('MW00210HR', 'OpenShift Container Platform', 'ocp', 'Premium', 'Production');
insert into offering(sku, product_name, role, sla, usage) values ('MW01370', 'OpenShift Dedicated', 'osd', 'Premium', 'Production');
```
FWIW, I'm using instructions for #350 otherwise to test along with

```
DEV_MODE=true \
  RHSM_KEYSTORE=$RHSM_KEYSTORE \
  RHSM_KEYSTORE_PASSWORD=$RHSM_KEYSTORE_PASSWORD \
  RHSM_TRUSTSTORE=$RHSM_TRUSTSTORE \
  RHSM_TRUSTSTORE_PASSWORD=$RHSM_TRUSTSTORE_PASSWORD \
  SUBSCRIPTION_HOST=subscription.qa.api.redhat.com \
  SUBSCRIPTION_PORT=443 \
  SUBSCRIPTION_USE_STUB=false \
  ./gradlew bootRun
```

May have a touch more feedback tomorrow, but wanted to go ahead and get the bulk of it to you.

2021-04-08 02:54 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceSubscriptionCollector.java
> +            return Collections.emptyList();
I'd rather throw an exception here.

2021-04-08 14:02 UTC, lindseyburnett commented
@kahowell, pushed some updates.  It addresses your feedback **except** for

- truststore changes
- dummy id stuff

Also, I added a retryTemplate to the SubscriptionService if you could check that out too.

Thanks!

2021-04-08 19:40 UTC, dmckoske requested changes

2021-04-09 15:34 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceSubscriptionCollector.java
> +    private static final String IBMMARKETPLACE = "ibmmarketplace";
Having it as a constant here is fine. Let's avoid the anti-pattern of a separate constants file (e.g. see https://www.baeldung.com/java-constants-good-practices#2-a-large-global-constants-class for rationale on why that's a bad practice)

2021-04-09 15:41 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/subscription/SubscriptionService.java
> +
The way the service functions is that if you ask for a page that doesn't exist, you get an empty list, so when result count is 0, you're done. Actually, we could avoid some unneeded calls by changing the condition (we also know we're done if the list we got back isn't our page size):

```java
        } while (latestResultCount == pageSize);
```

2021-04-09 20:43 UTC, kahowell requested changes

2021-04-09 20:43 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
> +        "o.role IN :#{#roles}) AND s.startDate > :rangeStart AND s.endDate < :rangeEnd AND " +
```suggestion
        "o.role IN :#{#roles}) AND s.startDate <= :rangeStart AND s.endDate >= :rangeEnd AND " +
```
Subscription needs to start before the usage can be reported against, and it must end after the usage period end.

2021-04-09 20:43 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/subscription/SubscriptionServiceProperties.java
> +public class SubscriptionServiceProperties {
Can you please extend org.candlepin.subscriptions.http.HttpClientProperties ? Then you can just use without a qualifier in org.candlepin.subscriptions.subscription.SubscriptionServiceConfiguration and intellij won't get confused about whether rhsm-subscriptions.subscription refers to SubscriptionServiceProperties or HttpClientProperties (cause it'll naturally be both :smile:).

IOW, after you do this, we won't need to have any mention of HttpClientProperties in SubscriptionServiceConfiguration.

2021-04-09 20:43 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/marketplace/MarketplacePayloadMapper.java
> +        }).collect(Collectors.toList());
Let's not do this. When all the other bits are sorted out (mainly the billing_type bits) we shouldn't be receiving data for non-Premium or non-Production usage, and if something is wrong and we do receive that data, it'd be best to be alerted about it. Additionally, future requirements may introduce non-Premium or non-Production PAYG.

2021-04-09 20:43 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/subscription/SubscriptionServiceProperties.java
> +    private long backOffInitialInterval = 1000L;
Can you please define these two in the application.yaml? Also, I prefer using `Duration` for the backOffInitialInterval.

2021-04-09 20:43 UTC, kahowell commented on src/main/resources/application.yaml
> +    useStub: ${SUBSCRIPTION_USE_STUB:true}
Can you please default this to false (for consistency)?

2021-04-09 20:43 UTC, kahowell commented on src/main/resources/application.yaml
> +    maxConnections: ${SUBSCRIPTION_MAX_CONNECTIONS:100}
Can you please populate these env vars in `templates/marketplace-worker.yaml`. They should replace `MARKETPLACE_DUMMY_ID`?

For populating `SUBSCRIPTION_KEYSTORE` and `SUBSCRIPTION_KEYSTORE_PASSWORD`, `templates/rhsm-conduit.yaml` -> `RHSM_KEYSTORE`, etc. is a good reference (we will use the same secret).

2021-04-12 20:58 UTC, kahowell approved these changes

2021-04-12 20:58 UTC, merged