SWATCH-2887: Remove optimistic locking for host tally buckets
RedHatInsights/rhsm-subscriptions pull request #3766
Opened 2024-09-19 10:56 UTC by Sgitario

Jira issue: SWATCH-2887

## Description
After the refactor of the event ingestion, we are handling events in batches ordered only by record date. 

Then, when we handle the events for the same host and the buckets need to be either updated/added/deleted in different transactions, hibernate throws an exception because the bucket version to update or delete does not match with the expected (the bucket version has been updated in other transaction).

We could refactor the event ingestion by grouping the events by host or perform a logical delete for the tally buckets, though these changes might have side effects in performance and other parts of the backend, so it might need more investigation. 

For the time being, I think the best approach is to remove the optimistic locking to unblock production and taking into account that this will cause a performance penalty when updating the buckets (because hibernate will do a select statement before updating).

## Testing
Added test to reproduce the issue.

2024-09-19 11:01 UTC, Sgitario commented
@kahowell adding you as reviewer as you have some context about the changes.
To sum up, I think the best quick fix to unblock production is to drop the version column in the entity. Indeed, this will cause a performance penalty with an extra select when updating/inserting the buckets, though I don't think it will be very notorious since these entities are indexed.

For a long term fix, I think the way to go is to logically delete the buckets instead of perform delete statements, we'll always perform update statements that will populate the version accordignly. If you're ok with these changes, I will open a follow-up JIRA ticket for this and also to add back the version column to configure the optimistic locking.

2024-09-19 12:51 UTC, barnabycourt commented
This needs review by the performance team before merge

2024-09-19 18:27 UTC, kahowell requested changes
> We could refactor the event ingestion by grouping the events by host or perform a logical delete for the tally buckets, though these changes might have side effects in performance and other parts of the backend, so it might need more investigation.

I thought about this a bit and I think there's a solution that's similar to logical deletion, but doesn't have the same risk of negative performance impacts:

1. Add a field named `stale` to the `HostTallyBucket` class (default `false`). Make this field transient (it doesn't need to be persisted).
2. When processing events, mark the bucket as stale rather than removing it from the collection.
3. When adding buckets, if there is an existing stale bucket, change the value of `stale` to `false`.
4. After all events have been processed, remove all `stale=true` buckets from hosts in the batch.

I'd rather implement the above than remove optimistic locking.

2024-09-20 05:29 UTC, Sgitario commented
> 4. After all events have been processed, remove all `stale=true` buckets from hosts in the batch.

Unfortunately, this is happening because hosts might have in different batches and hence be updated in different transactions, so deleting the stale buckets after each batch would have the same issue.

2024-09-20 08:36 UTC, Sgitario commented
@kahowell solution updated according to your feedback. 
I confirmed that it works by running the implemented test case, and also using the prod data that I initially used to reproduce the issue.

2024-09-20 14:49 UTC, kahowell approved these changes

2024-09-23 06:12 UTC, Sgitario commented
/retest

2024-09-23 16:05 UTC, merged