SWATCH-2995 Retry billable usage when it gets marketplace retry error
RedHatInsights/rhsm-subscriptions pull request #3822
Opened 2024-10-02 16:25 UTC by kartikshahc

Jira issue: SWATCH-XXXX

## Description

## Testing

IQE Test MR: 

### Setup

1.
1.

### Steps

1.
1.

### Verification

1.
1.

2024-10-03 04:49 UTC, Sgitario requested changes
We should contact the AWS support time to know more about what is our current quota: https://repost.aws/knowledge-center/ssm-parameter-store-rate-exceeded and/or to request an increase.

Also, if one call fails for this reason, it's probably that the following immediate calls fail for the same reason, so if we know the API rate, we could either delay these API cals or fail fast or implement another mecanism.

Finally, I'm missing a test case to cover these changes.

2024-10-03 15:27 UTC, kartikshahc commented
> We should contact the AWS support time to know more about what is our current quota: https://repost.aws/knowledge-center/ssm-parameter-store-rate-exceeded and/or to request an increase.
> 
> Also, if one call fails for this reason, it's probably that the following immediate calls fail for the same reason, so if we know the API rate, we could either delay these API cals or fail fast or implement another mecanism.
> I had a similar discussion with the team in the Slack channel, but it appears that this issue originates from the AWS side. Typically, we don’t send more than one usage. I would like to get @kahowell  opinion on this, but for now, we can limit the scope of this card to the fix that has already been implemented. Thoughts?

> Finally, I'm missing a test case to cover these changes.
I am working on the unit test

2024-10-03 19:34 UTC, kartikshahc commented
The code is ready for QE and DEV review. As mentioned above there are some open questions but, that can be done in next cards.

2024-10-03 19:46 UTC, kartikshahc commented
> We should contact the AWS support time to know more about what is our current quota: https://repost.aws/knowledge-center/ssm-parameter-store-rate-exceeded and/or to request an increase.
> 
> Also, if one call fails for this reason, it's probably that the following immediate calls fail for the same reason, so if we know the API rate, we could either delay these API cals or fail fast or implement another mecanism.

I had a similar discussion with the team in the Slack channel yesterday, but it appears that this issue originates from the AWS side. Typically, we don’t send more than one usage at a time. I would like to get @kahowell opinion on this, but for now, we can limit the scope of this card to the fix that has already been implemented. Also I don't know whom to contact on AWS side and with what details since I don't have customer id or anything else to create a support ticket. Not sure if the vault contains these details. 
One more thing with regard to this code, I do not anticipate that we will encounter the same issue since we attempt to retry the MARKETPLACE_RATE_LIMIT error code tuple in the remittance record in the next hour similar to what we do for subscription_not_found.
Thoughts?
 
> Finally, I'm missing a test case to cover these changes.

Done

The code is ready for QE and DEV review. As mentioned above there are some open questions but, that can be done in next cards.

2024-10-04 05:40 UTC, Sgitario approved these changes

2024-10-04 15:48 UTC, kartikshahc commented
/retest

2024-10-07 19:12 UTC, TrayvonMcKnight commented
/retest

2024-10-07 20:37 UTC, TrayvonMcKnight approved these changes
IQE MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/901

2024-10-08 13:00 UTC, merged