SWATCH-3177 Fix invalid remittance calculation when an amendment is applied
RedHatInsights/rhsm-subscriptions pull request #4033
Opened 2024-12-10 18:44 UTC by mstead

Jira issue: SWATCH-3177

## Description
This bug happens when the incoming events are in conflict (2 events with the same instance, metric and timestamp) and the hardware measurement type (HMT) is different. In the case of the reproducer events, the rhelemeter event does not specify the HMT which will get defaulted to PHYSICAL, not AWS. Since remittance uses the HMT to determine the current total remittance, it returns an incorrect value for the total when the usage for the second event is received.

This only happens when a conflict occurs and the value changes, since the measurements for the hour are replaced when tallied.

## Resolution
When determining the current remittance total, the billable usage
component no longer considers the hardware_measurement_type. As
such, when TallySummary messages are created during the hourly tally,
we must also exclude the measurement type when calculating the
current total for a metric, as this value is used when determining
remittance.

This PR also removes the hardware measurement type from billable usage
and remittance since it does not apply to remittance in general.

## Affected Components
1. swatch-billable-usage
  * The currentTotal of TallySummary.TallyMeasurement are now calculated to not include the hardware_type.
  * The billable_usage_remittance table no longer has the hardware_measurement_type.
2. All Swatch Billing Producers
  * Incoming BillableUsage messages no longer have the hardwareMeasurementType included.
  
## Testing
IQE Test MR: [IQE TEST](https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/759/diffs#5778b0b64554323fc857787e871cbb411a26d9f9_368_372)

### Steps

#### Deployment Tips
**When testing locally, I deployed the following services. Please read the test steps carefully, since the first deployment should be done on the MAIN branch.**

swatch-contracts
```
QUARKUS_MANAGEMENT_ENABLED=false SERVER_PORT=8001 ./gradlew :swatch-contracts:quarkusDev
```
swatch-billable-usage
```
SERVER_PORT=8002 QUARKUS_MANAGEMENT_PORT=9004 DEV_MODE=true ./gradlew :swatch-billable-usage:quarkusDev
```

swatch-tally
```
SPRING_PROFILES_ACTIVE=api,worker,kafka-queue DEV_MODE=true ./gradlew clean :bootRun
```

#### Testing
First, reproduce the bug on the **MAIN** branch.

Create a cost-management event for a host instance that includes the hardware_type.
```
http :9080/topics/platform.rhsm-subscriptions.service-instance-ingress Content-Type:application/vnd.kafka.json.v2+json Accept:application/vnd.kafka.v2+json --raw '{
        "records": [
          {
            "key": "3340851",
            "value": {
              "service_type": "RHEL System",
              "timestamp": "2024-06-03T14:00:00Z",
              "expiration": "2024-07-03T15:00:00Z",
              "display_name": "automation__cluster_testHostgge",
              "measurements": [
                {
                  "value": 4,
                  "uom": "vCPUs",
                  "metric_id": "vCPUs"
                }
              ],
              "product_ids": [
                "204"
              ],
              "cloud_provider": "AWS",
              "hardware_type": "Cloud",
              "sla": "Premium",
              "usage": "Production",
              "billing_provider": "aws",
              "billing_account_id": "testkfk",
              "product_tag": [
                "rhel-for-x86-els-payg-addon"
              ],
              "conversion": false,
              "event_source": "cost-management",
              "event_type": "vCPUs",
              "org_id": "3340851",
              "instance_id": "testHostgge"
            }
          }
        ]
      }
	  '
```

Perform an hourly tally for the org.
```
http POST ":8000/api/rhsm-subscriptions/v1/internal/tally/hourly?org=3340851" x-rh-swatch-psk:placeholder
```

Verify 4 AWS vCPUs were remitted.
```
select * from billable_usage_remittance where org_id='3340851';
```

Create a rhelemeter style event for the **SAME HOST** (no cloud_provider or hardware type). 
```
http :9080/topics/platform.rhsm-subscriptions.service-instance-ingress Content-Type:application/vnd.kafka.json.v2+json Accept:application/vnd.kafka.v2+json --raw '{
        "records": [
          {
            "key": "3340851",
            "value": {
              "service_type": "RHEL System",
              "timestamp": "2024-06-03T14:00:00Z",
              "expiration": "2024-07-03T15:00:00Z",
              "display_name": "automation__cluster_testHostgge",
              "measurements": [
                {
                  "value": 8,
                  "uom": "vCPUs",
                  "metric_id": "vCPUs"
                }
              ],
              "product_ids": [
                "204"
              ],
              "sla": "Premium",
              "usage": "Production",
              "billing_provider": "aws",
              "billing_account_id": "testkfk",
              "product_tag": [
                "rhel-for-x86-els-payg-addon"
              ],
              "conversion": false,
              "event_source": "rhelemeter",
              "event_type": "vCPUs",
              "org_id": "3340851",
              "instance_id": "testHostgge"
            }
          }
        ]
      }
	  '
```

Run an hourly tally for the org.
```
http POST ":8000/api/rhsm-subscriptions/v1/internal/tally/hourly?org=3340851" x-rh-swatch-psk:placeholder
```

Because the event should have been amended (**4 - 4**) + 8, the expected billable usage should have been and additional 4 vCPUs since we already billed for 4 (from the first event). HOWEVER, you'll notice that there were 8 additional vCPUs billed due to the PHYSICAL hardware measurement type. We have overbilled by 4 vCPUs.
```
select * from billable_usage_remittance where org_id='3340851';
```

Check out the branch with the bug fix and deploy. After deploying, check the **billable_usage_remittance** table to make sure that the **hardware_measurement_type** column was dropped.

Next verify that we will recover correctly from the 4 additional vCPUs that we previously billed for.

```
http :9080/topics/platform.rhsm-subscriptions.service-instance-ingress Content-Type:application/vnd.kafka.json.v2+json Accept:application/vnd.kafka.v2+json --raw '{
        "records": [
          {
            "key": "3340851",
            "value": {
              "service_type": "RHEL System",
              "timestamp": "2024-06-03T15:00:00Z",
              "expiration": "2024-07-03T15:00:00Z",
              "display_name": "automation__cluster_testHostgge",
              "measurements": [
                {
                  "value": 10,
                  "uom": "vCPUs",
                  "metric_id": "vCPUs"
                }
              ],
              "product_ids": [
                "204"
              ],
              "cloud_provider": "AWS",
              "hardware_type": "Cloud",
              "sla": "Premium",
              "usage": "Production",
              "billing_provider": "aws",
              "billing_account_id": "testkfk",
              "product_tag": [
                "rhel-for-x86-els-payg-addon"
              ],
              "conversion": false,
              "event_source": "cost-management",
              "event_type": "vCPUs",
              "org_id": "3340851",
              "instance_id": "testHostgge"
            }
          }
        ]
      }
	  '
```

Perform an hourly tally for the org.
```
http POST ":8000/api/rhsm-subscriptions/v1/internal/tally/hourly?org=3340851" x-rh-swatch-psk:placeholder
```

Since an additional 10 vCPUs were reported in the event we just sent, and we've previously overbilled for 4 vCPUs due to the bug, after the tally we should see that we billed for **6 vCPUs**.

Next, attempt to reproduce the bug scenario **WITH A DIFFERENT MONTH** to ensure the bug is addressed when starting fresh.

Create a cost-management event for a host instance that includes the hardware_type.
```
http :9080/topics/platform.rhsm-subscr [...]

2024-12-11 20:44 UTC, liwalker-rh commented
/retest

2024-12-12 15:25 UTC, Aurobinda55 commented
/retest

2024-12-12 20:33 UTC, kflahert commented
/retest

2024-12-13 15:22 UTC, Aurobinda55 commented
Verification steps :

**On the main branch** 

- Deployed EE, 
- Created a rhel-payg-addon event with event source cost management, value =2,instance-uuid='rhel_instance',billing_account_id='test-123'
- sync hourly tally
- Again, created another rhel-payg-addon event with event source=rhelemeter , value =7,instance-uuid='rhel_instance',billing_account_id='test-123', timestamp=same as above
- sync hourly tally
- conflicts happened(verified)
- Checked the remittance record and it showed two records,
```
  Out[27]: 
[{'orgId': '3340851',
  'productId': 'rhel-for-x86-els-payg-addon',
  'metricId': 'vCPUs',
  'billingProvider': 'aws',
  'billingAccountId': 'test-123',
  'remittedValue': 2.0,
  'accumulationPeriod': '2024-12',
  'remittanceDate': '2024-12-13T13:23:55.771941Z',
  'remittanceStatus': 'succeeded',
  'remittanceErrorCode': 'null'},
 {'orgId': '3340851',
  'productId': 'rhel-for-x86-els-payg-addon',
  'metricId': 'vCPUs',
  'billingProvider': 'aws',
  'billingAccountId': 'test-123',
  'remittedValue': 7.0,
  'accumulationPeriod': '2024-12',
  'remittanceDate': '2024-12-13T13:25:43.53135Z',
  'remittanceStatus': 'pending',
  'remittanceErrorCode': 'null'}]
```
Also, I checked the billable usage message has hardware type=AWS/Cloud

**Switched to the PR branch and deployed the PR image** 

- Created one more events with event source =cost-management, timestampe=same as previous event, value=15,instance-id=same as previous
- sync tally hourly 
- Conflict happened 
- Fetched the remittance records 
- Verified hardware measurement type removed from the existing record and new record
- There are two records in the remittance table, 1st record with remitted value 6, status Pending
- 2nd record with value 9 status succeeded 
```
[{'orgId': '3340851',
  'productId': 'rhel-for-x86-els-payg-addon',
  'metricId': 'vCPUs',
  'billingProvider': 'aws',
  'billingAccountId': 'test-123',
  'remittedValue': 6.0,
  'accumulationPeriod': '2024-12',
  'remittanceDate': '2024-12-13T13:49:05.750887Z',
  'remittanceStatus': 'pending',
  'remittanceErrorCode': 'null'},
 {'orgId': '3340851',
  'productId': 'rhel-for-x86-els-payg-addon',
  'metricId': 'vCPUs',
  'billingProvider': 'aws',
  'billingAccountId': 'test-123',
  'remittedValue': 9.0,
  'accumulationPeriod': '2024-12',
  'remittanceDate': '2024-12-13T13:25:43.53135Z',
  'remittanceStatus': 'succeeded',
  'remittanceErrorCode': 'null'}]
```
@mstead I think this is expected here because already 9 were sent(due to the bug in the main branch), and now 15, so 15-9=6 in the pending state? but need your confirmation here .

- Again, Created one more event with event source=rhelemeter, timestampe=same as previous event, instanc-id=same as previous, value=2
- sync tally hourly 
- Fetch remittance record 
- Now, I see one record status =succeeded, with a value of 15 and the latest value of 2 ignored
```
[{'orgId': '3340851',
  'productId': 'rhel-for-x86-els-payg-addon',
  'metricId': 'vCPUs',
  'billingProvider': 'aws',
  'billingAccountId': 'test-123',
  'remittedValue': 15.0,
  'accumulationPeriod': '2024-12',
  'remittanceDate': '2024-12-13T13:49:05.750887Z',
  'remittanceStatus': 'succeeded',
  'remittanceErrorCode': 'null'}]
```
**Now checked for the previous month's scenario** 

- Created two events having event source= cost-management, rhelmeter, same timestamp, same instance id, value 2 and 7 for each event
- sync hourly tally 
- Now I see, two records in the remittance table 1st record value=5 pending 2nd record value=2 status=succeeded
 ```
{
        "accumulationPeriod": "2024-11",
        "billingAccountId": "test-123",
        "billingProvider": "aws",
        "metricId": "vCPUs",
        "orgId": "3340851",
        "productId": "rhel-for-x86-els-payg-addon",
        "remittanceDate": "2024-12-13T14:32:09.255147Z",
        "remittanceErrorCode": "null",
        "remittanceStatus": "pending",
        "remittedValue": 5.0
    },
    {
        "accumulationPeriod": "2024-11",
        "billingAccountId": "test-123",
        "billingProvider": "aws",
        "metricId": "vCPUs",
        "orgId": "3340851",
        "productId": "rhel-for-x86-els-payg-addon",
        "remittanceDate": "2024-12-13T14:28:10.887495Z",
        "remittanceErrorCode": "null",
        "remittanceStatus": "succeeded",
        "remittedValue": 2.0
    },
```
@mstead I think this is expected here, because the latest value 7 adjusted with the first event value which is 2 ?
Also checked, the remittance records have no HMT , 

```
account_number          | 
org_id                  | 3340851
product_id              | rhel-for-x86-els-payg-addon
metric_id               | vCPUs
accumulation_period     | 2024-11
sla                     | Premium
usage                   | Production
billing_provider        | aws
billing_account_id      | test-123
remitted_pending_value  | 2
remittance_pending_date | 2024-12-13 14:28:10.887495+00
retry_after             | 
tally_id                | 8adf1a76-ae29-4a46-817a-61d7bd034ff5
uuid                    | 3faadcbb-8789-4e64-8c80-1c7b64b8a4be
billed_on               | 2024-12-13 14:32:09.412855+00
error_code              | 
status                  | succeeded
 
```
Checked on the swatch-billable-usage-service and can't see the HMT in the message.

2024-12-13 15:43 UTC, mstead commented
> @mstead I think this is expected here because already 9 were sent(due to the bug in the main branch), and now 15, so 15-9=6 in the pending state? but need your confirmation here .

Yes, that is correct.

> @mstead I think this is expected here, because the latest value 7 adjusted with the first event value which is 2 ?

Yes, this is also correct.

2024-12-16 15:00 UTC, Aurobinda55 commented
/retest

2024-12-16 16:03 UTC, Aurobinda55 commented
There are two failed tests in this PR due to the **hardware_measurement_type** column, which is removed in this PR. I see there is already a PR on the IQE side to handle the changes https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/commit/05ba352f615b7a3254eb39e02fcc81f44e099292, but due to some issue while releasing the tag in iqe-rhsm plugin(https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/tags/v2024.12.16.0) the ci job is not able to pull the latest image and failed with the same error. I am currently working on it.

2024-12-16 16:35 UTC, wottop commented
lgtm, but I would like to have another person approve the logic.

2024-12-17 09:30 UTC, Aurobinda55 commented
@mstead I see a minor issue in the tally report. The tally always shows the value of the first event, regardless of any deductions made during conflict resolution. Could you please confirm, if this is expected for below two cases?

Case-1: (When metric value of 1st event < metric value)

**Events** 
```
[{'event_source': 'cost-management',
  'event_type': 'vCPUs',
  'org_id': '3340851',
  'instance_id': 'testHostwqs',
  'event_id': 'afe2ebaf-44ea-456a-a034-963fff0713f8',
  'service_type': 'RHEL System',
  'timestamp': '2024-12-17T07:00:00Z',
  'record_date': '2024-12-17T08:54:35.501643825Z',
  'expiration': '2024-12-17T08:00:00Z',
  'display_name': 'automation__cluster_testHostwqs',
  'measurements': [{'value': 11.0, 'metric_id': 'vCPUs'}],
  'cloud_provider': 'AWS',
  'hardware_type': 'Cloud',
  'product_ids': ['204'],
  'sla': 'Premium',
  'usage': 'Production',
  'billing_provider': 'aws',
  'billing_account_id': 'testhfk',
  'product_tag': ['rhel-for-x86-els-payg-addon'],
  'conversion': False},
 {'event_source': 'cost-management',
  'event_type': 'vCPUs',
  'org_id': '3340851',
  'instance_id': 'testHostwqs',
  'event_id': 'e52ad17c-1e0f-4f50-aff8-009b37d8e388',
  'service_type': 'RHEL System',
  'timestamp': '2024-12-17T07:00:00Z',
  'record_date': '2024-12-17T08:54:50.531083343Z',
  'expiration': '2024-12-17T08:00:00Z',
  'display_name': 'automation__cluster_testHostwqs',
  'measurements': [{'value': -11.0, 'metric_id': 'vCPUs'}],
  'cloud_provider': 'AWS',
  'hardware_type': 'Cloud',
  'product_ids': ['204'],
  'sla': 'Premium',
  'usage': 'Production',
  'billing_provider': 'aws',
  'billing_account_id': 'testhfk',
  'product_tag': ['rhel-for-x86-els-payg-addon'],
  'amendment_type': 'deduction',
  'conversion': False},
 {'event_source': 'rhelemeter',
  'event_type': 'vCPUs',
  'org_id': '3340851',
  'instance_id': 'testHostwqs',
  'event_id': '4b9e12ea-a52b-4d27-8b7c-fdf3641a35d8',
  'service_type': 'RHEL System',
  'timestamp': '2024-12-17T07:00:00Z',
  'record_date': '2024-12-17T08:54:50.531652772Z',
  'expiration': '2024-12-17T08:00:00Z',
  'display_name': 'automation__cluster_testHostwqs',
  'measurements': [{'value': 8.0, 'metric_id': 'vCPUs'}],
  'product_ids': ['204'],
  'sla': 'Premium',
  'billing_provider': 'aws',
  'billing_account_id': 'testhfk',
  'product_tag': ['rhel-for-x86-els-payg-addon'],
  'conversion': False}]
```

**Tally**
```
In [22]: app.rhsm_subscriptions.get_today_tally_report(product_id=product_id,metric_id=metric)
2024-12-17 09:00:15.997 [    INFO] [iqe.base.rest_client] REST: GET http://swatch-api-service.ephemeral-lssrqf.svc:8000/api/rhsm-subscriptions/v1/tally/products/rhel-for-x86-els-payg-addon/vCPUs with query params [('granularity', 'Daily'), ('beginning', '2024-12-16T08:13:20.784394+00:00'), ('ending', '2024-12-17T09:00:15.982253+00:00')] and x-rh-insights-request-id=None
2024-12-17 09:00:15.998 [    INFO] [root] {'date': datetime.datetime(2024, 12, 17, 0, 0, tzinfo=tzlocal()),
 'has_data': True,
 'value': 11}
Out[22]: 
{'date': datetime.datetime(2024, 12, 17, 0, 0, tzinfo=tzlocal()),
 'value': 11,
 'has_data': True}
```
Case-2: (When metric value of 1st event < metric value)

**Events**

```
[{'event_source': 'cost-management',
  'event_type': 'vCPUs',
  'org_id': '3340851',
  'instance_id': 'testHostxxw',
  'event_id': '21e524eb-9254-4871-8034-7fe1baa63ec2',
  'service_type': 'RHEL System',
  'timestamp': '2024-12-17T08:00:00Z',
  'record_date': '2024-12-17T09:14:39.855647069Z',
  'expiration': '2024-12-17T09:00:00Z',
  'display_name': 'automation__cluster_testHostxxw',
  'measurements': [{'value': 7.0, 'metric_id': 'vCPUs'}],
  'cloud_provider': 'AWS',
  'hardware_type': 'Cloud',
  'product_ids': ['204'],
  'sla': 'Premium',
  'usage': 'Production',
  'billing_provider': 'aws',
  'billing_account_id': 'testbhg',
  'product_tag': ['rhel-for-x86-els-payg-addon'],
  'conversion': False},
 {'event_source': 'cost-management',
  'event_type': 'vCPUs',
  'org_id': '3340851',
  'instance_id': 'testHostxxw',
  'event_id': '9bc3135a-d215-4f99-b2b7-c255fc247325',
  'service_type': 'RHEL System',
  'timestamp': '2024-12-17T08:00:00Z',
  'record_date': '2024-12-17T09:14:54.891640685Z',
  'expiration': '2024-12-17T09:00:00Z',
  'display_name': 'automation__cluster_testHostxxw',
  'measurements': [{'value': -7.0, 'metric_id': 'vCPUs'}],
  'cloud_provider': 'AWS',
  'hardware_type': 'Cloud',
  'product_ids': ['204'],
  'sla': 'Premium',
  'usage': 'Production',
  'billing_provider': 'aws',
  'billing_account_id': 'testbhg',
  'product_tag': ['rhel-for-x86-els-payg-addon'],
  'amendment_type': 'deduction',
  'conversion': False},
 {'event_source': 'rhelemeter',
  'event_type': 'vCPUs',
  'org_id': '3340851',
  'instance_id': 'testHostxxw',
  'event_id': '390f45b2-6261-4d42-b47e-e4cdaf1f387a',
  'service_type': 'RHEL System',
  'timestamp': '2024-12-17T08:00:00Z',
  'record_date': '2024-12-17T09:14:54.892125545Z',
  'expiration': '2024-12-17T09:00:00Z',
  'display_name': 'automation__cluster_testHostxxw',
  'measurements': [{'value': 10.0, 'metric_id': 'vCPUs'}],
  'product_ids': ['204'],
  'sla': 'Premium',
  'billing_provider': 'aws',
  'billing_account_id': 'testbhg',
  'product_tag': ['rhel-for-x86-els-payg-addon'],
  'conversion': False}]

```
**tally**
```
In [28]: app.rhsm_subscriptions.get_today_tally_report(product_id=product_id,metric_id=metric)
2024-12-17 09:16:25.049 [    INFO] [iqe.base.rest_client] REST: GET http://swatch-api-service.ephemeral-lssrqf.svc:8000/api/rhsm-subscriptions/v1/tally/products/rhel-for-x86-els-payg-addon/vCPUs with query params [('granularity', 'Daily'), ('beginning', '2024-12-16T08:13:20.784394+00:00'), ('ending', '2024-12-17T09:16:25.032694+00:00')] and x-rh-insights-request-id=None
2024-12-17 09:16:25.049 [    INFO] [root] {'date': datetime.datetime(2024, 12, 17, 0, 0, tzinfo=tzlocal()),
 'has_data': True,
 'value': 7}
Out[28]: 
{'date': datetime.datetime(2024, 12, 17, 0, 0, tzinfo=tzlocal()),
 'value': 7,
 'has_data': True}

```

2024-12-17 21:00 UTC, liwalker-rh commented
/retest

2024-12-18 16:41 UTC, liwalker-rh commented
/retest

2024-12-18 19:44 UTC, liwalker-rh commented
These two tests have failed multiple times now in PR checks for this PR:

- test_multiple_tally_summaries_aggregated: https://ci.ext.devshift.net/job/RedHatInsights-rhsm-subscriptions-pr-check/9344/testReport/junit/tests.component.swatch_billable_usage/test_swatch_billable_usage/test_multiple_tally_summaries_aggregated/
- test_multiple_tally_summaries_not_aggregated_for_different_billing_account_ids: https://ci.ext.devshift.net/job/RedHatInsights-rhsm-subscriptions-pr-check/9344/testReport/junit/tests.component.swatch_billable_usage/test_swatch_billable_usage/test_multiple_tally_summaries_not_aggregated_for_different_billing_account_ids/

Is this an issue or is this expected behavior and the tests need to be updated?

2024-12-18 20:21 UTC, liwalker-rh commented
/retest

2024-12-18 21:19 UTC, kflahert commented
@liwalker-rh I just wrote these and I think its some timing issues I need to fix. I'll work on an IQE fix.

2024-12-19 23:07 UTC, liwalker-rh commented
/retest

2024-12-20 13:05 UTC, liwalker-rh commented
/retest

2024-12-20 15:57 UTC, liwalker-rh commented
/retest

2025-01-02 15:37 UTC, liwalker-rh commented
/retest

2025-01-02 17:15 UTC, liwalker-rh commented
/retest

2025-01-03 14:15 UTC, liwalker-rh commented
/retest

2025-01-06 21:27 UTC, liwalker-rh approved these changes
Looks good in testing and the related IQE tests are working as expected. Will merge those tests once this has been merged.

2025-01-07 14:15 UTC, mstead commented
/retest

2025-01-07 15:58 UTC, liwalker-rh commented
/retest

2025-01-08 13:02 UTC, liwalker-rh commented
/retest

2025-01-08 16:05 UTC, lindseyburnett requested changes
Unapproving pending failing test investigation

2025-01-08 17:34 UTC, liwalker-rh commented
/retest

2025-01-08 22:04 UTC, liwalker-rh commented
/retest

2025-01-10 18:42 UTC, mstead commented
/retest

2025-01-16 14:03 UTC, lindseyburnett approved these changes

2025-01-17 10:52 UTC, merged