Sgunta/ent 3823 add subscription number to subscription table
RedHatInsights/rhsm-subscriptions pull request #507
Opened 2021-07-14 18:56 UTC by snehagunta

- add subscription_number to subscription table and subscription entity

2021-07-14 19:32 UTC, redsaz reviewed
LGTM!

2021-07-15 17:41 UTC, lindseyburnett requested changes

2021-07-15 17:41 UTC, lindseyburnett commented on src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacity.java
> +@ToString
We can replace a lot of these annotations with the `@Data` annotation

https://projectlombok.org/features/Data

2021-07-15 18:09 UTC, lindseyburnett approved these changes

2021-07-15 18:09 UTC, merged