Awood/resend tally
RedHatInsights/rhsm-subscriptions pull request #822
Opened 2022-03-22 20:06 UTC by awood

2022-03-23 13:30 UTC, lindseyburnett commented on src/test/java/org/candlepin/subscriptions/validator/UuidValidatorTest.java
> +        "redhat.com"
what about something in a UUID format but has a bunch of special characters that aren't alpha numerical?

2022-03-28 22:46 UTC, kahowell requested changes
This is a bit cumbersome. How about:

1. Separate API spec for tally "service" (what we call worker profile). (We would use separate packages to keep them from clashing for now). - to keep things simple, instead of adding another subproject we can just add another openApiGenerate task into `$buildDir/tally-api` and then add that to `sourceSets.main.java.srcDirs`
2. Resource class for the tally service endpoints only imported in work profile.

Additionally, can you please rename retally to resend? I don't want someone to think this causes recalculation.

2022-03-31 21:10 UTC, awood commented
> This is a bit cumbersome. How about:
> 
>     1. Separate API spec for tally "service" (what we call worker profile). (We would use separate packages to keep them from clashing for now). - to keep things simple, instead of adding another subproject we can just add another openApiGenerate task into `$buildDir/tally-api` and then add that to `sourceSets.main.java.srcDirs`
> 
>     2. Resource class for the tally service endpoints only imported in work profile.
> 
> 
> Additionally, can you please rename retally to resend? I don't want someone to think this causes recalculation.

Updated now.

2022-04-04 15:15 UTC, kahowell requested changes

2022-04-04 15:47 UTC, kahowell approved these changes

2022-04-04 17:31 UTC, merged