Add BillingProducer to worker component
RedHatInsights/rhsm-subscriptions pull request #992
Opened 2022-05-13 17:41 UTC by mstead

* Add secondary listener to tally summary topic.
* Implemented a bare bones BillingProducer class that listens
  to the TallySummary topic and logs that a message was recieved
  and then forwards to new billable usage topic:
     platform.rhsm-subscriptions.billable-usage

## Testing
1. Ensure you have some Events in the DB and take not of the message counts for each topic.
2. Start the app as follows:
```bash
LOGGING_LEVEL_ORG_CANDLEPIN_SUBSCRIPTIONS_TALLY_BILLING=DEBUG SUBSCRIPTION_USE_STUB=true USER_USE_STUB=true DEV_MODE=true  ./gradlew :bootRun
```
3. Run the hourly tally. BE SURE YOU TALLY AROUND THE RANGE THAT HAS EVENTS. The example below should cover any Events in may and force a fresh re-tally.
```bash
curl 'http://localhost:8080/actuator/hawtio/jolokia/' \
-H 'Content-Type: application/json' \
-d '{"type":"exec","mbean":"org.candlepin.subscriptions.jmx:name=tallyJmxBean,type=TallyJmxBean","operation":"tallyAccountByHourly(java.lang.String,java.lang.String,java.lang.String)","arguments":["account123", "2022-05-01T00:00Z", "2022-05-30T00:00Z"]}'
```
4. Verify that you see logs from the RhMarketplaceMapper which means we are still getting TallySummary messages to the RHM consumer (likely subscription not found type messages).
```bash
2022-05-13 16:55:30,704 [thread=rh-marketplace-worker-0-C-1] [ERROR] [org.candlepin.subscriptions.rhmarketplace.RhMarketplacePayloadMapper] - SUBSCRIPTIONS3001: Could not find marketplace subscription id
```

5. Verify that you see DEBUG logs stating that we are getting messages to the secondary TallySummary consumer
```bash
2022-05-13 16:55:30,595 [thread=billing-producer-tally-summary-consumers-0-C-1] [DEBUG] [org.candlepin.subscriptions.tally.billing.TallySummaryMessageConsumer] - Tally Summary recieved. Producing billable usage.}
2022-05-13 16:55:30,595 [thread=billing-producer-tally-summary-consumers-0-C-1] [DEBUG] [org.candlepin.subscriptions.tally.billing.BillingProducer] - Forwarding summary account123 to topic platform.rhsm-subscriptions.billable-usage
```
8. Verify the  platform.rhsm-subscriptions.billable-usage topic exists and has messages waiting to be consumed.

2022-05-17 13:48 UTC, kahowell requested changes
Looks good overall, just looking for s/billingUsage/billableUsage/ in a few places. I think I marked them all, but please sanity check with `git grep -i billingUsage` afterwards.

2022-05-17 13:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducer.java
> + * BillingUsage.
```suggestion
 * BillingUsage.
```
```suggestion
 * BillableUsage.
```

2022-05-17 13:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducer.java
> +  private String billingUsageTopic;
```suggestion
  private String billingUsageTopic;
```
```suggestion
  private String billableUsageTopic;
```

2022-05-17 13:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducer.java
> +      @Qualifier("billingUsageTopicProperties") TaskQueueProperties billingUsageTopicProperties,
```suggestion
      @Qualifier("billingUsageTopicProperties") TaskQueueProperties billingUsageTopicProperties,
```
```suggestion
      @Qualifier("billableUsageTopicProperties") TaskQueueProperties billableUsageTopicProperties,
```

2022-05-17 13:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducer.java
> +    this.billingUsageTopic = billingUsageTopicProperties.getTopic();
```suggestion
      @Qualifier("billableUsageTopicProperties") TaskQueueProperties billableUsageTopicProperties,
      @Qualifier("billableUsageKafkaTemplate")
          KafkaTemplate<String, TallySummary> billableUsageKafkaTemplate) {
    this.billableUsageKafkaTemplate = billableUsageKafkaTemplate;
    this.billableUsageTopic = billableUsageTopicProperties.getTopic();
```

2022-05-17 13:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducer.java
> +    this.billingUsageTopic = billingUsageTopicProperties.getTopic();
```suggestion
      @Qualifier("billableUsageTopicProperties") TaskQueueProperties billableUsageTopicProperties,
      @Qualifier("billableUsageKafkaTemplate")
          KafkaTemplate<String, TallySummary> billableUsageKafkaTemplate) {
    this.billableUsageKafkaTemplate = billableUsageKafkaTemplate;
    this.billableUsageTopic = billableUsageTopicProperties.getTopic();
```

2022-05-17 13:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducer.java
> +  private String billingUsageTopic;
```suggestion
  private KafkaTemplate<String, TallySummary> billableUsageKafkaTemplate;
  private String billableUsageTopic;
```

2022-05-17 13:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducer.java
> +  private String billingUsageTopic;
```suggestion
  private KafkaTemplate<String, TallySummary> billableUsageKafkaTemplate;
  private String billableUsageTopic;
```

2022-05-17 13:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducer.java
> +    billingUsageKafkaTemplate.send(this.billingUsageTopic, tallySummary);
```suggestion
        this.billableUsageTopic);
    billableUsageKafkaTemplate.send(this.billableUsageTopic, tallySummary);
```

2022-05-17 13:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducer.java
> +    billingUsageKafkaTemplate.send(this.billingUsageTopic, tallySummary);
```suggestion
        this.billableUsageTopic);
    billableUsageKafkaTemplate.send(this.billableUsageTopic, tallySummary);
```

2022-05-17 13:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducerConfiguration.java
> +  public ProducerFactory<String, TallySummary> billingUsageProducerFactory(
```suggestion
  public ProducerFactory<String, TallySummary> billableUsageProducerFactory(
```

2022-05-17 13:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducerConfiguration.java
> +    return new KafkaTemplate<>(billingUsageProducerFactory);
```suggestion
  public KafkaTemplate<String, TallySummary> billingUsageKafkaTemplate(
      @Qualifier("billingUsageProducerFactory")
          ProducerFactory<String, TallySummary> billingUsageProducerFactory) {
    return new KafkaTemplate<>(billingUsageProducerFactory);
```
```suggestion
  public KafkaTemplate<String, TallySummary> billableUsageKafkaTemplate(
      @Qualifier("billableUsageProducerFactory")
          ProducerFactory<String, TallySummary> billableUsageProducerFactory) {
    return new KafkaTemplate<>(billableUsageProducerFactory);
```

2022-05-17 13:48 UTC, kahowell commented on src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducerConfiguration.java
> +  public TaskQueueProperties billingUsageTopicProperties() {
```suggestion
  public TaskQueueProperties billableUsageTopicProperties() {
```

2022-05-17 15:20 UTC, kahowell requested changes

2022-05-17 15:20 UTC, kahowell commented on src/main/resources/application-worker.yaml
> +        kafka-group-id: billing-producer-tally-summary-consumers
```suggestion
        kafka-group-id: swatch-producer-billing
```

2022-05-17 20:05 UTC, kahowell commented on src/main/resources/application-worker.yaml
> +        seek-override-timestamp: ${KAFKA_SEEK_OVERRIDE_TIMESTAMP:}
nitpick: too many spaces; please use 2 less:
```suggestion
      topic: platform.rhsm-subscriptions.tally
      kafka-group-id: swatch-producer-billing
      seek-override-end: ${KAFKA_SEEK_OVERRIDE_END:false}
      seek-override-timestamp: ${KAFKA_SEEK_OVERRIDE_TIMESTAMP:}
```

2022-05-18 14:12 UTC, mstead commented
Now sending BillableUsage messages to billable-usage topic and and fixed the formatting.

Should be the last thing needed here.

2022-05-18 14:14 UTC, kahowell approved these changes

2022-05-18 19:37 UTC, merged